export type UiLang = "en" | "hi" | "te" | "bn" | "mr" | "ta";

export const UI_LANG_CODES = ["en", "hi", "te", "bn", "mr", "ta"] as const;

export function isUiLang(value: string): value is UiLang {
  return (UI_LANG_CODES as readonly string[]).includes(value);
}

export const STRINGS: Record<UiLang, Record<string, string>> = {
  en: {
    APP_EYEBROW: "APPLICANT WORKSPACE",
    APP_TITLE_A: "Turn your village into a ",
    APP_TITLE_B: "bankable decision.",
    APP_SUB:
      "Enter your village, margin and business — GramIntel checks hyper-local signals, matches the right SCA scheme, and builds your financial plan. All in your language.",
    LOGIN_TITLE: "APPLICANT LOGIN",
    LOGIN_SECURE: "Secure · OTP + Google",
    LOGIN_GOOGLE: "Continue with Google",
    LOGIN_OR_OTP: "OR OTP",
    LOGIN_EMAIL: "Email",
    LOGIN_SEND_OTP: "Send OTP",
    LOGIN_SENDING: "Sending…",
    LOGIN_OTP: "OTP code",
    LOGIN_VERIFY: "Verify & continue",
    LOGIN_VERIFYING: "Verifying…",
    LOGIN_BACK: "Back",
    INPUTS_TITLE: "YOUR BUSINESS INPUTS",
    INPUTS_PS_NOTE: "PS: village / block / district + margin + category",
    F_VILLAGE: "Village",
    F_BLOCK: "Block",
    F_DISTRICT: "District",
    F_MARGIN: "Available margin capital (₹)",
    F_MARGIN_HINT: "Project cost = margin / 10% →",
    F_CATEGORY: "Business category",
    LANG_LABEL: "Narrative language",
    BTN_ANALYZE: "Analyze my business → feasibility + financial plan",
    BTN_ANALYZING: "Synthesising hyper-local signals…",
    BTN_LOGIN_FIRST: "Log in to analyze",
    MSG_FILL_LOCATION: "Fill village / block / district",
    MSG_BAD_MARGIN: "Enter valid margin capital",
    MSG_LOGIN_FIRST: "Please log in first (OTP above)",
    EMPTY_STATE:
      "No analysis yet. Fill the inputs above and click Analyze — you’ll get all 6 PS signals + the PS-verbatim scheme router and a quarterly repayment table with moratorium, in EN/हि/ते.",
    R_MARKET: "MARKET REACH · 5–10KM",
    R_OPPORTUNITY: "OPPORTUNITY ANALYSIS",
    R_VALUE: "PRODUCT MARKET VALUE",
    R_WORKING_CAP: "WORKING CAPITAL · ESTIMATE",
    R_SWOT: "SWOT",
    R_NARRATIVES: "NARRATIVE",
    R_CASES: "YOUR CASES",
    APPLY_TITLE: "READY TO APPLY?",
    APPLY_SUB: "Submit this case for officer review",
    APPLY_STATUS: "Status: DRAFT → SUBMITTED → UNDER_REVIEW → APPROVED/REJECTED",
    BTN_SUBMIT: "Submit case #",
    ST_SUBMITTING: "Submitting…",
    ST_SUBMITTED: "✓ Submitted",
    BTN_PRINT: "Print / Save PDF",
    EMI_MONTH: "EMI / MONTH",
    EMI_QUARTER: "EMI / QUARTER",
    QTR_SUFFIX: "/qtr",
    QTR_PER_PS: "×3 · quarterly per PS",
    TOTAL_PAYABLE: "TOTAL PAYABLE",
    INTEREST_WORD: "interest",
    QUARTERLY_SCHEDULE: "QUARTERLY SCHEDULE",
    SCHEDULE_PAUSE: "{n}-mo pause · then {amt}/qtr",
    SCHEME_MORA: "{m}-mo moratorium",
    SCHEME_YEARS: "{y}y",
    PROJECT_WORD: "project",
    LOAN_WORD: "loan",
    TH_QTR: "Qtr",
    TH_MONTHS: "Months",
    TH_EMI: "EMI",
    TH_PRINCIPAL: "Principal",
    TH_INTEREST: "Interest",
    TH_BALANCE: "Balance",
    MORATORIUM: "moratorium",
    EMI_FORMULA: "EMI = P·r·(1+r)ⁿ/((1+r)ⁿ−1) · P {loan} · {rate}%/12 · n {n} ⇒ {emi}/mo · {qtr}/qtr · {mora}mo moratorium",
    WC_MONTHLY_OPEX: "Monthly opex",
    WC_CONTINGENCY: "Contingency (10%)",
    WC_FIRST_YEAR: "First-year outlay",
    WC_3MO: "3-month working capital",
    WC_NOTE_DEFAULT: "Planning estimates",
    BANNER_DEMO: "Live places temporarily unavailable — showing demo density",
    BANNER_LOCATING: "Locating village…",
    CONSUMERS_WORD: "consumers",
    COMPETITORS_WORD: "competitors",
    CHANNELS_LABEL: "Channels:",
    AVG_WORD: "avg",
    BADGE_LIVE: "verified · live OSM",
    BADGE_DEMO: "demo density",
    CASE_WORD: "CASE #",
    PILL_COMP_MAP: "Competitor mapping:",
    PILL_THREATS: "Threats:",
    MEDIAN_WORD: "Median",
    APPLY_DONE: "Submitted — case #{id} is now under review",
    VIABILITY_SCORE: "VIABILITY SCORE",
    CHAT_ADVISOR: "AI CASE ADVISOR",
    CHAT_STATUS_THINKING: "Thinking…",
    CHAT_STATUS_IDLE: "Ask about this case",
    CHAT_INTRO: "I review case #{id}'s feasibility, financial plan and market data to help you understand your own business — how much loan you can get, what competes nearby, and whether you can repay.",
    CHAT_SUGGEST_1: "How much loan can I get for this business?",
    CHAT_SUGGEST_2: "What businesses compete near me?",
    CHAT_SUGGEST_3: "Will I be able to repay comfortably?",
    CHAT_SUGGEST_4: "Summarize the study for me",
    CHAT_SEND: "Send",
    CHAT_PLACEHOLDER: "Ask about case #{id}…",
    CHAT_BTN: "Chat about this case",
    CHAT_OFFLINE: "⚠ AI service unreachable — showing fallback assessment.",
    CHAT_ERR: "Sorry, something went wrong on my end. Please try again.",
    CHAT_NO_RESPONSE: "I couldn't reach the analysis service. Please retry — the case data is loaded and should connect shortly.",
  },
  hi: {
    APP_EYEBROW: "आवेदक कार्यक्षेत्र",
    APP_TITLE_A: "अपने गाँव को ",
    APP_TITLE_B: "बैंक-योग्य निर्णय में बदलें।",
    APP_SUB:
      "अपना गाँव, मार्जिन और व्यवसाय दर्ज करें — GramIntel अति-स्थानीय संकेतों की जाँच करता है, सही SCA योजना से मिलान करता है और आपकी वित्तीय योजना बनाता है। सब कुछ आपकी भाषा में।",
    LOGIN_TITLE: "आवेदक लॉगिन",
    LOGIN_SECURE: "सुरक्षित · OTP + Google",
    LOGIN_GOOGLE: "Google से जारी रखें",
    LOGIN_OR_OTP: "या OTP",
    LOGIN_EMAIL: "ईमेल",
    LOGIN_SEND_OTP: "OTP भेजें",
    LOGIN_SENDING: "भेजा जा रहा है…",
    LOGIN_OTP: "OTP कोड",
    LOGIN_VERIFY: "सत्यापित करें और आगे बढ़ें",
    LOGIN_VERIFYING: "सत्यापन हो रहा है…",
    LOGIN_BACK: "वापस",
    INPUTS_TITLE: "आपके व्यवसाय की जानकारी",
    INPUTS_PS_NOTE: "PS: गाँव / प्रखंड / जिला + मार्जिन + श्रेणी",
    F_VILLAGE: "गाँव",
    F_BLOCK: "प्रखंड",
    F_DISTRICT: "जिला",
    F_MARGIN: "उपलब्ध मार्जिन पूँजी (₹)",
    F_MARGIN_HINT: "परियोजना लागत = मार्जिन / 10% →",
    F_CATEGORY: "व्यवसाय श्रेणी",
    LANG_LABEL: "विवरण की भाषा",
    BTN_ANALYZE: "मेरे व्यवसाय का विश्लेषण करें → व्यवहार्यता + वित्तीय योजना",
    BTN_ANALYZING: "अति-स्थानीय संकेतों का विश्लेषण हो रहा है…",
    BTN_LOGIN_FIRST: "विश्लेषण के लिए लॉगिन करें",
    MSG_FILL_LOCATION: "गाँव / प्रखंड / जिला भरें",
    MSG_BAD_MARGIN: "सही मार्जिन पूँजी दर्ज करें",
    MSG_LOGIN_FIRST: "कृपया पहले लॉगिन करें (ऊपर OTP)",
    EMPTY_STATE:
      "अभी कोई विश्लेषण नहीं है। ऊपर जानकारी भरें और विश्लेषण पर क्लिक करें — आपको सभी 6 PS संकेत + PS-अनुसार योजना चयन और अधिस्थगन सहित त्रैमासिक पुनर्भुगतान तालिका मिलेगी, EN/हिं/ते में।",
    R_MARKET: "बाज़ार पहुँच · 5–10 कि.मी.",
    R_OPPORTUNITY: "अवसर विश्लेषण",
    R_VALUE: "उत्पाद बाज़ार मूल्य",
    R_WORKING_CAP: "कार्यशील पूँजी · अनुमान",
    R_SWOT: "SWOT",
    R_NARRATIVES: "विवरण",
    R_CASES: "आपके केस",
    APPLY_TITLE: "आवेदन के लिए तैयार?",
    APPLY_SUB: "अधिकारी समीक्षा हेतु यह केस जमा करें",
    APPLY_STATUS: "स्थिति: DRAFT → SUBMITTED → UNDER_REVIEW → APPROVED/REJECTED",
    BTN_SUBMIT: "केस जमा करें #",
    ST_SUBMITTING: "जमा किया जा रहा है…",
    ST_SUBMITTED: "✓ जमा किया गया",
    BTN_PRINT: "प्रिंट / PDF सहेजें",
    EMI_MONTH: "EMI / माह",
    EMI_QUARTER: "EMI / तिमाही",
    QTR_SUFFIX: "/तिमाही",
    QTR_PER_PS: "×3 · PS अनुसार त्रैमासिक",
    TOTAL_PAYABLE: "कुल देय राशि",
    INTEREST_WORD: "ब्याज",
    QUARTERLY_SCHEDULE: "त्रैमासिक अनुसूची",
    SCHEDULE_PAUSE: "{n}-माह विराम · फिर {amt}/तिमाही",
    SCHEME_MORA: "{m}-माह अधिस्थगन",
    SCHEME_YEARS: "{y} वर्ष",
    PROJECT_WORD: "परियोजना",
    LOAN_WORD: "ऋण",
    TH_QTR: "तिमाही",
    TH_MONTHS: "माह",
    TH_EMI: "EMI",
    TH_PRINCIPAL: "मूलधन",
    TH_INTEREST: "ब्याज",
    TH_BALANCE: "शेष",
    MORATORIUM: "अधिस्थगन",
    EMI_FORMULA: "EMI = P·r·(1+r)ⁿ/((1+r)ⁿ−1) · P {loan} · {rate}%/12 · n {n} ⇒ {emi}/माह · {qtr}/तिमाही · {mora}माह अधिस्थगन",
    WC_MONTHLY_OPEX: "मासिक संचालन व्यय",
    WC_CONTINGENCY: "आकस्मिकता (10%)",
    WC_FIRST_YEAR: "प्रथम-वर्ष परिव्यय",
    WC_3MO: "3-माह कार्यशील पूँजी",
    WC_NOTE_DEFAULT: "योजना अनुमान",
    BANNER_DEMO: "लाइव स्थान अस्थायी रूप से अनुपलब्ध — डेमो घनत्व दिखाया जा रहा है",
    BANNER_LOCATING: "गाँव की स्थिति ज्ञात की जा रही है…",
    CONSUMERS_WORD: "उपभोक्ता",
    COMPETITORS_WORD: "प्रतिस्पर्धी",
    CHANNELS_LABEL: "चैनल:",
    AVG_WORD: "औसत",
    BADGE_LIVE: "सत्यापित · लाइव OSM",
    BADGE_DEMO: "डेमो घनत्व",
    CASE_WORD: "केस #",
    PILL_COMP_MAP: "प्रतिस्पर्धी मानचित्रण:",
    PILL_THREATS: "खतरे:",
    MEDIAN_WORD: "माध्यिका",
    APPLY_DONE: "जमा किया गया — केस #{id} अब समीक्षा में है",
    VIABILITY_SCORE: "व्यवहार्यता स्कोर",
    CHAT_ADVISOR: "AI केस सलाहकार",
    CHAT_STATUS_THINKING: "सोच रहा है…",
    CHAT_STATUS_IDLE: "इस केस के बारे में पूछें",
    CHAT_INTRO: "मैं केस #{id} की व्यवहार्यता, वित्तीय योजना और बाज़ार आँकड़ों की समीक्षा करता हूँ ताकि आप अपने व्यवसाय को समझ सकें — आपको कितना ऋण मिलेगा, आसपास क्या प्रतिस्पर्धा है, और क्या आप आराम से चुका सकते हैं।",
    CHAT_SUGGEST_1: "इस व्यवसाय के लिए मुझे कितना ऋण मिलेगा?",
    CHAT_SUGGEST_2: "मेरे पास कौन से व्यवसाय प्रतिस्पर्धा में हैं?",
    CHAT_SUGGEST_3: "क्या मैं आराम से चुका पाऊँगा?",
    CHAT_SUGGEST_4: "अध्ययन का सारांश दें",
    CHAT_SEND: "भेजें",
    CHAT_PLACEHOLDER: "केस #{id} के बारे में पूछें…",
    CHAT_BTN: "इस केस पर चैट करें",
    CHAT_OFFLINE: "⚠ AI सेवा अनुपलब्ध — फ़ॉलबैक आकलन दिखाया जा रहा है।",
    CHAT_ERR: "क्षमा करें, मेरी ओर से कुछ गड़बड़ हो गई। कृपया पुनः प्रयास करें।",
    CHAT_NO_RESPONSE: "मैं विश्लेषण सेवा तक नहीं पहुँच सका। कृपया पुनः प्रयास करें — केस डेटा लोड है और जल्द ही जुड़ जाना चाहिए।",
  },
  te: {
    APP_EYEBROW: "దరఖాస్తుదారు కార్యస్థలం",
    APP_TITLE_A: "మీ గ్రామాన్ని ",
    APP_TITLE_B: "బ్యాంకు-యోగ్య నిర్ణయంగా మార్చండి.",
    APP_SUB:
      "మీ గ్రామం, మార్జిన్ మరియు వ్యాపారాన్ని నమోదు చేయండి — GramIntel అతి-స్థానిక సంకేతాలను పరిశీలిస్తుంది, సరైన SCA పథకంతో జత చేస్తుంది మరియు మీ ఆర్థిక ప్రణాళికను రూపొందిస్తుంది. అన్నీ మీ భాషలో.",
    LOGIN_TITLE: "దరఖాస్తుదారు లాగిన్",
    LOGIN_SECURE: "సురక్షితం · OTP + Google",
    LOGIN_GOOGLE: "Googleతో కొనసాగండి",
    LOGIN_OR_OTP: "లేదా OTP",
    LOGIN_EMAIL: "ఈమెయిల్",
    LOGIN_SEND_OTP: "OTP పంపండి",
    LOGIN_SENDING: "పంపుతోంది…",
    LOGIN_OTP: "OTP కోడ్",
    LOGIN_VERIFY: "ధృవీకరించి కొనసాగండి",
    LOGIN_VERIFYING: "ధృవీకరిస్తోంది…",
    LOGIN_BACK: "వెనుకకు",
    INPUTS_TITLE: "మీ వ్యాపార వివరాలు",
    INPUTS_PS_NOTE: "PS: గ్రామం / బ్లాక్ / జిల్లా + మార్జిన్ + వర్గం",
    F_VILLAGE: "గ్రామం",
    F_BLOCK: "బ్లాక్",
    F_DISTRICT: "జిల్లా",
    F_MARGIN: "అందుబాటులోని మార్జిన్ మూలధనం (₹)",
    F_MARGIN_HINT: "ప్రాజెక్ట్ వ్యయం = మార్జిన్ / 10% →",
    F_CATEGORY: "వ్యాపార వర్గం",
    LANG_LABEL: "కథన భాష",
    BTN_ANALYZE: "నా వ్యాపారాన్ని విశ్లేషించండి → సాధ్యత + ఆర్థిక ప్రణాళిక",
    BTN_ANALYZING: "అతి-స్థానిక సంకేతాలను విశ్లేషిస్తోంది…",
    BTN_LOGIN_FIRST: "విశ్లేషణ కోసం లాగిన్ చేయండి",
    MSG_FILL_LOCATION: "గ్రామం / బ్లాక్ / జిల్లా నమోదు చేయండి",
    MSG_BAD_MARGIN: "సరైన మార్జిన్ మూలధనాన్ని నమోదు చేయండి",
    MSG_LOGIN_FIRST: "దయచేసి ముందుగా లాగిన్ చేయండి (పైన OTP)",
    EMPTY_STATE:
      "ఇంకా విశ్లేషణ లేదు. పైన వివరాలు నింపి విశ్లేషణపై క్లిక్ చేయండి — మీకు అన్ని 6 PS సంకేతాలు + PS ప్రకారం పథక ఎంపిక మరియు మారటోరియంతో త్రైమాసిక తిరిగి చెల్లింపు పట్టిక లభిస్తుంది, EN/హి/తెలో.",
    R_MARKET: "మార్కెట్ పరిధి · 5–10 కి.మీ.",
    R_OPPORTUNITY: "అవకాశాల విశ్లేషణ",
    R_VALUE: "ఉత్పత్తి మార్కెట్ విలువ",
    R_WORKING_CAP: "నిర్వహణ మూలధనం · అంచనా",
    R_SWOT: "SWOT",
    R_NARRATIVES: "కథనం",
    R_CASES: "మీ కేసులు",
    APPLY_TITLE: "దరఖాస్తుకు సిద్ధంగా ఉన్నారా?",
    APPLY_SUB: "అధికారి సమీక్ష కోసం ఈ కేసును సమర్పించండి",
    APPLY_STATUS: "స్థితి: DRAFT → SUBMITTED → UNDER_REVIEW → APPROVED/REJECTED",
    BTN_SUBMIT: "కేసు సమర్పించండి #",
    ST_SUBMITTING: "సమర్పిస్తోంది…",
    ST_SUBMITTED: "✓ సమర్పించబడింది",
    BTN_PRINT: "ప్రింట్ / PDF సేవ్ చేయండి",
    EMI_MONTH: "EMI / నెల",
    EMI_QUARTER: "EMI / త్రైమాసికం",
    QTR_SUFFIX: "/త్రైమాసికం",
    QTR_PER_PS: "×3 · PS ప్రకారం త్రైమాసికం",
    TOTAL_PAYABLE: "మొత్తం చెల్లించవలసిన మొత్తం",
    INTEREST_WORD: "వడ్డీ",
    QUARTERLY_SCHEDULE: "త్రైమాసిక షెడ్యూల్",
    SCHEDULE_PAUSE: "{n}-నెలల విరామం · తర్వాత {amt}/త్రైమాసికం",
    SCHEME_MORA: "{m}-నెలల మారటోరియం",
    SCHEME_YEARS: "{y} సం.",
    PROJECT_WORD: "ప్రాజెక్ట్",
    LOAN_WORD: "రుణం",
    TH_QTR: "త్రైమా.",
    TH_MONTHS: "నెలలు",
    TH_EMI: "EMI",
    TH_PRINCIPAL: "అసలు",
    TH_INTEREST: "వడ్డీ",
    TH_BALANCE: "మిగులు",
    MORATORIUM: "మారటోరియం",
    EMI_FORMULA: "EMI = P·r·(1+r)ⁿ/((1+r)ⁿ−1) · P {loan} · {rate}%/12 · n {n} ⇒ {emi}/నెల · {qtr}/త్రైమాసికం · {mora}నెలల మారటోరియం",
    WC_MONTHLY_OPEX: "నెలవారీ నిర్వహణ వ్యయం",
    WC_CONTINGENCY: "అనుకోని ఖర్చులు (10%)",
    WC_FIRST_YEAR: "మొదటి సంవత్సర వ్యయం",
    WC_3MO: "3-నెలల నిర్వహణ మూలధనం",
    WC_NOTE_DEFAULT: "ప్రణాళిక అంచనాలు",
    BANNER_DEMO: "లైవ్ ప్రదేశాలు తాత్కాలికంగా అందుబాటులో లేవు — డెమో సాంద్రత చూపుతోంది",
    BANNER_LOCATING: "గ్రామాన్ని గుర్తిస్తోంది…",
    CONSUMERS_WORD: "వినియోగదారులు",
    COMPETITORS_WORD: "పోటీదారులు",
    CHANNELS_LABEL: "మార్గాలు:",
    AVG_WORD: "సగటు",
    BADGE_LIVE: "ధృవీకరించబడింది · లైవ్ OSM",
    BADGE_DEMO: "డెమో సాంద్రత",
    CASE_WORD: "కేసు #",
    PILL_COMP_MAP: "పోటీదారుల మ్యాపింగ్:",
    PILL_THREATS: "ముప్పులు:",
    MEDIAN_WORD: "మధ్యగత",
    APPLY_DONE: "సమర్పించబడింది — కేసు #{id} ఇప్పుడు సమీక్షలో ఉంది",
    VIABILITY_SCORE: "సాధ్యత స్కోరు",
    CHAT_ADVISOR: "AI కేసు సలహాదారు",
    CHAT_STATUS_THINKING: "ఆలోచిస్తోంది…",
    CHAT_STATUS_IDLE: "ఈ కేసు గురించి అడగండి",
    CHAT_INTRO: "మీ స్వంత వ్యాపారాన్ని అర్థం చేసుకోవడానికి నేను కేసు #{id} యొక్క సాధ్యత, ఆర్థిక ప్రణాళిక మరియు మార్కెట్ డేటాను సమీక్షిస్తాను — మీకు ఎంత రుణం లభిస్తుంది, సమీపంలో ఏ పోటీ ఉంది, మరియు మీరు సౌకర్యంగా తిరిగి చెల్లించగలరా.",
    CHAT_SUGGEST_1: "ఈ వ్యాపారానికి నాకు ఎంత రుణం లభిస్తుంది?",
    CHAT_SUGGEST_2: "నా దగ్గర పోటీలో ఏ వ్యాపారాలు ఉన్నాయి?",
    CHAT_SUGGEST_3: "నేను సౌకర్యంగా తిరిగి చెల్లించగలనా?",
    CHAT_SUGGEST_4: "అధ్యయనాన్ని సంగ్రహించండి",
    CHAT_SEND: "పంపండి",
    CHAT_PLACEHOLDER: "కేసు #{id} గురించి అడగండి…",
    CHAT_BTN: "ఈ కేసుపై చాట్ చేయండి",
    CHAT_OFFLINE: "⚠ AI సేవ అందుబాటులో లేదు — ఫాల్‌బ్యాక్ అంచనా చూపుతోంది.",
    CHAT_ERR: "క్షమించండి, నా వైపు ఏదో తప్పు జరిగింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    CHAT_NO_RESPONSE: "విశ్లేషణ సేవను చేరుకోలేకపోయాను. దయచేసి మళ్లీ ప్రయత్నించండి — కేసు డేటా లోడ్ అయింది, త్వరలో కనెక్ట్ అవుతుంది.",
  },
  bn: {},
  mr: {},
  ta: {},
};

export function t(lang: UiLang, key: string): string {
  return STRINGS[lang]?.[key] ?? STRINGS.en[key] ?? key;
}

export const CATEGORIES: Record<UiLang, string[]> = {
  en: ["Dairy", "Retail", "Textile", "Food Processing", "Poultry", "Kirana", "Services", "Food"],
  hi: ["डेयरी", "खुदरा", "वस्त्र", "खाद्य प्रसंस्करण", "मुर्गी पालन", "किराना", "सेवाएँ", "खाद्य"],
  te: ["డెయిరీ", "రిటైల్", "వస్త్రాలు", "ఆహార ప్రాసెసింగ్", "కోళ్ల పెంపకం", "కిరాణా", "సేవలు", "ఆహారం"],
  bn: ["দুগ্ধ ব্যবসা", "খুচরা", "বস্ত্র", "খাদ্য প্রক্রিয়াকরণ", "পোল্ট্রি", "মুদি", "পরিষেবা", "খাদ্য"],
  mr: ["दुग्ध व्यवसाय", "किरकोळ", "कापड", "अन्न प्रक्रिया", "कुक्कुटपालन", "किराणा", "सेवा", "अन्न"],
  ta: ["பால் பண்ணை", "சில்லறை", "துணி", "உணவு பதப்படுத்தல்", "கோழிப்பண்ணை", "மளிகை", "சேவைகள்", "உணவு"],
};

export const DATA: Record<UiLang, Record<string, string>> = {
  en: {},
  hi: {
    "MARKET DEMAND": "बाज़ार मांग",
    "COMPETITION": "प्रतिस्पर्धा",
    "PRICING POWER": "मूल्य निर्धारण क्षमता",
    "SUPPLY ACCESS": "आपूर्ति पहुँच",
    "FINANCIAL FIT": "वित्तीय उपयुक्तता",
    "RISK EXPOSURE": "जोखिम स्तर",
    "rising milk spend in radius": "क्षेत्र में दूध पर व्यय बढ़ रहा है",
    "none value-added nearby": "आसपास कोई मूल्यवर्धित प्रतिस्पर्धी नहीं",
    "12–18% premium achievable": "12–18% प्रीमियम संभव",
    "3 co-ops within 6 km": "6 किमी के भीतर 3 सहकारी समितियाँ",
    "matches term-loan structure": "सावधि-ऋण संरचना के अनुरूप",
    "matches micro-loan structure": "सूक्ष्म-ऋण संरचना के अनुरूप",
    "seasonal dips · power supply": "मौसमी उतार-चढ़ाव · बिजली आपूर्ति",
    "Rising milk spend in 10km radius": "10 किमी क्षेत्र में दूध पर व्यय बढ़ रहा है",
    "3 co-ops within 6km — supply access reliable": "6 किमी के भीतर 3 सहकारी समितियाँ — आपूर्ति विश्वसनीय",
    "First-time entrepreneur risk; working capital discipline needed": "पहली बार उद्यम करने का जोखिम; कार्यशील पूँजी में अनुशासन आवश्यक",
    "Limited cold storage at village edge": "गाँव के छोर पर सीमित शीत भंडारण",
    "Seasonal dips (summer milk yield)": "मौसमी गिरावट (गर्मी में दूध उत्पादन में कमी)",
    "Single-buyer dependency if tied to one co-op": "एक सहकारी समिति से जुड़ने पर एकल-क्रेता निर्भरता",
    "Power supply intermittency": "बिजली आपूर्ति में रुकावट",
    "Kirana cluster": "किराना समूह",
    "Weekly haat": "साप्ताहिक हाट",
    "Co-op collection": "सहकारी संग्रह",
    "Roadside stalls": "सड़क किनारे ठेले",
    "Mobile vending": "चलती-फिरती बिक्री",
    "Underserved direct-to-home": "वंचित क्षेत्रों में घर-घर आपूर्ति",
    "Value-added dairy (paneer/curd)": "मूल्यवर्धित डेयरी (पनीर/दही)",
    "No value-added competitor within 3.4km": "3.4 किमी के भीतर कोई मूल्यवर्धित प्रतिस्पर्धी नहीं",
    "Milk collection + cold chain": "दूध संग्रह + शीत श्रृंखला",
    "3 co-ops within 6km, demand stable": "6 किमी के भीतर 3 सहकारी समितियाँ, मांग स्थिर",
    "Feed supply": "पशु आहार आपूर्ति",
    "Cattle feed depot 5.9km away": "पशु आहार डिपो 5.9 किमी दूर",
    "General retail mix": "सामान्य खुदरा मिश्रण",
    "Consistent demand, repeat customers": "स्थिर मांग, नियमित ग्राहक",
    "Premium opportunity in 10km radius": "10 किमी क्षेत्र में प्रीमियम अवसर",
    "Diversified risk": "विविधीकृत जोखिम",
    "per kg · value-added": "प्रति किग्रा · मूल्यवर्धित",
    "Planning estimates — confirm with your SCA officer": "योजना अनुमान — अपने SCA अधिकारी से पुष्टि करें",
    "1,240 consumers · rising milk spend": "1,240 उपभोक्ता · दूध पर बढ़ता खर्च",
    "7 direct · none value-added": "7 प्रत्यक्ष · कोई मूल्यवर्धित नहीं",
    "3 dairy co-ops within 6 km": "6 किमी के भीतर 3 डेयरी सहकारी समितियाँ",
    "GOOD POTENTIAL": "अच्छी संभावना",
    "MODERATE": "मध्यम",
    "LOW": "कम",
  },
  te: {
    "MARKET DEMAND": "మార్కెట్ డిమాండ్",
    "COMPETITION": "పోటీ",
    "PRICING POWER": "ధర నిర్ణయ శక్తి",
    "SUPPLY ACCESS": "సరఫరా లభ్యత",
    "FINANCIAL FIT": "ఆర్థిక అనుకూలత",
    "RISK EXPOSURE": "రిస్క్ స్థాయి",
    "rising milk spend in radius": "ప్రాంతంలో పాల వ్యయం పెరుగుతోంది",
    "none value-added nearby": "సమీపంలో విలువ ఆధారిత పోటీదారు లేరు",
    "12–18% premium achievable": "12–18% ప్రీమియం సాధ్యం",
    "3 co-ops within 6 km": "6 కి.మీ. పరిధిలో 3 సహకార సంఘాలు",
    "matches term-loan structure": "టర్మ్-లోన్ నిర్మాణానికి అనుగుణం",
    "matches micro-loan structure": "మైక్రో-లోన్ నిర్మాణానికి అనుగుణం",
    "seasonal dips · power supply": "కాలానుగుణ హెచ్చుతగ్గులు · విద్యుత్ సరఫరా",
    "Rising milk spend in 10km radius": "10 కి.మీ. పరిధిలో పాల వ్యయం పెరుగుతోంది",
    "3 co-ops within 6km — supply access reliable": "6 కి.మీ. పరిధిలో 3 సహకార సంఘాలు — సరఫరా నమ్మకమైనది",
    "First-time entrepreneur risk; working capital discipline needed": "తొలిసారి వ్యవస్థాపక రిస్క్; నిర్వహణ మూలధన క్రమశిక్షణ అవసరం",
    "Limited cold storage at village edge": "గ్రామ శివార్లలో పరిమిత శీతల నిల్వ",
    "Seasonal dips (summer milk yield)": "కాలానుగుణ తగ్గుదల (వేసవిలో పాల దిగుబడి తగ్గుతుంది)",
    "Single-buyer dependency if tied to one co-op": "ఒక సహకార సంఘంతో ముడిపడితే ఏక-కొనుగోలుదారు ఆధారపడటం",
    "Power supply intermittency": "విద్యుత్ సరఫరాలో అంతరాయం",
    "Kirana cluster": "కిరాణా సమూహం",
    "Weekly haat": "వారపు సంత",
    "Co-op collection": "సహకార సేకరణ",
    "Roadside stalls": "రోడ్డు పక్క దుకాణాలు",
    "Mobile vending": "సంచార విక్రయం",
    "Underserved direct-to-home": "సేవలందని ప్రాంతాల్లో ఇంటింటి సరఫరా",
    "Value-added dairy (paneer/curd)": "విలువ ఆధారిత డెయిరీ (పనీర్/పెరుగు)",
    "No value-added competitor within 3.4km": "3.4 కి.మీ. పరిధిలో విలువ ఆధారిత పోటీదారు లేరు",
    "Milk collection + cold chain": "పాల సేకరణ + శీతల గొలుసు",
    "3 co-ops within 6km, demand stable": "6 కి.మీ. పరిధిలో 3 సహకార సంఘాలు, డిమాండ్ స్థిరం",
    "Feed supply": "పశుగ్రాస సరఫరా",
    "Cattle feed depot 5.9km away": "పశుగ్రాస డిపో 5.9 కి.మీ. దూరంలో",
    "General retail mix": "సాధారణ రిటైల్ మిశ్రమం",
    "Consistent demand, repeat customers": "స్థిరమైన డిమాండ్, పునరావృత వినియోగదారులు",
    "Premium opportunity in 10km radius": "10 కి.మీ. పరిధిలో ప్రీమియం అవకాశం",
    "Diversified risk": "వైవిధ్యభరిత రిస్క్",
    "per kg · value-added": "కిలోకు · విలువ ఆధారిత",
    "Planning estimates — confirm with your SCA officer": "ప్రణాళిక అంచనాలు — మీ SCA అధికారితో నిర్ధారించండి",
    "1,240 consumers · rising milk spend": "1,240 వినియోగదారులు · పాలపై పెరుగుతున్న ఖర్చు",
    "7 direct · none value-added": "7 ప్రత్యక్ష పోటీ · విలువ ఆధారితవి లేవు",
    "3 dairy co-ops within 6 km": "6 కి.మీ.లో 3 పాడి సహకార సంఘాలు",
    "GOOD POTENTIAL": "మంచి అవకాశం",
    "MODERATE": "మధ్యస్థం",
    "LOW": "తక్కువ",
  },
  bn: {},
  mr: {},
  ta: {},
};

export const TEMPLATES: Record<UiLang, Record<string, string>> = {
  en: {
    SWOT_LIVE_STRENGTH: "{n} competitors mapped in 10km; demand density supports entry",
    DEMAND_NOTE: "₹{x}L/mo · {n} consumers",
    SAME_CATEGORY: "{n} same-category within 10km",
    CROWDING: "crowding from {n} rivals",
    PLACES_MAPPED: "{n} places mapped within 10km",
    PRICING_BAND_NOTE: "band {lo}–{hi} ({p}% spread)",
    PRICING_STRENGTH: "Pricing power {lo}–{hi} shows 12–18% premium achievable",
    PURCHASING_POWER: "₹{x}L monthly demand in 10km",
    COMP_NOTE_LIVE: "{n} shops · verified via OSM within 8km",
    COMP_NOTE_DEMO: "{n} shops · demo density",
    GENERIC_NICHE_DAILY: "{c} — daily needs",
    GENERIC_NICHE_VALUE: "{c} — value added",
  },
  hi: {
    SWOT_LIVE_STRENGTH: "{n} प्रतिस्पर्धी 10 किमी में दर्ज; मांग घनत्व प्रवेश का समर्थन करता है",
    DEMAND_NOTE: "₹{x} लाख/माह · {n} उपभोक्ता",
    SAME_CATEGORY: "10 किमी के भीतर {n} समान-श्रेणी प्रतिस्पर्धी",
    CROWDING: "{n} प्रतिद्वंद्वियों से भीड़",
    PLACES_MAPPED: "10 किमी के भीतर {n} स्थान दर्ज",
    PRICING_BAND_NOTE: "बैंड {lo}–{hi} ({p}% अंतर)",
    PRICING_STRENGTH: "मूल्य निर्धारण क्षमता {lo}–{hi}, 12–18% प्रीमियम संभव दर्शाती है",
    PURCHASING_POWER: "10 किमी में ₹{x} लाख मासिक मांग",
    COMP_NOTE_LIVE: "{n} दुकानें · OSM द्वारा 8 किमी के भीतर सत्यापित",
    COMP_NOTE_DEMO: "{n} दुकानें · डेमो घनत्व",
    GENERIC_NICHE_DAILY: "{c} — दैनिक आवश्यकताएँ",
    GENERIC_NICHE_VALUE: "{c} — मूल्यवर्धित",
  },
  te: {
    SWOT_LIVE_STRENGTH: "{n} పోటీదారులు 10 కి.మీ.లో నమోదయ్యారు; డిమాండ్ సాంద్రత ప్రవేశానికి అనుకూలం",
    DEMAND_NOTE: "₹{x} లక్షలు/నెల · {n} వినియోగదారులు",
    SAME_CATEGORY: "10 కి.మీ. పరిధిలో {n} ఒకే-వర్గం పోటీదారులు",
    CROWDING: "{n} ప్రత్యర్థుల వల్ల రద్దీ",
    PLACES_MAPPED: "10 కి.మీ. పరిధిలో {n} ప్రదేశాలు నమోదయ్యాయి",
    PRICING_BAND_NOTE: "బ్యాండ్ {lo}–{hi} ({p}% వ్యత్యాసం)",
    PRICING_STRENGTH: "ధర నిర్ణయ శక్తి {lo}–{hi}, 12–18% ప్రీమియం సాధ్యమని చూపుతోంది",
    PURCHASING_POWER: "10 కి.మీ.లో ₹{x} లక్షల నెలవారీ డిమాండ్",
    COMP_NOTE_LIVE: "{n} దుకాణాలు · 8 కి.మీ. పరిధిలో OSM ద్వారా ధృవీకరించబడింది",
    COMP_NOTE_DEMO: "{n} దుకాణాలు · డెమో సాంద్రత",
    GENERIC_NICHE_DAILY: "{c} — రోజువారీ అవసరాలు",
    GENERIC_NICHE_VALUE: "{c} — విలువ ఆధారిత",
  },
  bn: {},
  mr: {},
  ta: {},
};

Object.assign(STRINGS.bn, {
  APP_EYEBROW: "আবেদনকারীর কর্মক্ষেত্র", APP_TITLE_A: "আপনার গ্রামকে ", APP_TITLE_B: "ব্যাংকযোগ্য সিদ্ধান্তে বদলান।",
  APP_SUB: "আপনার গ্রাম, মার্জিন ও ব্যবসা লিখুন — GramIntel স্থানীয় সংকেত যাচাই করে, সঠিক SCA প্রকল্প বেছে দেয় এবং আর্থিক পরিকল্পনা তৈরি করে। সবকিছু আপনার ভাষায়।",
  LOGIN_TITLE: "আবেদনকারীর লগইন", LOGIN_SECURE: "নিরাপদ · OTP + Google", LOGIN_GOOGLE: "Google দিয়ে চালিয়ে যান", LOGIN_OR_OTP: "অথবা OTP", LOGIN_EMAIL: "ইমেল", LOGIN_SEND_OTP: "OTP পাঠান", LOGIN_SENDING: "পাঠানো হচ্ছে…", LOGIN_OTP: "OTP কোড", LOGIN_VERIFY: "যাচাই করে চালিয়ে যান", LOGIN_VERIFYING: "যাচাই হচ্ছে…", LOGIN_BACK: "পিছনে",
  INPUTS_TITLE: "আপনার ব্যবসার তথ্য", INPUTS_PS_NOTE: "PS: গ্রাম / ব্লক / জেলা + মার্জিন + শ্রেণি", F_VILLAGE: "গ্রাম", F_BLOCK: "ব্লক", F_DISTRICT: "জেলা", F_MARGIN: "উপলব্ধ মার্জিন মূলধন (₹)", F_MARGIN_HINT: "প্রকল্প ব্যয় = মার্জিন / 10% →", F_CATEGORY: "ব্যবসার শ্রেণি", LANG_LABEL: "বর্ণনার ভাষা",
  BTN_ANALYZE: "আমার ব্যবসা বিশ্লেষণ করুন → সম্ভাব্যতা + আর্থিক পরিকল্পনা", BTN_ANALYZING: "স্থানীয় সংকেত বিশ্লেষণ হচ্ছে…", BTN_LOGIN_FIRST: "বিশ্লেষণের জন্য লগইন করুন", MSG_FILL_LOCATION: "গ্রাম / ব্লক / জেলা পূরণ করুন", MSG_BAD_MARGIN: "সঠিক মার্জিন মূলধন লিখুন", MSG_LOGIN_FIRST: "দয়া করে আগে লগইন করুন (উপরে OTP)",
  EMPTY_STATE: "এখনও কোনো বিশ্লেষণ নেই। উপরের তথ্য পূরণ করে বিশ্লেষণে ক্লিক করুন — আপনি ৬টি PS সংকেত, সঠিক প্রকল্প নির্বাচন এবং স্থগিতকালসহ ত্রৈমাসিক পরিশোধের তালিকা পাবেন।", R_MARKET: "বাজারের পরিধি · ৫–১০ কিমি", R_OPPORTUNITY: "সুযোগ বিশ্লেষণ", R_VALUE: "পণ্যের বাজারমূল্য", R_WORKING_CAP: "কার্যকরী মূলধন · অনুমান", R_SWOT: "SWOT", R_NARRATIVES: "বর্ণনা", R_CASES: "আপনার কেস",
  APPLY_TITLE: "আবেদন করতে প্রস্তুত?", APPLY_SUB: "অফিসারের পর্যালোচনার জন্য এই কেস জমা দিন", APPLY_STATUS: "অবস্থা: DRAFT → SUBMITTED → UNDER_REVIEW → APPROVED/REJECTED", BTN_SUBMIT: "কেস জমা দিন #", ST_SUBMITTING: "জমা হচ্ছে…", ST_SUBMITTED: "✓ জমা হয়েছে", BTN_PRINT: "প্রিন্ট / PDF সংরক্ষণ করুন",
  EMI_MONTH: "EMI / মাস", EMI_QUARTER: "EMI / ত্রৈমাসিক", QTR_SUFFIX: "/ত্রৈমাসিক", QTR_PER_PS: "×৩ · PS অনুযায়ী ত্রৈমাসিক", TOTAL_PAYABLE: "মোট পরিশোধযোগ্য", INTEREST_WORD: "সুদ", QUARTERLY_SCHEDULE: "ত্রৈমাসিক সময়সূচি", SCHEDULE_PAUSE: "{n}-মাস বিরতি · তারপর {amt}/ত্রৈমাসিক", SCHEME_MORA: "{m}-মাস স্থগিতকাল", SCHEME_YEARS: "{y} বছর", PROJECT_WORD: "প্রকল্প", LOAN_WORD: "ঋণ", TH_QTR: "ত্রৈমাসিক", TH_MONTHS: "মাস", TH_EMI: "EMI", TH_PRINCIPAL: "মূলধন", TH_INTEREST: "সুদ", TH_BALANCE: "বকেয়া", MORATORIUM: "স্থগিতকাল", EMI_FORMULA: "EMI = P·r·(1+r)ⁿ/((1+r)ⁿ−1) · P {loan} · {rate}%/12 · n {n} ⇒ {emi}/মাস · {qtr}/ত্রৈমাসিক · {mora}মাস স্থগিতকাল",
  WC_MONTHLY_OPEX: "মাসিক পরিচালন ব্যয়", WC_CONTINGENCY: "আকস্মিক খরচ (১০%)", WC_FIRST_YEAR: "প্রথম বছরের ব্যয়", WC_3MO: "৩ মাসের কার্যকরী মূলধন", WC_NOTE_DEFAULT: "পরিকল্পনার অনুমান", BANNER_DEMO: "লাইভ স্থান সাময়িকভাবে অনুপলব্ধ — ডেমো ঘনত্ব দেখানো হচ্ছে", BANNER_LOCATING: "গ্রাম খোঁজা হচ্ছে…", CONSUMERS_WORD: "ভোক্তা", COMPETITORS_WORD: "প্রতিযোগী", CHANNELS_LABEL: "চ্যানেল:", AVG_WORD: "গড়", BADGE_LIVE: "যাচাইকৃত · লাইভ OSM", BADGE_DEMO: "ডেমো ঘনত্ব", CASE_WORD: "কেস #", PILL_COMP_MAP: "প্রতিযোগী মানচিত্র:", PILL_THREATS: "ঝুঁকি:", MEDIAN_WORD: "মধ্যমা", APPLY_DONE: "জমা হয়েছে — কেস #{id} এখন পর্যালোচনায়", VIABILITY_SCORE: "সম্ভাব্যতা স্কোর",
  CHAT_ADVISOR: "AI কেস পরামর্শদাতা", CHAT_STATUS_THINKING: "ভাবছে…", CHAT_STATUS_IDLE: "এই কেস সম্পর্কে জিজ্ঞাসা করুন", CHAT_INTRO: "আমি কেস #{id}-এর সম্ভাব্যতা, আর্থিক পরিকল্পনা ও বাজারের তথ্য পর্যালোচনা করি — আপনি কত ঋণ পাবেন, আশেপাশে কী প্রতিযোগিতা আছে এবং স্বচ্ছন্দে শোধ করতে পারবেন কি না তা বুঝতে সাহায্য করি।", CHAT_SUGGEST_1: "এই ব্যবসার জন্য কত ঋণ পাব?", CHAT_SUGGEST_2: "আমার কাছে কোন ব্যবসাগুলি প্রতিযোগিতা করছে?", CHAT_SUGGEST_3: "আমি কি স্বচ্ছন্দে ঋণ শোধ করতে পারব?", CHAT_SUGGEST_4: "গবেষণার সারাংশ দিন", CHAT_SEND: "পাঠান", CHAT_PLACEHOLDER: "কেস #{id} সম্পর্কে জিজ্ঞাসা করুন…", CHAT_BTN: "এই কেস নিয়ে চ্যাট করুন", CHAT_OFFLINE: "⚠ AI পরিষেবা পাওয়া যাচ্ছে না — বিকল্প মূল্যায়ন দেখানো হচ্ছে।", CHAT_ERR: "দুঃখিত, একটি সমস্যা হয়েছে। আবার চেষ্টা করুন।", CHAT_NO_RESPONSE: "বিশ্লেষণ পরিষেবায় পৌঁছানো যায়নি। আবার চেষ্টা করুন — কেসের তথ্য লোড হয়েছে।",
});
Object.assign(STRINGS.mr, {
  APP_EYEBROW: "अर्जदार कार्यक्षेत्र", APP_TITLE_A: "तुमच्या गावाला ", APP_TITLE_B: "बँकेला योग्य निर्णयात बदला.", APP_SUB: "तुमचे गाव, मार्जिन आणि व्यवसाय भरा — GramIntel स्थानिक संकेत तपासते, योग्य SCA योजना निवडते आणि आर्थिक आराखडा तयार करते. सर्व काही तुमच्या भाषेत.", LOGIN_TITLE: "अर्जदार लॉगिन", LOGIN_SECURE: "सुरक्षित · OTP + Google", LOGIN_GOOGLE: "Google ने पुढे जा", LOGIN_OR_OTP: "किंवा OTP", LOGIN_EMAIL: "ईमेल", LOGIN_SEND_OTP: "OTP पाठवा", LOGIN_SENDING: "पाठवत आहे…", LOGIN_OTP: "OTP कोड", LOGIN_VERIFY: "पडताळून पुढे जा", LOGIN_VERIFYING: "पडताळणी सुरू आहे…", LOGIN_BACK: "मागे",
  INPUTS_TITLE: "तुमच्या व्यवसायाची माहिती", INPUTS_PS_NOTE: "PS: गाव / ब्लॉक / जिल्हा + मार्जिन + श्रेणी", F_VILLAGE: "गाव", F_BLOCK: "ब्लॉक", F_DISTRICT: "जिल्हा", F_MARGIN: "उपलब्ध मार्जिन भांडवल (₹)", F_MARGIN_HINT: "प्रकल्प खर्च = मार्जिन / 10% →", F_CATEGORY: "व्यवसाय श्रेणी", LANG_LABEL: "कथनाची भाषा", BTN_ANALYZE: "माझ्या व्यवसायाचे विश्लेषण करा → व्यवहार्यता + आर्थिक आराखडा", BTN_ANALYZING: "स्थानिक संकेतांचे विश्लेषण सुरू आहे…", BTN_LOGIN_FIRST: "विश्लेषणासाठी लॉगिन करा", MSG_FILL_LOCATION: "गाव / ब्लॉक / जिल्हा भरा", MSG_BAD_MARGIN: "योग्य मार्जिन भांडवल भरा", MSG_LOGIN_FIRST: "कृपया आधी लॉगिन करा (वरील OTP)", EMPTY_STATE: "अजून विश्लेषण नाही. वरील माहिती भरून विश्लेषणावर क्लिक करा — तुम्हाला ६ PS संकेत, योग्य योजना आणि स्थगितीसह त्रैमासिक परतफेड तक्ता मिळेल.",
  R_MARKET: "बाजार पोहोच · ५–१० किमी", R_OPPORTUNITY: "संधी विश्लेषण", R_VALUE: "उत्पादन बाजारमूल्य", R_WORKING_CAP: "कार्यकारी भांडवल · अंदाज", R_SWOT: "SWOT", R_NARRATIVES: "कथन", R_CASES: "तुमची प्रकरणे", APPLY_TITLE: "अर्ज करण्यास तयार?", APPLY_SUB: "अधिकाऱ्याच्या तपासणीसाठी हे प्रकरण जमा करा", APPLY_STATUS: "स्थिती: DRAFT → SUBMITTED → UNDER_REVIEW → APPROVED/REJECTED", BTN_SUBMIT: "प्रकरण जमा करा #", ST_SUBMITTING: "जमा करत आहे…", ST_SUBMITTED: "✓ जमा झाले", BTN_PRINT: "प्रिंट / PDF जतन करा",
  EMI_MONTH: "EMI / महिना", EMI_QUARTER: "EMI / तिमाही", QTR_SUFFIX: "/तिमाही", QTR_PER_PS: "×३ · PS नुसार तिमाही", TOTAL_PAYABLE: "एकूण देय", INTEREST_WORD: "व्याज", QUARTERLY_SCHEDULE: "तिमाही वेळापत्रक", SCHEDULE_PAUSE: "{n}-महिन्यांचा विराम · नंतर {amt}/तिमाही", SCHEME_MORA: "{m}-महिन्यांची स्थगिती", SCHEME_YEARS: "{y} वर्षे", PROJECT_WORD: "प्रकल्प", LOAN_WORD: "कर्ज", TH_QTR: "तिमाही", TH_MONTHS: "महिने", TH_EMI: "EMI", TH_PRINCIPAL: "मुद्दल", TH_INTEREST: "व्याज", TH_BALANCE: "शिल्लक", MORATORIUM: "स्थगिती", EMI_FORMULA: "EMI = P·r·(1+r)ⁿ/((1+r)ⁿ−1) · P {loan} · {rate}%/12 · n {n} ⇒ {emi}/महिना · {qtr}/तिमाही · {mora}महिने स्थगिती", WC_MONTHLY_OPEX: "मासिक संचालन खर्च", WC_CONTINGENCY: "आकस्मिकता (१०%)", WC_FIRST_YEAR: "पहिल्या वर्षाचा खर्च", WC_3MO: "३ महिन्यांचे कार्यकारी भांडवल", WC_NOTE_DEFAULT: "नियोजन अंदाज", BANNER_DEMO: "लाइव्ह ठिकाणे तात्पुरती अनुपलब्ध — डेमो घनता दाखवत आहे", BANNER_LOCATING: "गाव शोधत आहे…", CONSUMERS_WORD: "ग्राहक", COMPETITORS_WORD: "स्पर्धक", CHANNELS_LABEL: "चॅनेल:", AVG_WORD: "सरासरी", BADGE_LIVE: "पडताळलेले · लाइव्ह OSM", BADGE_DEMO: "डेमो घनता", CASE_WORD: "प्रकरण #", PILL_COMP_MAP: "स्पर्धक नकाशा:", PILL_THREATS: "धोके:", MEDIAN_WORD: "मध्यक", APPLY_DONE: "जमा झाले — प्रकरण #{id} आता तपासणीत आहे", VIABILITY_SCORE: "व्यवहार्यता गुण",
  CHAT_ADVISOR: "AI प्रकरण सल्लागार", CHAT_STATUS_THINKING: "विचार करत आहे…", CHAT_STATUS_IDLE: "या प्रकरणाबद्दल विचारा", CHAT_INTRO: "मी प्रकरण #{id} ची व्यवहार्यता, आर्थिक आराखडा आणि बाजार माहिती पाहतो — तुम्हाला किती कर्ज मिळेल, जवळ कोणती स्पर्धा आहे आणि परतफेड शक्य आहे का हे समजावतो.", CHAT_SUGGEST_1: "या व्यवसायासाठी किती कर्ज मिळेल?", CHAT_SUGGEST_2: "माझ्याजवळ कोणते व्यवसाय स्पर्धेत आहेत?", CHAT_SUGGEST_3: "मी आरामात परतफेड करू शकेन का?", CHAT_SUGGEST_4: "अभ्यासाचा सारांश द्या", CHAT_SEND: "पाठवा", CHAT_PLACEHOLDER: "प्रकरण #{id} बद्दल विचारा…", CHAT_BTN: "या प्रकरणावर चॅट करा", CHAT_OFFLINE: "⚠ AI सेवा उपलब्ध नाही — पर्यायी अंदाज दाखवत आहे.", CHAT_ERR: "क्षमस्व, काहीतरी चूक झाली. पुन्हा प्रयत्न करा.", CHAT_NO_RESPONSE: "विश्लेषण सेवेशी संपर्क झाला नाही. पुन्हा प्रयत्न करा — प्रकरणाची माहिती लोड आहे.",
});
Object.assign(STRINGS.ta, {
  APP_EYEBROW: "விண்ணப்பதாரர் பணியிடம்", APP_TITLE_A: "உங்கள் கிராமத்தை ", APP_TITLE_B: "வங்கிக்கு ஏற்ற முடிவாக மாற்றுங்கள்.", APP_SUB: "உங்கள் கிராமம், மார்ஜின் மற்றும் தொழிலை உள்ளிடுங்கள் — GramIntel உள்ளூர் சந்தைச் சிக்னல்களைச் சரிபார்த்து, சரியான SCA திட்டத்தைத் தேர்ந்தெடுத்து, நிதித் திட்டத்தை உருவாக்கும். அனைத்தும் உங்கள் மொழியில்.", LOGIN_TITLE: "விண்ணப்பதாரர் உள்நுழைவு", LOGIN_SECURE: "பாதுகாப்பானது · OTP + Google", LOGIN_GOOGLE: "Google மூலம் தொடர்க", LOGIN_OR_OTP: "அல்லது OTP", LOGIN_EMAIL: "மின்னஞ்சல்", LOGIN_SEND_OTP: "OTP அனுப்புக", LOGIN_SENDING: "அனுப்பப்படுகிறது…", LOGIN_OTP: "OTP குறியீடு", LOGIN_VERIFY: "சரிபார்த்து தொடர்க", LOGIN_VERIFYING: "சரிபார்க்கிறது…", LOGIN_BACK: "பின்செல்",
  INPUTS_TITLE: "உங்கள் தொழில் விவரங்கள்", INPUTS_PS_NOTE: "PS: கிராமம் / வட்டம் / மாவட்டம் + மார்ஜின் + வகை", F_VILLAGE: "கிராமம்", F_BLOCK: "வட்டம்", F_DISTRICT: "மாவட்டம்", F_MARGIN: "கிடைக்கும் மார்ஜின் மூலதனம் (₹)", F_MARGIN_HINT: "திட்டச் செலவு = மார்ஜின் / 10% →", F_CATEGORY: "தொழில் வகை", LANG_LABEL: "கதை மொழி", BTN_ANALYZE: "என் தொழிலைப் பகுப்பாய்வு செய்க → சாத்தியம் + நிதித் திட்டம்", BTN_ANALYZING: "உள்ளூர் சிக்னல்களைப் பகுப்பாய்வு செய்கிறது…", BTN_LOGIN_FIRST: "பகுப்பாய்வுக்கு உள்நுழைக", MSG_FILL_LOCATION: "கிராமம் / வட்டம் / மாவட்டத்தை நிரப்புக", MSG_BAD_MARGIN: "சரியான மார்ஜின் மூலதனத்தை உள்ளிடுக", MSG_LOGIN_FIRST: "முதலில் உள்நுழைக (மேலே OTP)", EMPTY_STATE: "இன்னும் பகுப்பாய்வு இல்லை. மேலே உள்ள விவரங்களை நிரப்பி பகுப்பாய்வு செய்க என்பதைக் கிளிக் செய்யுங்கள் — 6 PS சிக்னல்கள், சரியான திட்டம் மற்றும் இடைக்காலத்துடன் காலாண்டு திருப்பிச் செலுத்தும் அட்டவணை கிடைக்கும்.",
  R_MARKET: "சந்தை வரம்பு · 5–10 கி.மீ.", R_OPPORTUNITY: "வாய்ப்பு பகுப்பாய்வு", R_VALUE: "தயாரிப்பு சந்தை மதிப்பு", R_WORKING_CAP: "செயல்பாட்டு மூலதனம் · மதிப்பீடு", R_SWOT: "SWOT", R_NARRATIVES: "கதை", R_CASES: "உங்கள் வழக்குகள்", APPLY_TITLE: "விண்ணப்பிக்க தயாரா?", APPLY_SUB: "அலுவலர் மதிப்பாய்வுக்கு இந்த வழக்கைச் சமர்ப்பிக்கவும்", APPLY_STATUS: "நிலை: DRAFT → SUBMITTED → UNDER_REVIEW → APPROVED/REJECTED", BTN_SUBMIT: "வழக்கைச் சமர்ப்பிக்கவும் #", ST_SUBMITTING: "சமர்ப்பிக்கிறது…", ST_SUBMITTED: "✓ சமர்ப்பிக்கப்பட்டது", BTN_PRINT: "அச்சிடு / PDF சேமி",
  EMI_MONTH: "EMI / மாதம்", EMI_QUARTER: "EMI / காலாண்டு", QTR_SUFFIX: "/காலாண்டு", QTR_PER_PS: "×3 · PS படி காலாண்டு", TOTAL_PAYABLE: "மொத்தம் செலுத்த வேண்டியது", INTEREST_WORD: "வட்டி", QUARTERLY_SCHEDULE: "காலாண்டு அட்டவணை", SCHEDULE_PAUSE: "{n}-மாத இடைநிறுத்தம் · பின்னர் {amt}/காலாண்டு", SCHEME_MORA: "{m}-மாத இடைக்காலம்", SCHEME_YEARS: "{y} ஆண்டுகள்", PROJECT_WORD: "திட்டம்", LOAN_WORD: "கடன்", TH_QTR: "காலாண்டு", TH_MONTHS: "மாதங்கள்", TH_EMI: "EMI", TH_PRINCIPAL: "முதல்தொகை", TH_INTEREST: "வட்டி", TH_BALANCE: "மீதம்", MORATORIUM: "இடைக்காலம்", EMI_FORMULA: "EMI = P·r·(1+r)ⁿ/((1+r)ⁿ−1) · P {loan} · {rate}%/12 · n {n} ⇒ {emi}/மாதம் · {qtr}/காலாண்டு · {mora}மாத இடைக்காலம்", WC_MONTHLY_OPEX: "மாதாந்திர இயக்கச் செலவு", WC_CONTINGENCY: "தற்செயல் செலவு (10%)", WC_FIRST_YEAR: "முதல் ஆண்டு செலவு", WC_3MO: "3 மாத செயல்பாட்டு மூலதனம்", WC_NOTE_DEFAULT: "திட்ட மதிப்பீடுகள்", BANNER_DEMO: "நேரடி இடங்கள் தற்காலிகமாக கிடைக்கவில்லை — டெமோ அடர்த்தி காட்டப்படுகிறது", BANNER_LOCATING: "கிராமத்தைக் கண்டறிகிறது…", CONSUMERS_WORD: "நுகர்வோர்", COMPETITORS_WORD: "போட்டியாளர்கள்", CHANNELS_LABEL: "வழிகள்:", AVG_WORD: "சராசரி", BADGE_LIVE: "சரிபார்க்கப்பட்டது · நேரடி OSM", BADGE_DEMO: "டெமோ அடர்த்தி", CASE_WORD: "வழக்கு #", PILL_COMP_MAP: "போட்டியாளர் வரைபடம்:", PILL_THREATS: "அச்சுறுத்தல்கள்:", MEDIAN_WORD: "இடைநிலை", APPLY_DONE: "சமர்ப்பிக்கப்பட்டது — வழக்கு #{id} மதிப்பாய்வில் உள்ளது", VIABILITY_SCORE: "சாத்தியக்கூறு மதிப்பெண்",
  CHAT_ADVISOR: "AI வழக்கு ஆலோசகர்", CHAT_STATUS_THINKING: "சிந்திக்கிறது…", CHAT_STATUS_IDLE: "இந்த வழக்கைப் பற்றி கேளுங்கள்", CHAT_INTRO: "வழக்கு #{id} இன் சாத்தியம், நிதித் திட்டம் மற்றும் சந்தைத் தரவைப் பார்வையிட்டு — கிடைக்கும் கடன், அருகிலுள்ள போட்டி, திருப்பிச் செலுத்தும் திறன் ஆகியவற்றைப் புரிந்துகொள்ள உதவுகிறேன்.", CHAT_SUGGEST_1: "இந்த தொழிலுக்கு எவ்வளவு கடன் கிடைக்கும்?", CHAT_SUGGEST_2: "எனக்கு அருகில் எந்த தொழில்கள் போட்டியிடுகின்றன?", CHAT_SUGGEST_3: "நான் வசதியாக திருப்பிச் செலுத்த முடியுமா?", CHAT_SUGGEST_4: "ஆய்வின் சுருக்கத்தைத் தருக", CHAT_SEND: "அனுப்பு", CHAT_PLACEHOLDER: "வழக்கு #{id} பற்றி கேளுங்கள்…", CHAT_BTN: "இந்த வழக்கில் அரட்டை", CHAT_OFFLINE: "⚠ AI சேவை கிடைக்கவில்லை — மாற்று மதிப்பீடு காட்டப்படுகிறது.", CHAT_ERR: "மன்னிக்கவும், ஏதோ தவறு ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.", CHAT_NO_RESPONSE: "பகுப்பாய்வு சேவையை அணுக முடியவில்லை. மீண்டும் முயற்சிக்கவும் — வழக்குத் தரவு ஏற்றப்பட்டுள்ளது.",
});

Object.assign(DATA.bn, { "MARKET DEMAND": "বাজারের চাহিদা", "COMPETITION": "প্রতিযোগিতা", "PRICING POWER": "মূল্য নির্ধারণের ক্ষমতা", "SUPPLY ACCESS": "সরবরাহের সুযোগ", "FINANCIAL FIT": "আর্থিক উপযুক্ততা", "RISK EXPOSURE": "ঝুঁকির মাত্রা", "GOOD POTENTIAL": "ভালো সম্ভাবনা", "MODERATE": "মাঝারি", "LOW": "কম",
  "rising milk spend in radius": "এলাকায় দুধে ব্যয় বাড়ছে", "none value-added nearby": "কাছে কোনো মূল্য সংযোজন প্রতিযোগী নেই", "12–18% premium achievable": "১২–১৮% প্রিমিয়াম সম্ভব", "3 co-ops within 6 km": "৬ কিমির মধ্যে ৩টি সমবায় সমিতি", "matches term-loan structure": "মেয়াদি ঋণ কাঠামোর সঙ্গে মানানসই", "matches micro-loan structure": "ক্ষুদ্র ঋণ কাঠামোর সঙ্গে মানানসই", "seasonal dips · power supply": "মৌসুমি ওঠানামা · বিদ্যুৎ সরবরাহ",
  "Rising milk spend in 10km radius": "১০ কিমি এলাকায় দুধে ব্যয় বাড়ছে", "3 co-ops within 6km — supply access reliable": "৬ কিমির মধ্যে ৩টি সমবায় — সরবরাহ নির্ভরযোগ্য", "First-time entrepreneur risk; working capital discipline needed": "প্রথমবারের উদ্যোক্তা ঝুঁকি; কার্যকরী মূলধনে শৃঙ্খলা দরকার", "Limited cold storage at village edge": "গ্রামের প্রান্তে সীমিত হিম সংরক্ষণ", "Seasonal dips (summer milk yield)": "মৌসুমি পতন (গ্রীষ্মে দুধ উৎপাদন কমে)", "Single-buyer dependency if tied to one co-op": "এক সমবায়ের সঙ্গে বাঁধা থাকলে একক ক্রেতা নির্ভরতা", "Power supply intermittency": "বিদ্যুৎ সরবরাহে বিঘ্ন",
  "Kirana cluster": "মুদি দোকান গুচ্ছ", "Weekly haat": "সাপ্তাহিক হাট", "Co-op collection": "সমবায় সংগ্রহ", "Roadside stalls": "রাস্তার পাশের দোকান", "Mobile vending": "ভ্রাম্যমাণ বিক্রি", "Underserved direct-to-home": "বঞ্চিত এলাকায় বাড়ি বাড়ি সরবরাহ",
  "Value-added dairy (paneer/curd)": "মূল্য সংযোজন দুগ্ধ (পনির/দই)", "No value-added competitor within 3.4km": "৩.৪ কিমির মধ্যে কোনো মূল্য সংযোজন প্রতিযোগী নেই", "Milk collection + cold chain": "দুধ সংগ্রহ + হিম শৃঙ্খল", "3 co-ops within 6km, demand stable": "৬ কিমির মধ্যে ৩টি সমবায়, চাহিদা স্থিতিশীল", "Feed supply": "পশুখাদ্য সরবরাহ", "Cattle feed depot 5.9km away": "পশুখাদ্য ডিপো ৫.৯ কিমি দূরে", "General retail mix": "সাধারণ খুচরা মিশ্রণ", "Consistent demand, repeat customers": "স্থিতিশীল চাহিদা, নিয়মিত গ্রাহক", "Premium opportunity in 10km radius": "১০ কিমি এলাকায় প্রিমিয়াম সুযোগ", "Diversified risk": "বৈচিত্র্যময় ঝুঁকি",
  "per kg · value-added": "প্রতি কেজি · মূল্য সংযোজন", "Planning estimates — confirm with your SCA officer": "পরিকল্পনার অনুমান — আপনার SCA অফিসারের সঙ্গে নিশ্চিত করুন", "1,240 consumers · rising milk spend": "১,২৪০ ভোক্তা · দুধে বাড়তি ব্যয়", "7 direct · none value-added": "৭টি প্রত্যক্ষ · কোনো মূল্য সংযোজন নেই", "3 dairy co-ops within 6 km": "৬ কিমির মধ্যে ৩টি দুগ্ধ সমবায়" });
Object.assign(DATA.mr, { "MARKET DEMAND": "बाजारातील मागणी", "COMPETITION": "स्पर्धा", "PRICING POWER": "किंमत ठरवण्याची क्षमता", "SUPPLY ACCESS": "पुरवठ्याची उपलब्धता", "FINANCIAL FIT": "आर्थिक योग्यतेची", "RISK EXPOSURE": "जोखीम पातळी", "GOOD POTENTIAL": "चांगली क्षमता", "MODERATE": "मध्यम", "LOW": "कमी",
  "rising milk spend in radius": "परिसरात दुधावरील खर्च वाढत आहे", "none value-added nearby": "जवळपास कोणताही मूल्यवर्धित स्पर्धक नाही", "12–18% premium achievable": "१२–१८% प्रीमियम शक्य", "3 co-ops within 6 km": "६ किमीमध्ये ३ सहकारी संस्था", "matches term-loan structure": "मुदत कर्ज रचनेला अनुरूप", "matches micro-loan structure": "सूक्ष्म कर्ज रचनेला अनुरूप", "seasonal dips · power supply": "हंगामी चढ-उतार · वीजपुरवठा",
  "Rising milk spend in 10km radius": "१० किमी परिसरात दुधावरील खर्च वाढत आहे", "3 co-ops within 6km — supply access reliable": "६ किमीमध्ये ३ सहकारी संस्था — पुरवठा विश्वासार्ह", "First-time entrepreneur risk; working capital discipline needed": "पहिल्यांदा उद्योजक होण्याचा धोका; खेळत्या भांडवलात शिस्त हवी", "Limited cold storage at village edge": "गावाच्या कडेला मर्यादित शीतगृह", "Seasonal dips (summer milk yield)": "हंगामी घट (उन्हाळ्यात दूध उत्पादन घटते)", "Single-buyer dependency if tied to one co-op": "एका संस्थेशी जोडले असल्यास एकल-खरेदीदार अवलंबित्व", "Power supply intermittency": "वीजपुरवठ्यात खंड",
  "Kirana cluster": "किराणा समूह", "Weekly haat": "साप्ताहिक बाजार", "Co-op collection": "सहकारी संकलन", "Roadside stalls": "रस्त्याकडेची दुकाने", "Mobile vending": "फिरती विक्री", "Underserved direct-to-home": "वंचित भागांत घरोघरी पुरवठा",
  "Value-added dairy (paneer/curd)": "मूल्यवर्धित दुग्ध (पनीर/दही)", "No value-added competitor within 3.4km": "३.४ किमीमध्ये कोणताही मूल्यवर्धित स्पर्धक नाही", "Milk collection + cold chain": "दूध संकलन + शीतसाखळी", "3 co-ops within 6km, demand stable": "६ किमीमध्ये ३ सहकारी संस्था, मागणी स्थिर", "Feed supply": "पशुखाद्य पुरवठा", "Cattle feed depot 5.9km away": "पशुखाद्य डेपो ५.९ किमी दूर", "General retail mix": "सामान्य किरकोळ मिश्रण", "Consistent demand, repeat customers": "स्थिर मागणी, नियमित ग्राहक", "Premium opportunity in 10km radius": "१० किमी परिसरात प्रीमियम संधी", "Diversified risk": "वैविध्यपूर्ण धोका",
  "per kg · value-added": "प्रति किलो · मूल्यवर्धित", "Planning estimates — confirm with your SCA officer": "नियोजन अंदाज — तुमच्या SCA अधिकाऱ्याशी खात्री करा", "1,240 consumers · rising milk spend": "१,२४० ग्राहक · दुधावरील वाढता खर्च", "7 direct · none value-added": "७ थेट · कोणतेही मूल्यवर्धित नाही", "3 dairy co-ops within 6 km": "६ किमीमध्ये ३ दुग्ध सहकारी संस्था" });
Object.assign(DATA.ta, { "MARKET DEMAND": "சந்தை தேவை", "COMPETITION": "போட்டி", "PRICING POWER": "விலை நிர்ணய திறன்", "SUPPLY ACCESS": "வழங்கல் அணுகல்", "FINANCIAL FIT": "நிதி பொருத்தம்", "RISK EXPOSURE": "ஆபத்து நிலை", "GOOD POTENTIAL": "நல்ல வாய்ப்பு", "MODERATE": "மிதமானது", "LOW": "குறைவு",
  "rising milk spend in radius": "பகுதியில் பால் செலவு அதிகரித்து வருகிறது", "none value-added nearby": "அருகில் மதிப்பு கூட்டிய போட்டியாளர் இல்லை", "12–18% premium achievable": "12–18% பிரீமியம் சாத்தியம்", "3 co-ops within 6 km": "6 கி.மீ.க்குள் 3 கூட்டுறவு சங்கங்கள்", "matches term-loan structure": "காலக்கடன் அமைப்புக்கு ஏற்றது", "matches micro-loan structure": "நுண்கடன் அமைப்புக்கு ஏற்றது", "seasonal dips · power supply": "பருவகால சரிவுகள் · மின்சார விநியோகம்",
  "Rising milk spend in 10km radius": "10 கி.மீ. பகுதியில் பால் செலவு அதிகரித்து வருகிறது", "3 co-ops within 6km — supply access reliable": "6 கி.மீ.க்குள் 3 கூட்டுறவு சங்கங்கள் — வழங்கல் நம்பகமானது", "First-time entrepreneur risk; working capital discipline needed": "முதல் முறை தொழில்முனைவோர் ஆபத்து; செயல்பாட்டு மூலதன ஒழுக்கம் தேவை", "Limited cold storage at village edge": "கிராம விளிம்பில் குறைந்த குளிர் சேமிப்பு", "Seasonal dips (summer milk yield)": "பருவகால சரிவு (கோடையில் பால் உற்பத்தி குறையும்)", "Single-buyer dependency if tied to one co-op": "ஒரு சங்கத்துடன் இணைந்தால் ஒற்றை வாங்குபவர் சார்பு", "Power supply intermittency": "மின்சார விநியோகத் தடை",
  "Kirana cluster": "மளிகைக் கடைத் தொகுப்பு", "Weekly haat": "வாரச் சந்தை", "Co-op collection": "கூட்டுறவு சேகரிப்பு", "Roadside stalls": "சாலையோரக் கடைகள்", "Mobile vending": "நடமாடும் விற்பனை", "Underserved direct-to-home": "சேவை குறைந்த பகுதிகளில் வீடு வீடாக விநியோகம்",
  "Value-added dairy (paneer/curd)": "மதிப்பு கூட்டிய பால் பொருட்கள் (பனீர்/தயிர்)", "No value-added competitor within 3.4km": "3.4 கி.மீ.க்குள் மதிப்பு கூட்டிய போட்டியாளர் இல்லை", "Milk collection + cold chain": "பால் சேகரிப்பு + குளிர் சங்கிலி", "3 co-ops within 6km, demand stable": "6 கி.மீ.க்குள் 3 கூட்டுறவு சங்கங்கள், தேவை நிலையானது", "Feed supply": "தீவன வழங்கல்", "Cattle feed depot 5.9km away": "கால்நடைத் தீவனக் கிடங்கு 5.9 கி.மீ. தொலைவில்", "General retail mix": "பொது சில்லறைக் கலவை", "Consistent demand, repeat customers": "நிலையான தேவை, தொடர் வாடிக்கையாளர்கள்", "Premium opportunity in 10km radius": "10 கி.மீ. பகுதியில் பிரீமியம் வாய்ப்பு", "Diversified risk": "பல்வகை ஆபத்து",
  "per kg · value-added": "கிலோவுக்கு · மதிப்பு கூட்டியது", "Planning estimates — confirm with your SCA officer": "திட்ட மதிப்பீடுகள் — உங்கள் SCA அலுவலரிடம் உறுதிப்படுத்தவும்", "1,240 consumers · rising milk spend": "1,240 நுகர்வோர் · அதிகரிக்கும் பால் செலவு", "7 direct · none value-added": "7 நேரடி · மதிப்பு கூட்டியது இல்லை", "3 dairy co-ops within 6 km": "6 கி.மீ.க்குள் 3 பால் கூட்டுறவு சங்கங்கள்" });

Object.assign(TEMPLATES.bn, { SWOT_LIVE_STRENGTH: "10 কিমিতে {n} প্রতিযোগী চিহ্নিত; চাহিদার ঘনত্ব প্রবেশকে সমর্থন করে", DEMAND_NOTE: "₹{x} লক্ষ/মাস · {n} ভোক্তা", SAME_CATEGORY: "10 কিমির মধ্যে একই শ্রেণির {n} প্রতিযোগী", CROWDING: "{n} প্রতিদ্বন্দ্বীর কারণে ভিড়", PLACES_MAPPED: "10 কিমির মধ্যে {n}টি স্থান চিহ্নিত", PRICING_BAND_NOTE: "পরিসর {lo}–{hi} ({p}% পার্থক্য)", PRICING_STRENGTH: "মূল্য ক্ষমতা {lo}–{hi}; 12–18% প্রিমিয়াম সম্ভব", PURCHASING_POWER: "10 কিমিতে ₹{x} লক্ষ মাসিক চাহিদা", COMP_NOTE_LIVE: "{n}টি দোকান · 8 কিমির মধ্যে OSM-এ যাচাইকৃত", COMP_NOTE_DEMO: "{n}টি দোকান · ডেমো ঘনত্ব", GENERIC_NICHE_DAILY: "{c} — দৈনন্দিন প্রয়োজন", GENERIC_NICHE_VALUE: "{c} — মূল্য সংযোজন" });
Object.assign(TEMPLATES.mr, { SWOT_LIVE_STRENGTH: "10 किमीमध्ये {n} स्पर्धक नोंदले; मागणीची घनता प्रवेशाला अनुकूल", DEMAND_NOTE: "₹{x} लाख/महिना · {n} ग्राहक", SAME_CATEGORY: "10 किमीमध्ये {n} समान श्रेणीतील स्पर्धक", CROWDING: "{n} प्रतिस्पर्ध्यांमुळे गर्दी", PLACES_MAPPED: "10 किमीमध्ये {n} ठिकाणे नोंदली", PRICING_BAND_NOTE: "पट्टा {lo}–{hi} ({p}% फरक)", PRICING_STRENGTH: "किंमत क्षमता {lo}–{hi}; 12–18% प्रीमियम शक्य", PURCHASING_POWER: "10 किमीमध्ये ₹{x} लाख मासिक मागणी", COMP_NOTE_LIVE: "{n} दुकाने · 8 किमीमध्ये OSM द्वारे पडताळलेली", COMP_NOTE_DEMO: "{n} दुकाने · डेमो घनता", GENERIC_NICHE_DAILY: "{c} — रोजच्या गरजा", GENERIC_NICHE_VALUE: "{c} — मूल्यवर्धित" });
Object.assign(TEMPLATES.ta, { SWOT_LIVE_STRENGTH: "10 கி.மீ.யில் {n} போட்டியாளர்கள்; தேவை அடர்த்தி நுழைவுக்கு ஆதரவு", DEMAND_NOTE: "₹{x} லட்சம்/மாதம் · {n} நுகர்வோர்", SAME_CATEGORY: "10 கி.மீ.க்குள் {n} அதே வகை போட்டியாளர்கள்", CROWDING: "{n} போட்டியாளர்களால் நெரிசல்", PLACES_MAPPED: "10 கி.மீ.க்குள் {n} இடங்கள் வரைபடமிடப்பட்டன", PRICING_BAND_NOTE: "வரம்பு {lo}–{hi} ({p}% வேறுபாடு)", PRICING_STRENGTH: "விலை திறன் {lo}–{hi}; 12–18% பிரீமியம் சாத்தியம்", PURCHASING_POWER: "10 கி.மீ.யில் ₹{x} லட்சம் மாதாந்திர தேவை", COMP_NOTE_LIVE: "{n} கடைகள் · 8 கி.மீ.க்குள் OSM மூலம் சரிபார்க்கப்பட்டது", COMP_NOTE_DEMO: "{n} கடைகள் · டெமோ அடர்த்தி", GENERIC_NICHE_DAILY: "{c} — அன்றாட தேவைகள்", GENERIC_NICHE_VALUE: "{c} — மதிப்பு கூட்டியது" });

const TEMPLATE_RES: { key: string; re: RegExp; vars: string[] }[] = [
  { key: "SWOT_LIVE_STRENGTH", re: /^(\d+) competitors mapped in 10km; demand density supports entry$/, vars: ["n"] },
  { key: "DEMAND_NOTE", re: /^₹([\d.,]+)L\/mo · ([\d,]+) consumers$/, vars: ["x", "n"] },
  { key: "SAME_CATEGORY", re: /^(\d+) same-category within 10km$/, vars: ["n"] },
  { key: "CROWDING", re: /^crowding from (\d+) rivals$/, vars: ["n"] },
  { key: "PLACES_MAPPED", re: /^(\d+) places mapped within 10km$/, vars: ["n"] },
  { key: "PRICING_BAND_NOTE", re: /^band (\d+)–(\d+) \(([\d.]+)% spread\)$/, vars: ["lo", "hi", "p"] },
  { key: "PRICING_STRENGTH", re: /^Pricing power (\d+)–(\d+) shows 12–18% premium achievable$/, vars: ["lo", "hi"] },
  { key: "PURCHASING_POWER", re: /^₹([\d.,]+)L monthly demand in 10km$/, vars: ["x"] },
  { key: "COMP_NOTE_LIVE", re: /^(\d+) shops · verified via OSM within 8km$/, vars: ["n"] },
  { key: "COMP_NOTE_DEMO", re: /^(\d+) shops · demo density$/, vars: ["n"] },
  { key: "GENERIC_NICHE_DAILY", re: /^(.+) — daily needs$/, vars: ["c"] },
  { key: "GENERIC_NICHE_VALUE", re: /^(.+) — value added$/, vars: ["c"] },
];

export function tdyn(lang: UiLang, line: string): string {
  if (!line) return line;
  if (lang === "en") return line;
  const exact = DATA[lang]?.[line];
  if (exact) return exact;
  for (const m of TEMPLATE_RES) {
    const r = m.re.exec(line);
    if (!r) continue;
    let out = TEMPLATES[lang]?.[m.key] ?? TEMPLATES.en[m.key] ?? line;
    m.vars.forEach((v, i) => {
      let val = r[i + 1] ?? "";
      if (v === "c") {
        const idx = CATEGORIES.en.indexOf(val);
        if (idx >= 0 && CATEGORIES[lang]?.[idx]) val = CATEGORIES[lang][idx];
      }
      out = out.split(`{${v}}`).join(val);
    });
    return out;
  }
  return line;
}

export function isWarmBanner(b: string): boolean {
  if (!b) return false;
  if (b.includes("unavailable") || b.includes("Locating")) return true;
  return UI_LANG_CODES.some(
    (L) => b === STRINGS[L]["BANNER_DEMO"] || b === STRINGS[L]["BANNER_LOCATING"]
  );
}
