export type UiLang = "en" | "hi" | "te";

export const STRINGS: Record<UiLang, Record<string, string>> = {
  en: {
    APP_EYEBROW: "APPLICANT WORKSPACE",
    APP_TITLE_A: "Turn your village into a ",
    APP_TITLE_B: "bankable decision.",
    APP_SUB:
      "Enter your village, margin and business — GramIntel checks hyper-local signals, matches the right SCA scheme, and builds your financial plan. All in your language.",
    LOGIN_TITLE: "APPLICANT LOGIN",
    LOGIN_SECURE: "Secure · OTP + Google",
    LOGIN_GOOGLE: "Continue with Google",
    LOGIN_OR_OTP: "OR OTP",
    LOGIN_EMAIL: "Email",
    LOGIN_SEND_OTP: "Send OTP",
    LOGIN_SENDING: "Sending…",
    LOGIN_OTP: "OTP code",
    LOGIN_VERIFY: "Verify & continue",
    LOGIN_VERIFYING: "Verifying…",
    LOGIN_BACK: "Back",
    INPUTS_TITLE: "YOUR BUSINESS INPUTS",
    INPUTS_PS_NOTE: "PS: village / block / district + margin + category",
    F_VILLAGE: "Village",
    F_BLOCK: "Block",
    F_DISTRICT: "District",
    F_MARGIN: "Available margin capital (₹)",
    F_MARGIN_HINT: "Project cost = margin / 10% →",
    F_CATEGORY: "Business category",
    LANG_LABEL: "Narrative language",
    BTN_ANALYZE: "Analyze my business → feasibility + financial plan",
    BTN_ANALYZING: "Synthesising hyper-local signals…",
    BTN_LOGIN_FIRST: "Log in to analyze",
    MSG_FILL_LOCATION: "Fill village / block / district",
    MSG_BAD_MARGIN: "Enter valid margin capital",
    MSG_LOGIN_FIRST: "Please log in first (OTP above)",
    EMPTY_STATE:
      "No analysis yet. Fill the inputs above and click Analyze — you’ll get all 6 PS signals + the PS-verbatim scheme router and a quarterly repayment table with moratorium, in EN/हि/ते.",
    R_MARKET: "MARKET REACH · 5–10KM",
    R_OPPORTUNITY: "OPPORTUNITY ANALYSIS",
    R_VALUE: "PRODUCT MARKET VALUE",
    R_WORKING_CAP: "WORKING CAPITAL · ESTIMATE",
    R_SWOT: "SWOT",
    R_NARRATIVES: "NARRATIVE",
    R_CASES: "YOUR CASES",
    APPLY_TITLE: "READY TO APPLY?",
    APPLY_SUB: "Submit this case for officer review",
    APPLY_STATUS: "Status: DRAFT → SUBMITTED → UNDER_REVIEW → APPROVED/REJECTED",
    BTN_SUBMIT: "Submit case #",
    ST_SUBMITTING: "Submitting…",
    ST_SUBMITTED: "✓ Submitted",
    BTN_PRINT: "Print / Save PDF",
    EMI_MONTH: "EMI / MONTH",
    EMI_QUARTER: "EMI / QUARTER",
    QTR_SUFFIX: "/qtr",
    QTR_PER_PS: "×3 · quarterly per PS",
    TOTAL_PAYABLE: "TOTAL PAYABLE",
    INTEREST_WORD: "interest",
    QUARTERLY_SCHEDULE: "QUARTERLY SCHEDULE",
    SCHEDULE_PAUSE: "{n}-mo pause · then {amt}/qtr",
    SCHEME_MORA: "{m}-mo moratorium",
    SCHEME_YEARS: "{y}y",
    PROJECT_WORD: "project",
    LOAN_WORD: "loan",
    TH_QTR: "Qtr",
    TH_MONTHS: "Months",
    TH_EMI: "EMI",
    TH_PRINCIPAL: "Principal",
    TH_INTEREST: "Interest",
    TH_BALANCE: "Balance",
    MORATORIUM: "moratorium",
    EMI_FORMULA: "EMI = P·r·(1+r)ⁿ/((1+r)ⁿ−1) · P {loan} · {rate}%/12 · n {n} ⇒ {emi}/mo · {qtr}/qtr · {mora}mo moratorium",
    WC_MONTHLY_OPEX: "Monthly opex",
    WC_CONTINGENCY: "Contingency (10%)",
    WC_FIRST_YEAR: "First-year outlay",
    WC_3MO: "3-month working capital",
    WC_NOTE_DEFAULT: "Planning estimates",
    BANNER_DEMO: "Live places temporarily unavailable — showing demo density",
    BANNER_LOCATING: "Locating village…",
    CONSUMERS_WORD: "consumers",
    COMPETITORS_WORD: "competitors",
    CHANNELS_LABEL: "Channels:",
    AVG_WORD: "avg",
    BADGE_LIVE: "verified · live OSM",
    BADGE_DEMO: "demo density",
    CASE_WORD: "CASE #",
    PILL_COMP_MAP: "Competitor mapping:",
    PILL_THREATS: "Threats:",
    MEDIAN_WORD: "Median",
    APPLY_DONE: "Submitted — case #{id} is now under review",
    VIABILITY_SCORE: "VIABILITY SCORE",
    CHAT_ADVISOR: "AI CASE ADVISOR",
    CHAT_STATUS_THINKING: "Thinking…",
    CHAT_STATUS_IDLE: "Ask about this case",
    CHAT_INTRO: "I review case #{id}'s feasibility, financial plan and market data to help you understand your own business — how much loan you can get, what competes nearby, and whether you can repay.",
    CHAT_SUGGEST_1: "How much loan can I get for this business?",
    CHAT_SUGGEST_2: "What businesses compete near me?",
    CHAT_SUGGEST_3: "Will I be able to repay comfortably?",
    CHAT_SUGGEST_4: "Summarize the study for me",
    CHAT_SEND: "Send",
    CHAT_PLACEHOLDER: "Ask about case #{id}…",
    CHAT_BTN: "Chat about this case",
    CHAT_OFFLINE: "⚠ AI service unreachable — showing fallback assessment.",
    CHAT_ERR: "Sorry, something went wrong on my end. Please try again.",
    CHAT_NO_RESPONSE: "I couldn't reach the analysis service. Please retry — the case data is loaded and should connect shortly.",
  },
  hi: {
    APP_EYEBROW: "आवेदक कार्यक्षेत्र",
    APP_TITLE_A: "अपने गाँव को ",
    APP_TITLE_B: "बैंक-योग्य निर्णय में बदलें।",
    APP_SUB:
      "अपना गाँव, मार्जिन और व्यवसाय दर्ज करें — GramIntel अति-स्थानीय संकेतों की जाँच करता है, सही SCA योजना से मिलान करता है और आपकी वित्तीय योजना बनाता है। सब कुछ आपकी भाषा में।",
    LOGIN_TITLE: "आवेदक लॉगिन",
    LOGIN_SECURE: "सुरक्षित · OTP + Google",
    LOGIN_GOOGLE: "Google से जारी रखें",
    LOGIN_OR_OTP: "या OTP",
    LOGIN_EMAIL: "ईमेल",
    LOGIN_SEND_OTP: "OTP भेजें",
    LOGIN_SENDING: "भेजा जा रहा है…",
    LOGIN_OTP: "OTP कोड",
    LOGIN_VERIFY: "सत्यापित करें और आगे बढ़ें",
    LOGIN_VERIFYING: "सत्यापन हो रहा है…",
    LOGIN_BACK: "वापस",
    INPUTS_TITLE: "आपके व्यवसाय की जानकारी",
    INPUTS_PS_NOTE: "PS: गाँव / प्रखंड / जिला + मार्जिन + श्रेणी",
    F_VILLAGE: "गाँव",
    F_BLOCK: "प्रखंड",
    F_DISTRICT: "जिला",
    F_MARGIN: "उपलब्ध मार्जिन पूँजी (₹)",
    F_MARGIN_HINT: "परियोजना लागत = मार्जिन / 10% →",
    F_CATEGORY: "व्यवसाय श्रेणी",
    LANG_LABEL: "विवरण की भाषा",
    BTN_ANALYZE: "मेरे व्यवसाय का विश्लेषण करें → व्यवहार्यता + वित्तीय योजना",
    BTN_ANALYZING: "अति-स्थानीय संकेतों का विश्लेषण हो रहा है…",
    BTN_LOGIN_FIRST: "विश्लेषण के लिए लॉगिन करें",
    MSG_FILL_LOCATION: "गाँव / प्रखंड / जिला भरें",
    MSG_BAD_MARGIN: "सही मार्जिन पूँजी दर्ज करें",
    MSG_LOGIN_FIRST: "कृपया पहले लॉगिन करें (ऊपर OTP)",
    EMPTY_STATE:
      "अभी कोई विश्लेषण नहीं है। ऊपर जानकारी भरें और विश्लेषण पर क्लिक करें — आपको सभी 6 PS संकेत + PS-अनुसार योजना चयन और अधिस्थगन सहित त्रैमासिक पुनर्भुगतान तालिका मिलेगी, EN/हिं/ते में।",
    R_MARKET: "बाज़ार पहुँच · 5–10 कि.मी.",
    R_OPPORTUNITY: "अवसर विश्लेषण",
    R_VALUE: "उत्पाद बाज़ार मूल्य",
    R_WORKING_CAP: "कार्यशील पूँजी · अनुमान",
    R_SWOT: "SWOT",
    R_NARRATIVES: "विवरण",
    R_CASES: "आपके केस",
    APPLY_TITLE: "आवेदन के लिए तैयार?",
    APPLY_SUB: "अधिकारी समीक्षा हेतु यह केस जमा करें",
    APPLY_STATUS: "स्थिति: DRAFT → SUBMITTED → UNDER_REVIEW → APPROVED/REJECTED",
    BTN_SUBMIT: "केस जमा करें #",
    ST_SUBMITTING: "जमा किया जा रहा है…",
    ST_SUBMITTED: "✓ जमा किया गया",
    BTN_PRINT: "प्रिंट / PDF सहेजें",
    EMI_MONTH: "EMI / माह",
    EMI_QUARTER: "EMI / तिमाही",
    QTR_SUFFIX: "/तिमाही",
    QTR_PER_PS: "×3 · PS अनुसार त्रैमासिक",
    TOTAL_PAYABLE: "कुल देय राशि",
    INTEREST_WORD: "ब्याज",
    QUARTERLY_SCHEDULE: "त्रैमासिक अनुसूची",
    SCHEDULE_PAUSE: "{n}-माह विराम · फिर {amt}/तिमाही",
    SCHEME_MORA: "{m}-माह अधिस्थगन",
    SCHEME_YEARS: "{y} वर्ष",
    PROJECT_WORD: "परियोजना",
    LOAN_WORD: "ऋण",
    TH_QTR: "तिमाही",
    TH_MONTHS: "माह",
    TH_EMI: "EMI",
    TH_PRINCIPAL: "मूलधन",
    TH_INTEREST: "ब्याज",
    TH_BALANCE: "शेष",
    MORATORIUM: "अधिस्थगन",
    EMI_FORMULA: "EMI = P·r·(1+r)ⁿ/((1+r)ⁿ−1) · P {loan} · {rate}%/12 · n {n} ⇒ {emi}/माह · {qtr}/तिमाही · {mora}माह अधिस्थगन",
    WC_MONTHLY_OPEX: "मासिक संचालन व्यय",
    WC_CONTINGENCY: "आकस्मिकता (10%)",
    WC_FIRST_YEAR: "प्रथम-वर्ष परिव्यय",
    WC_3MO: "3-माह कार्यशील पूँजी",
    WC_NOTE_DEFAULT: "योजना अनुमान",
    BANNER_DEMO: "लाइव स्थान अस्थायी रूप से अनुपलब्ध — डेमो घनत्व दिखाया जा रहा है",
    BANNER_LOCATING: "गाँव की स्थिति ज्ञात की जा रही है…",
    CONSUMERS_WORD: "उपभोक्ता",
    COMPETITORS_WORD: "प्रतिस्पर्धी",
    CHANNELS_LABEL: "चैनल:",
    AVG_WORD: "औसत",
    BADGE_LIVE: "सत्यापित · लाइव OSM",
    BADGE_DEMO: "डेमो घनत्व",
    CASE_WORD: "केस #",
    PILL_COMP_MAP: "प्रतिस्पर्धी मानचित्रण:",
    PILL_THREATS: "खतरे:",
    MEDIAN_WORD: "माध्यिका",
    APPLY_DONE: "जमा किया गया — केस #{id} अब समीक्षा में है",
    VIABILITY_SCORE: "व्यवहार्यता स्कोर",
    CHAT_ADVISOR: "AI केस सलाहकार",
    CHAT_STATUS_THINKING: "सोच रहा है…",
    CHAT_STATUS_IDLE: "इस केस के बारे में पूछें",
    CHAT_INTRO: "मैं केस #{id} की व्यवहार्यता, वित्तीय योजना और बाज़ार आँकड़ों की समीक्षा करता हूँ ताकि आप अपने व्यवसाय को समझ सकें — आपको कितना ऋण मिलेगा, आसपास क्या प्रतिस्पर्धा है, और क्या आप आराम से चुका सकते हैं।",
    CHAT_SUGGEST_1: "इस व्यवसाय के लिए मुझे कितना ऋण मिलेगा?",
    CHAT_SUGGEST_2: "मेरे पास कौन से व्यवसाय प्रतिस्पर्धा में हैं?",
    CHAT_SUGGEST_3: "क्या मैं आराम से चुका पाऊँगा?",
    CHAT_SUGGEST_4: "अध्ययन का सारांश दें",
    CHAT_SEND: "भेजें",
    CHAT_PLACEHOLDER: "केस #{id} के बारे में पूछें…",
    CHAT_BTN: "इस केस पर चैट करें",
    CHAT_OFFLINE: "⚠ AI सेवा अनुपलब्ध — फ़ॉलबैक आकलन दिखाया जा रहा है।",
    CHAT_ERR: "क्षमा करें, मेरी ओर से कुछ गड़बड़ हो गई। कृपया पुनः प्रयास करें।",
    CHAT_NO_RESPONSE: "मैं विश्लेषण सेवा तक नहीं पहुँच सका। कृपया पुनः प्रयास करें — केस डेटा लोड है और जल्द ही जुड़ जाना चाहिए।",
  },
  te: {
    APP_EYEBROW: "దరఖాస్తుదారు కార్యస్థలం",
    APP_TITLE_A: "మీ గ్రామాన్ని ",
    APP_TITLE_B: "బ్యాంకు-యోగ్య నిర్ణయంగా మార్చండి.",
    APP_SUB:
      "మీ గ్రామం, మార్జిన్ మరియు వ్యాపారాన్ని నమోదు చేయండి — GramIntel అతి-స్థానిక సంకేతాలను పరిశీలిస్తుంది, సరైన SCA పథకంతో జత చేస్తుంది మరియు మీ ఆర్థిక ప్రణాళికను రూపొందిస్తుంది. అన్నీ మీ భాషలో.",
    LOGIN_TITLE: "దరఖాస్తుదారు లాగిన్",
    LOGIN_SECURE: "సురక్షితం · OTP + Google",
    LOGIN_GOOGLE: "Googleతో కొనసాగండి",
    LOGIN_OR_OTP: "లేదా OTP",
    LOGIN_EMAIL: "ఈమెయిల్",
    LOGIN_SEND_OTP: "OTP పంపండి",
    LOGIN_SENDING: "పంపుతోంది…",
    LOGIN_OTP: "OTP కోడ్",
    LOGIN_VERIFY: "ధృవీకరించి కొనసాగండి",
    LOGIN_VERIFYING: "ధృవీకరిస్తోంది…",
    LOGIN_BACK: "వెనుకకు",
    INPUTS_TITLE: "మీ వ్యాపార వివరాలు",
    INPUTS_PS_NOTE: "PS: గ్రామం / బ్లాక్ / జిల్లా + మార్జిన్ + వర్గం",
    F_VILLAGE: "గ్రామం",
    F_BLOCK: "బ్లాక్",
    F_DISTRICT: "జిల్లా",
    F_MARGIN: "అందుబాటులోని మార్జిన్ మూలధనం (₹)",
    F_MARGIN_HINT: "ప్రాజెక్ట్ వ్యయం = మార్జిన్ / 10% →",
    F_CATEGORY: "వ్యాపార వర్గం",
    LANG_LABEL: "కథన భాష",
    BTN_ANALYZE: "నా వ్యాపారాన్ని విశ్లేషించండి → సాధ్యత + ఆర్థిక ప్రణాళిక",
    BTN_ANALYZING: "అతి-స్థానిక సంకేతాలను విశ్లేషిస్తోంది…",
    BTN_LOGIN_FIRST: "విశ్లేషణ కోసం లాగిన్ చేయండి",
    MSG_FILL_LOCATION: "గ్రామం / బ్లాక్ / జిల్లా నమోదు చేయండి",
    MSG_BAD_MARGIN: "సరైన మార్జిన్ మూలధనాన్ని నమోదు చేయండి",
    MSG_LOGIN_FIRST: "దయచేసి ముందుగా లాగిన్ చేయండి (పైన OTP)",
    EMPTY_STATE:
      "ఇంకా విశ్లేషణ లేదు. పైన వివరాలు నింపి విశ్లేషణపై క్లిక్ చేయండి — మీకు అన్ని 6 PS సంకేతాలు + PS ప్రకారం పథక ఎంపిక మరియు మారటోరియంతో త్రైమాసిక తిరిగి చెల్లింపు పట్టిక లభిస్తుంది, EN/హి/తెలో.",
    R_MARKET: "మార్కెట్ పరిధి · 5–10 కి.మీ.",
    R_OPPORTUNITY: "అవకాశాల విశ్లేషణ",
    R_VALUE: "ఉత్పత్తి మార్కెట్ విలువ",
    R_WORKING_CAP: "నిర్వహణ మూలధనం · అంచనా",
    R_SWOT: "SWOT",
    R_NARRATIVES: "కథనం",
    R_CASES: "మీ కేసులు",
    APPLY_TITLE: "దరఖాస్తుకు సిద్ధంగా ఉన్నారా?",
    APPLY_SUB: "అధికారి సమీక్ష కోసం ఈ కేసును సమర్పించండి",
    APPLY_STATUS: "స్థితి: DRAFT → SUBMITTED → UNDER_REVIEW → APPROVED/REJECTED",
    BTN_SUBMIT: "కేసు సమర్పించండి #",
    ST_SUBMITTING: "సమర్పిస్తోంది…",
    ST_SUBMITTED: "✓ సమర్పించబడింది",
    BTN_PRINT: "ప్రింట్ / PDF సేవ్ చేయండి",
    EMI_MONTH: "EMI / నెల",
    EMI_QUARTER: "EMI / త్రైమాసికం",
    QTR_SUFFIX: "/త్రైమాసికం",
    QTR_PER_PS: "×3 · PS ప్రకారం త్రైమాసికం",
    TOTAL_PAYABLE: "మొత్తం చెల్లించవలసిన మొత్తం",
    INTEREST_WORD: "వడ్డీ",
    QUARTERLY_SCHEDULE: "త్రైమాసిక షెడ్యూల్",
    SCHEDULE_PAUSE: "{n}-నెలల విరామం · తర్వాత {amt}/త్రైమాసికం",
    SCHEME_MORA: "{m}-నెలల మారటోరియం",
    SCHEME_YEARS: "{y} సం.",
    PROJECT_WORD: "ప్రాజెక్ట్",
    LOAN_WORD: "రుణం",
    TH_QTR: "త్రైమా.",
    TH_MONTHS: "నెలలు",
    TH_EMI: "EMI",
    TH_PRINCIPAL: "అసలు",
    TH_INTEREST: "వడ్డీ",
    TH_BALANCE: "మిగులు",
    MORATORIUM: "మారటోరియం",
    EMI_FORMULA: "EMI = P·r·(1+r)ⁿ/((1+r)ⁿ−1) · P {loan} · {rate}%/12 · n {n} ⇒ {emi}/నెల · {qtr}/త్రైమాసికం · {mora}నెలల మారటోరియం",
    WC_MONTHLY_OPEX: "నెలవారీ నిర్వహణ వ్యయం",
    WC_CONTINGENCY: "అనుకోని ఖర్చులు (10%)",
    WC_FIRST_YEAR: "మొదటి సంవత్సర వ్యయం",
    WC_3MO: "3-నెలల నిర్వహణ మూలధనం",
    WC_NOTE_DEFAULT: "ప్రణాళిక అంచనాలు",
    BANNER_DEMO: "లైవ్ ప్రదేశాలు తాత్కాలికంగా అందుబాటులో లేవు — డెమో సాంద్రత చూపుతోంది",
    BANNER_LOCATING: "గ్రామాన్ని గుర్తిస్తోంది…",
    CONSUMERS_WORD: "వినియోగదారులు",
    COMPETITORS_WORD: "పోటీదారులు",
    CHANNELS_LABEL: "మార్గాలు:",
    AVG_WORD: "సగటు",
    BADGE_LIVE: "ధృవీకరించబడింది · లైవ్ OSM",
    BADGE_DEMO: "డెమో సాంద్రత",
    CASE_WORD: "కేసు #",
    PILL_COMP_MAP: "పోటీదారుల మ్యాపింగ్:",
    PILL_THREATS: "ముప్పులు:",
    MEDIAN_WORD: "మధ్యగత",
    APPLY_DONE: "సమర్పించబడింది — కేసు #{id} ఇప్పుడు సమీక్షలో ఉంది",
    VIABILITY_SCORE: "సాధ్యత స్కోరు",
    CHAT_ADVISOR: "AI కేసు సలహాదారు",
    CHAT_STATUS_THINKING: "ఆలోచిస్తోంది…",
    CHAT_STATUS_IDLE: "ఈ కేసు గురించి అడగండి",
    CHAT_INTRO: "మీ స్వంత వ్యాపారాన్ని అర్థం చేసుకోవడానికి నేను కేసు #{id} యొక్క సాధ్యత, ఆర్థిక ప్రణాళిక మరియు మార్కెట్ డేటాను సమీక్షిస్తాను — మీకు ఎంత రుణం లభిస్తుంది, సమీపంలో ఏ పోటీ ఉంది, మరియు మీరు సౌకర్యంగా తిరిగి చెల్లించగలరా.",
    CHAT_SUGGEST_1: "ఈ వ్యాపారానికి నాకు ఎంత రుణం లభిస్తుంది?",
    CHAT_SUGGEST_2: "నా దగ్గర పోటీలో ఏ వ్యాపారాలు ఉన్నాయి?",
    CHAT_SUGGEST_3: "నేను సౌకర్యంగా తిరిగి చెల్లించగలనా?",
    CHAT_SUGGEST_4: "అధ్యయనాన్ని సంగ్రహించండి",
    CHAT_SEND: "పంపండి",
    CHAT_PLACEHOLDER: "కేసు #{id} గురించి అడగండి…",
    CHAT_BTN: "ఈ కేసుపై చాట్ చేయండి",
    CHAT_OFFLINE: "⚠ AI సేవ అందుబాటులో లేదు — ఫాల్‌బ్యాక్ అంచనా చూపుతోంది.",
    CHAT_ERR: "క్షమించండి, నా వైపు ఏదో తప్పు జరిగింది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    CHAT_NO_RESPONSE: "విశ్లేషణ సేవను చేరుకోలేకపోయాను. దయచేసి మళ్లీ ప్రయత్నించండి — కేసు డేటా లోడ్ అయింది, త్వరలో కనెక్ట్ అవుతుంది.",
  },
};

export function t(lang: UiLang, key: string): string {
  return STRINGS[lang]?.[key] ?? STRINGS.en[key] ?? key;
}

export const CATEGORIES: Record<UiLang, string[]> = {
  en: ["Dairy", "Retail", "Textile", "Food Processing", "Poultry", "Kirana", "Services", "Food"],
  hi: ["डेयरी", "खुदरा", "वस्त्र", "खाद्य प्रसंस्करण", "मुर्गी पालन", "किराना", "सेवाएँ", "खाद्य"],
  te: ["డెయిరీ", "రిటైల్", "వస్త్రాలు", "ఆహార ప్రాసెసింగ్", "కోళ్ల పెంపకం", "కిరాణా", "సేవలు", "ఆహారం"],
};

export const DATA: Record<UiLang, Record<string, string>> = {
  en: {},
  hi: {
    "MARKET DEMAND": "बाज़ार मांग",
    "COMPETITION": "प्रतिस्पर्धा",
    "PRICING POWER": "मूल्य निर्धारण क्षमता",
    "SUPPLY ACCESS": "आपूर्ति पहुँच",
    "FINANCIAL FIT": "वित्तीय उपयुक्तता",
    "RISK EXPOSURE": "जोखिम स्तर",
    "rising milk spend in radius": "क्षेत्र में दूध पर व्यय बढ़ रहा है",
    "none value-added nearby": "आसपास कोई मूल्यवर्धित प्रतिस्पर्धी नहीं",
    "12–18% premium achievable": "12–18% प्रीमियम संभव",
    "3 co-ops within 6 km": "6 किमी के भीतर 3 सहकारी समितियाँ",
    "matches term-loan structure": "सावधि-ऋण संरचना के अनुरूप",
    "matches micro-loan structure": "सूक्ष्म-ऋण संरचना के अनुरूप",
    "seasonal dips · power supply": "मौसमी उतार-चढ़ाव · बिजली आपूर्ति",
    "Rising milk spend in 10km radius": "10 किमी क्षेत्र में दूध पर व्यय बढ़ रहा है",
    "3 co-ops within 6km — supply access reliable": "6 किमी के भीतर 3 सहकारी समितियाँ — आपूर्ति विश्वसनीय",
    "First-time entrepreneur risk; working capital discipline needed": "पहली बार उद्यम करने का जोखिम; कार्यशील पूँजी में अनुशासन आवश्यक",
    "Limited cold storage at village edge": "गाँव के छोर पर सीमित शीत भंडारण",
    "Seasonal dips (summer milk yield)": "मौसमी गिरावट (गर्मी में दूध उत्पादन में कमी)",
    "Single-buyer dependency if tied to one co-op": "एक सहकारी समिति से जुड़ने पर एकल-क्रेता निर्भरता",
    "Power supply intermittency": "बिजली आपूर्ति में रुकावट",
    "Kirana cluster": "किराना समूह",
    "Weekly haat": "साप्ताहिक हाट",
    "Co-op collection": "सहकारी संग्रह",
    "Roadside stalls": "सड़क किनारे ठेले",
    "Mobile vending": "चलती-फिरती बिक्री",
    "Underserved direct-to-home": "वंचित क्षेत्रों में घर-घर आपूर्ति",
    "Value-added dairy (paneer/curd)": "मूल्यवर्धित डेयरी (पनीर/दही)",
    "No value-added competitor within 3.4km": "3.4 किमी के भीतर कोई मूल्यवर्धित प्रतिस्पर्धी नहीं",
    "Milk collection + cold chain": "दूध संग्रह + शीत श्रृंखला",
    "3 co-ops within 6km, demand stable": "6 किमी के भीतर 3 सहकारी समितियाँ, मांग स्थिर",
    "Feed supply": "पशु आहार आपूर्ति",
    "Cattle feed depot 5.9km away": "पशु आहार डिपो 5.9 किमी दूर",
    "General retail mix": "सामान्य खुदरा मिश्रण",
    "Consistent demand, repeat customers": "स्थिर मांग, नियमित ग्राहक",
    "Premium opportunity in 10km radius": "10 किमी क्षेत्र में प्रीमियम अवसर",
    "Diversified risk": "विविधीकृत जोखिम",
    "per kg · value-added": "प्रति किग्रा · मूल्यवर्धित",
    "Planning estimates — confirm with your SCA officer": "योजना अनुमान — अपने SCA अधिकारी से पुष्टि करें",
    "1,240 consumers · rising milk spend": "1,240 उपभोक्ता · दूध पर बढ़ता खर्च",
    "7 direct · none value-added": "7 प्रत्यक्ष · कोई मूल्यवर्धित नहीं",
    "3 dairy co-ops within 6 km": "6 किमी के भीतर 3 डेयरी सहकारी समितियाँ",
    "GOOD POTENTIAL": "अच्छी संभावना",
    "MODERATE": "मध्यम",
    "LOW": "कम",
  },
  te: {
    "MARKET DEMAND": "మార్కెట్ డిమాండ్",
    "COMPETITION": "పోటీ",
    "PRICING POWER": "ధర నిర్ణయ శక్తి",
    "SUPPLY ACCESS": "సరఫరా లభ్యత",
    "FINANCIAL FIT": "ఆర్థిక అనుకూలత",
    "RISK EXPOSURE": "రిస్క్ స్థాయి",
    "rising milk spend in radius": "ప్రాంతంలో పాల వ్యయం పెరుగుతోంది",
    "none value-added nearby": "సమీపంలో విలువ ఆధారిత పోటీదారు లేరు",
    "12–18% premium achievable": "12–18% ప్రీమియం సాధ్యం",
    "3 co-ops within 6 km": "6 కి.మీ. పరిధిలో 3 సహకార సంఘాలు",
    "matches term-loan structure": "టర్మ్-లోన్ నిర్మాణానికి అనుగుణం",
    "matches micro-loan structure": "మైక్రో-లోన్ నిర్మాణానికి అనుగుణం",
    "seasonal dips · power supply": "కాలానుగుణ హెచ్చుతగ్గులు · విద్యుత్ సరఫరా",
    "Rising milk spend in 10km radius": "10 కి.మీ. పరిధిలో పాల వ్యయం పెరుగుతోంది",
    "3 co-ops within 6km — supply access reliable": "6 కి.మీ. పరిధిలో 3 సహకార సంఘాలు — సరఫరా నమ్మకమైనది",
    "First-time entrepreneur risk; working capital discipline needed": "తొలిసారి వ్యవస్థాపక రిస్క్; నిర్వహణ మూలధన క్రమశిక్షణ అవసరం",
    "Limited cold storage at village edge": "గ్రామ శివార్లలో పరిమిత శీతల నిల్వ",
    "Seasonal dips (summer milk yield)": "కాలానుగుణ తగ్గుదల (వేసవిలో పాల దిగుబడి తగ్గుతుంది)",
    "Single-buyer dependency if tied to one co-op": "ఒక సహకార సంఘంతో ముడిపడితే ఏక-కొనుగోలుదారు ఆధారపడటం",
    "Power supply intermittency": "విద్యుత్ సరఫరాలో అంతరాయం",
    "Kirana cluster": "కిరాణా సమూహం",
    "Weekly haat": "వారపు సంత",
    "Co-op collection": "సహకార సేకరణ",
    "Roadside stalls": "రోడ్డు పక్క దుకాణాలు",
    "Mobile vending": "సంచార విక్రయం",
    "Underserved direct-to-home": "సేవలందని ప్రాంతాల్లో ఇంటింటి సరఫరా",
    "Value-added dairy (paneer/curd)": "విలువ ఆధారిత డెయిరీ (పనీర్/పెరుగు)",
    "No value-added competitor within 3.4km": "3.4 కి.మీ. పరిధిలో విలువ ఆధారిత పోటీదారు లేరు",
    "Milk collection + cold chain": "పాల సేకరణ + శీతల గొలుసు",
    "3 co-ops within 6km, demand stable": "6 కి.మీ. పరిధిలో 3 సహకార సంఘాలు, డిమాండ్ స్థిరం",
    "Feed supply": "పశుగ్రాస సరఫరా",
    "Cattle feed depot 5.9km away": "పశుగ్రాస డిపో 5.9 కి.మీ. దూరంలో",
    "General retail mix": "సాధారణ రిటైల్ మిశ్రమం",
    "Consistent demand, repeat customers": "స్థిరమైన డిమాండ్, పునరావృత వినియోగదారులు",
    "Premium opportunity in 10km radius": "10 కి.మీ. పరిధిలో ప్రీమియం అవకాశం",
    "Diversified risk": "వైవిధ్యభరిత రిస్క్",
    "per kg · value-added": "కిలోకు · విలువ ఆధారిత",
    "Planning estimates — confirm with your SCA officer": "ప్రణాళిక అంచనాలు — మీ SCA అధికారితో నిర్ధారించండి",
    "1,240 consumers · rising milk spend": "1,240 వినియోగదారులు · పాలపై పెరుగుతున్న ఖర్చు",
    "7 direct · none value-added": "7 ప్రత్యక్ష పోటీ · విలువ ఆధారితవి లేవు",
    "3 dairy co-ops within 6 km": "6 కి.మీ.లో 3 పాడి సహకార సంఘాలు",
    "GOOD POTENTIAL": "మంచి అవకాశం",
    "MODERATE": "మధ్యస్థం",
    "LOW": "తక్కువ",
  },
};

export const TEMPLATES: Record<UiLang, Record<string, string>> = {
  en: {
    SWOT_LIVE_STRENGTH: "{n} competitors mapped in 10km; demand density supports entry",
    DEMAND_NOTE: "₹{x}L/mo · {n} consumers",
    SAME_CATEGORY: "{n} same-category within 10km",
    CROWDING: "crowding from {n} rivals",
    PLACES_MAPPED: "{n} places mapped within 10km",
    PRICING_BAND_NOTE: "band {lo}–{hi} ({p}% spread)",
    PRICING_STRENGTH: "Pricing power {lo}–{hi} shows 12–18% premium achievable",
    PURCHASING_POWER: "₹{x}L monthly demand in 10km",
    COMP_NOTE_LIVE: "{n} shops · verified via OSM within 8km",
    COMP_NOTE_DEMO: "{n} shops · demo density",
    GENERIC_NICHE_DAILY: "{c} — daily needs",
    GENERIC_NICHE_VALUE: "{c} — value added",
  },
  hi: {
    SWOT_LIVE_STRENGTH: "{n} प्रतिस्पर्धी 10 किमी में दर्ज; मांग घनत्व प्रवेश का समर्थन करता है",
    DEMAND_NOTE: "₹{x} लाख/माह · {n} उपभोक्ता",
    SAME_CATEGORY: "10 किमी के भीतर {n} समान-श्रेणी प्रतिस्पर्धी",
    CROWDING: "{n} प्रतिद्वंद्वियों से भीड़",
    PLACES_MAPPED: "10 किमी के भीतर {n} स्थान दर्ज",
    PRICING_BAND_NOTE: "बैंड {lo}–{hi} ({p}% अंतर)",
    PRICING_STRENGTH: "मूल्य निर्धारण क्षमता {lo}–{hi}, 12–18% प्रीमियम संभव दर्शाती है",
    PURCHASING_POWER: "10 किमी में ₹{x} लाख मासिक मांग",
    COMP_NOTE_LIVE: "{n} दुकानें · OSM द्वारा 8 किमी के भीतर सत्यापित",
    COMP_NOTE_DEMO: "{n} दुकानें · डेमो घनत्व",
    GENERIC_NICHE_DAILY: "{c} — दैनिक आवश्यकताएँ",
    GENERIC_NICHE_VALUE: "{c} — मूल्यवर्धित",
  },
  te: {
    SWOT_LIVE_STRENGTH: "{n} పోటీదారులు 10 కి.మీ.లో నమోదయ్యారు; డిమాండ్ సాంద్రత ప్రవేశానికి అనుకూలం",
    DEMAND_NOTE: "₹{x} లక్షలు/నెల · {n} వినియోగదారులు",
    SAME_CATEGORY: "10 కి.మీ. పరిధిలో {n} ఒకే-వర్గం పోటీదారులు",
    CROWDING: "{n} ప్రత్యర్థుల వల్ల రద్దీ",
    PLACES_MAPPED: "10 కి.మీ. పరిధిలో {n} ప్రదేశాలు నమోదయ్యాయి",
    PRICING_BAND_NOTE: "బ్యాండ్ {lo}–{hi} ({p}% వ్యత్యాసం)",
    PRICING_STRENGTH: "ధర నిర్ణయ శక్తి {lo}–{hi}, 12–18% ప్రీమియం సాధ్యమని చూపుతోంది",
    PURCHASING_POWER: "10 కి.మీ.లో ₹{x} లక్షల నెలవారీ డిమాండ్",
    COMP_NOTE_LIVE: "{n} దుకాణాలు · 8 కి.మీ. పరిధిలో OSM ద్వారా ధృవీకరించబడింది",
    COMP_NOTE_DEMO: "{n} దుకాణాలు · డెమో సాంద్రత",
    GENERIC_NICHE_DAILY: "{c} — రోజువారీ అవసరాలు",
    GENERIC_NICHE_VALUE: "{c} — విలువ ఆధారిత",
  },
};

const TEMPLATE_RES: { key: string; re: RegExp; vars: string[] }[] = [
  { key: "SWOT_LIVE_STRENGTH", re: /^(\d+) competitors mapped in 10km; demand density supports entry$/, vars: ["n"] },
  { key: "DEMAND_NOTE", re: /^₹([\d.,]+)L\/mo · ([\d,]+) consumers$/, vars: ["x", "n"] },
  { key: "SAME_CATEGORY", re: /^(\d+) same-category within 10km$/, vars: ["n"] },
  { key: "CROWDING", re: /^crowding from (\d+) rivals$/, vars: ["n"] },
  { key: "PLACES_MAPPED", re: /^(\d+) places mapped within 10km$/, vars: ["n"] },
  { key: "PRICING_BAND_NOTE", re: /^band (\d+)–(\d+) \(([\d.]+)% spread\)$/, vars: ["lo", "hi", "p"] },
  { key: "PRICING_STRENGTH", re: /^Pricing power (\d+)–(\d+) shows 12–18% premium achievable$/, vars: ["lo", "hi"] },
  { key: "PURCHASING_POWER", re: /^₹([\d.,]+)L monthly demand in 10km$/, vars: ["x"] },
  { key: "COMP_NOTE_LIVE", re: /^(\d+) shops · verified via OSM within 8km$/, vars: ["n"] },
  { key: "COMP_NOTE_DEMO", re: /^(\d+) shops · demo density$/, vars: ["n"] },
  { key: "GENERIC_NICHE_DAILY", re: /^(.+) — daily needs$/, vars: ["c"] },
  { key: "GENERIC_NICHE_VALUE", re: /^(.+) — value added$/, vars: ["c"] },
];

export function tdyn(lang: UiLang, line: string): string {
  if (!line) return line;
  if (lang === "en") return line;
  const exact = DATA[lang]?.[line];
  if (exact) return exact;
  for (const m of TEMPLATE_RES) {
    const r = m.re.exec(line);
    if (!r) continue;
    let out = TEMPLATES[lang]?.[m.key] ?? TEMPLATES.en[m.key] ?? line;
    m.vars.forEach((v, i) => {
      let val = r[i + 1] ?? "";
      if (v === "c") {
        const idx = CATEGORIES.en.indexOf(val);
        if (idx >= 0 && CATEGORIES[lang]?.[idx]) val = CATEGORIES[lang][idx];
      }
      out = out.split(`{${v}}`).join(val);
    });
    return out;
  }
  return line;
}

export function isWarmBanner(b: string): boolean {
  if (!b) return false;
  if (b.includes("unavailable") || b.includes("Locating")) return true;
  return (["en", "hi", "te"] as const).some(
    (L) => b === STRINGS[L]["BANNER_DEMO"] || b === STRINGS[L]["BANNER_LOCATING"]
  );
}
