import type { UiLang } from "./assistant-strings";

type UiDictionary = Record<string, string>;

export const UI_STRINGS: Record<UiLang, UiDictionary> = {
  en: {
    LANGUAGE: "Language",
    ENGLISH: "English",
    HINDI: "Hindi",
    TELUGU: "Telugu",
    SKIP_TO_CONTENT: "Skip to content",
    RELOAD: "Reload",
    SECTION_UNAVAILABLE: "Section temporarily unavailable — story continues",
    MAP: "Map",
    ASSISTANT: "Assistant",
    PORTAL: "Portal",
    LOGOUT: "Logout",
    OFFICER_PORTAL: "Officer portal",
    APPLICANT_WORKSPACE: "Applicant workspace",
    HOME: "Home",
    PRIMARY_NAV: "Primary navigation",
    MOBILE_NAV: "Mobile navigation",
    MAP_EXPLORER: "Map explorer",
    LOADING_MAP: "Loading map · preparing explorer",
    OFFLINE_MAP: "You are offline — showing cached map data.",
    LIVE_DATA_UNAVAILABLE: "Live business data temporarily unavailable — showing cached/demo local data.",
    RETRY_LIVE_DATA: "Retry live data",
    MAP_RADIUS: "Map exploration radius",
    MAP_RADIUS_NOTE: "Exploration only — the feasibility report always uses 10 km.",
    SEARCH_MODE: "Search mode",
    LOCATION: "Location",
    F_VILLAGE: "Village",
    R_MARKET: "MARKET REACH · 5–10 KM",
    CAPITAL: "Capital",
    BUSINESS_IDEA: "Business idea",
    COMPETITION: "Competition",
    RISK: "Risk",
    DATA_SATELLITE: "SATELLITE + OPEN GOV DATA",
    DATA_PRICE: "LOCAL PRICE FEEDS",
    DATA_SCHEME: "SCHEME ELIGIBILITY RULES",
    DATA_RISK: "RISK HEURISTICS",
    BUSINESS: "Business",
    SEARCH_VILLAGE: "Search village or town",
    TYPE_VILLAGE: "Type a village or town in India",
    SEARCH_BUSINESSES: "Search businesses in view",
    SEARCH_BY_NAME: "Search by name or category",
    SEARCHING: "Searching…",
    MATCHING_PLACES: "Matching places",
    MATCHING_BUSINESSES: "Matching businesses",
    NO_PLACES: "No places found — try a nearby town",
    NEARBY_BUSINESSES: "Nearby businesses",
    ALL: "All",
    LOADING: "Loading",
    NO_BUSINESSES: "No businesses in this view yet — try widening the radius or searching a nearby town.",
    BUSINESSES: "Businesses",
    AREA_SIGNALS: "Area signals",
    BUSINESSES_MAPPED: "Businesses mapped",
    DOMINANT_CATEGORY: "Dominant category",
    AVG_DISTANCE: "Avg distance",
    CATEGORIES_DETECTED: "Categories detected",
    DENSITY_BAND: "Density band",
    NO_DATA: "No data",
    LIVE_OSM_RESULTS: "Live OpenStreetMap results for this search area",
    CACHED_DEMO_DATA: "Cached or demo local data — live lookup unavailable",
    MAP_SIGNALS_NOTE: "Map exploration signals — not a feasibility report",
    OPPORTUNITY_CHECK: "Opportunity check",
    BUSINESS_CATEGORY: "Business category",
    NEARBY_COMPETITORS: "Nearby competitors",
    CLOSEST: "Closest",
    DENSITY: "Density",
    SIGNAL: "Signal",
    DISTANCE: "Distance",
    CLOSE_DETAILS: "Close details",
    DETAILS_FOR: "Details for {name}",
    VIEW_ON_MAP: "View on Map",
    VIEW_ON_OSM: "View on OpenStreetMap",
    GRAMINTEL_FUNDED: "GramIntel-funded business — loan approved by an officer",
    DEMO_LISTING: "Demo listing — representative local business, not live data",
    OSM_DETAILS: "More details: not available from OpenStreetMap",
    AREA_RESULTS: "Area results",
    CLOSE_RESULTS: "Close results",
    FILTER_CATEGORY: "Filter by category",
    CASES: "Cases",
    AI_CASE_ADVISOR: "AI Case Advisor",
    LANDING_PAGE: "Landing page",
    OFFICER_LOGIN: "Officer login",
    REVIEW_DECIDE: "Review & decide with confidence.",
    OR_OTP: "OR OTP",
    ADMIN_EMAIL: "Admin email",
    SIX_DIGIT_CODE: "6-digit code",
    SEND_OTP: "Send OTP",
    SENDING: "Sending…",
    VERIFY: "Verify",
    VERIFYING: "Verifying…",
    BACK: "Back",
    GOOGLE_CONTINUE: "Continue with Google",
    ADMIN_GOOGLE_HELP: "Sign in with the admin Google account to access the officer portal. The code is emailed to that address.",
    QUEUE: "Queue",
    SHOWN: "shown",
    ALL_STATUSES: "All statuses",
    REFRESH: "Refresh",
    NO_CASES_FILTER: "No cases for this filter. Applicants submit from /assistant — then they appear here.",
    SELECT_CASE: "Select a case from the queue to see full feasibility + financials + narrative and take a decision.",
    CLOSE: "Close",
    MARKET_REACH: "Market reach",
    VIABILITY: "Viability",
    NARRATIVES: "Narratives",
    STATUS_HISTORY: "Status history",
    DECISION: "Decision",
    DECISION_NOTE: "Mandatory note — why approve/reject (shown in timeline)",
    APPROVE: "Approve",
    REJECT: "Reject",
    TRANSITIONS: "Transitions: DRAFT→SUBMITTED→UNDER_REVIEW→APPROVED|REJECTED. Backend auto-moves SUBMITTED→UNDER_REVIEW on first decision.",
    CASE_TOTAL: "{n} total",
    STATUS_DRAFT: "Draft",
    STATUS_SUBMITTED: "Submitted",
    STATUS_UNDER_REVIEW: "Under review",
    STATUS_APPROVED: "Approved",
    STATUS_REJECTED: "Rejected",
    LANDING_ANALYZE: "Analyze my business",
    LANDING_METHOD: "Method",
    LANDING_MARKET: "Market",
    LANDING_VIABILITY: "Viability",
    LANDING_FINANCE: "Finance",
    LANDING_SCHEMES: "Schemes",
    LANDING_LANGUAGE: "Language",
    LANDING_HOW: "See how it thinks",
    LANDING_MAP: "Explore the live business map",
    HOW_THINKS: "03 — HOW GRAMINTEL THINKS",
    TIP_ZOOM: "TIP: HOLD Ctrl + SCROLL TO ZOOM · DRAG TO PAN",
    YOUR_MARGIN: "YOUR MARGIN",
    PROJECT_COST: "PROJECT COST",
    POTENTIAL_LOAN: "POTENTIAL LOAN",
    BENEFICIARY: "BENEFICIARY",
    INSTITUTIONAL_FINANCING: "INSTITUTIONAL FINANCING",
    REPAYMENT_QUESTION: "Can the business actually repay?",
    REPAYMENT_EXPLANATION: "Left: the numbers. Right: the same month as a polar area, so scale is instant.",
    CALCULATION_NOTE: "EMI = P·r·(1+r)ⁿ ⁄ ((1+r)ⁿ−1) · P ₹9L · 8%/12 · n 84 ⇒ {emi}/mo · {quarterly}/qtr · buffer {buffer}/mo · 6-month moratorium",
    REPAYMENT_HEALTH: "Repayment health",
    SAFE: "Safe",
    RAW_INFORMATION: "Raw information in.",
    ONE_QUESTION: "One question in.",
    ANALYZE_CTA_UPPER: "ANALYZE MY BUSINESS",
    PROTOTYPE_NOTE: "PROTOTYPE · DEMO DATA UNTIL YOUR LOCATION IS CONNECTED",
    LIVE_GEOGRAPHY: "LIVE GEOGRAPHY · 12,480 EST. CONSUMERS · 10 KM RADIUS",
    DISCOVERY: "DISCOVERY",
    DEMO_PURPOSES: "YOUTUBE · FOR DEMO PURPOSES ONLY",
    OFFICER_PORTAL_ARROW: "Officer portal →",
    STARTS_SOMEWHERE: "starts somewhere.",
    GRAMINTEL_LOCAL_SIGNAL: "GramIntel helps turn that local signal into a business decision you can defend.",
    LOCAL_PLACES: "LOCAL PLACES · GANDIPET 8KM",
    MARKET: "Market",
    FOOD: "Food",
    FAMOUS_PLACES: "Famous Places",
    HEALTH: "Health",
    EDUCATION: "Education",
    FINANCE: "Finance",
    RETAIL: "Retail",
    TRANSPORT: "Transport",
    DEMO_DATA_CLUSTERED: "Demo data · clustered",
    TITLE_THE_PROBLEM: "THE PROBLEM",
    TITLE_HOW_THINKS: "HOW GRAMINTEL THINKS",
    TITLE_MARKET_MAP: "MARKET MAP",
    TITLE_MARKET_INTELLIGENCE: "MARKET INTELLIGENCE · CLOSE-UP",
    TITLE_BUSINESS_VIABILITY: "BUSINESS VIABILITY",
    TITLE_INTELLIGENCE_ENGINE: "INTELLIGENCE ENGINE",
    TITLE_FINANCIAL_STRUCTURE: "FINANCIAL STRUCTURE",
    TITLE_SCHEME_ROUTING: "SCHEME ROUTING",
    TITLE_REPAYMENT_SIMULATION: "REPAYMENT SIMULATION",
    TITLE_MULTILINGUAL: "MULTILINGUAL",
    TITLE_MAKE_IT_DEFENSIBLE: "MAKE IT DEFENSIBLE",
    TITLE_SPEAKING_LANGUAGE: "SPEAKING YOUR LANGUAGE",
    TITLE_REASONING_PIPELINE: "THE REASONING PIPELINE",
    TITLE_MONEY_VISIBLE: "THE MONEY, MADE VISIBLE",
    STAGE_LOCATION: "Location",
    STAGE_MARKET: "Market",
    STAGE_COMPETITION: "Competition",
    STAGE_OPPORTUNITY: "Opportunity",
    STAGE_FINANCE: "Finance",
    STAGE_LOCATION_LINE: "One pin. Your village, placed on the economic map.",
    STAGE_MARKET_LINE: "Consumer density, spending power and footfall within reach.",
    STAGE_COMPETITION_LINE: "Every shop already serving your customers — counted.",
    STAGE_OPPORTUNITY_LINE: "The gap between what people need and what exists.",
    STAGE_FINANCE_LINE: "Costs, loans, repayment — viability before commitment.",
    FIVE_MOVES: "Five moves from a point on the map to a bankable decision.",
    PILLAR_MARKET_DETAIL: "12,480 consumers · 10 km radius",
    PILLAR_OPPORTUNITY_DETAIL: "Value-added dairy · 78/100 score",
    PILLAR_FINANCE_DETAIL: "₹1L margin → ₹9L loan · 8% · 7 years",
    GANDIPET_HYDERABAD: "Gandipet · Hyderabad",
    SMART_INDIA_HACKATHON: "Smart India Hackathon",
    PROBLEM_HEAD: "Rural entrepreneurs make billion-rupee decisions with almost no local data.",
    PROBLEM_HEAD_A: "Rural entrepreneurs make",
    PROBLEM_HEAD_B: "billion-rupee decisions",
    PROBLEM_HEAD_C: "with almost no local data.",
    PROBLEM_BODY: "A loan officer sees a credit score. A family sees collateral. Nobody sees the village market itself — until now.",
    SCROLL_SIGNAL: "SCROLL — WATCH THE SIGNAL ORGANIZE →",
    DEMAND: "DEMAND",
    SUPPLY_GAP: "SUPPLY GAP",
    COMPETITION_LABEL: "COMPETITION",
    DEFENSIBLE_HEAD_A: "A",
    DEFENSIBLE_HEAD_B: "defensible decision",
    DEFENSIBLE_HEAD_C: "out.",
    PIPELINE_BODY: "No chatbot to interrogate. One pipeline that reads your context and returns structured intelligence.",
    INPUT: "INPUT",
    INTELLIGENCE_ENGINE: "INTELLIGENCE ENGINE",
    OUTPUT: "OUTPUT",
    MARGIN_FAMILY: "What a working family can actually save and risk.",
    DAIRY_UNIT: "A dairy value-addition unit: equipment, shed, cattle, working capital.",
    FINANCING_COVERS: "Institutional financing covers what savings cannot.",
    ILLUSTRATIVE_CALCULATION: "ILLUSTRATIVE CALCULATION · EMI = P·r·(1+r)ⁿ ⁄ ((1+r)ⁿ−1), r = 8%/12, n = 84 · DETERMINISTIC",
    THE_DECISION: "THE DECISION",
    THE: "The",
    DONT_START_LOAN: "Don’t start with a loan.",
    START_DECISION: "Start with a decision.",
    UNDERSTAND_MARKET: "Understand your market.",
    UNDERSTAND_OPPORTUNITY: "Understand your opportunity.",
    UNDERSTAND_FINANCES: "Understand your finances.",
    GOOD_POTENTIAL_LABEL: "Good potential",
    SUPPLY_RADIUS: "Supply ≤6km radius",
    SPEAK_LANGUAGE_HEAD: "Intelligence should speak your language.",
    YOUR_DECISION: "Your decision, in your language.",
    PRODUCT: "PRODUCT",
    CONTEXT: "CONTEXT",
    CONNECT: "CONNECT",
    THE_METHOD: "The Method",
    MARKET_INTELLIGENCE: "Market Intelligence",
    SCHEME_ROUTER: "Scheme Router",
    REPAYMENT_PLANNER: "Repayment Planner",
    THE_PROBLEM_LINK: "The Problem",
    DATA_SOURCES: "Data Sources",
    IMPACT_MODEL: "Impact Model",
    FOR_LENDERS: "For Lenders",
    TEAM_GRAMINTEL: "Team GramIntel",
    CONTACT: "Contact",
    HYPER_LOCAL: "HYPER-LOCAL ENTERPRISE INTELLIGENCE",
    FOOTER_COPY: "© 2026 GRAMINTEL · FROM A LOCATION ON A MAP TO A CONFIDENT BUSINESS DECISION",
    BUILT_FOR_SIH: "BUILT FOR SIH",
    LOCAL_DEMAND: "LOCAL DEMAND",
    MILK_RISING: "Milk & dairy spend rising fastest within the radius.",
    MARKET_QUANTIFIED: "The market, quantified.",
    MARKET_BODY: "The same signals a seasoned trader reads intuitively — counted, priced and scored for your specific location.",
    ESTIMATED_CONSUMERS: "ESTIMATED CONSUMERS",
    SIMILAR_BUSINESSES: "SIMILAR BUSINESSES",
    PRICE_RANGE: "PRICE RANGE",
    OPPORTUNITY_SCORE: "OPPORTUNITY SCORE",
    LOCAL_DEMAND_GEO: "LIVE GEOGRAPHY · 12,480 EST. CONSUMERS · 10 KM RADIUS",
    RURAL_STARTS: "Every confident business decision starts somewhere.",
    THE_GAP: "the gap",
    SCHEME_QUESTION: "One question in.",
    RIGHT_SCHEME: "right scheme",
    LIGHTS_UP: "lights up.",
    MICRO_NEED: "I need a project ≤ ₹1.40 lakh",
    TERM_NEED: "My project costs more",
    MICRO_FINANCE: "MICRO FINANCE",
    TERM_LOAN: "TERM LOAN",
    MUDRA_SHISHU: "MUDRA SHISHU",
    MUDRA_TARUN: "MUDRA TARUN / PMEGP",
    MICRO_DETAIL: "≤₹1.40L → Micro · 6.5% · 3yr + 3mo",
    TERM_DETAIL: ">₹1.40L ≤₹50L → Term · 8% · 7yr + 6mo",
    PROJECT_THRESHOLD: "≤ ₹1.40 L?",
    SCHEME_FOOTNOTE: "MUDRA Shishu ≤₹50k / Kishor ≤₹5L / Tarun ≤₹10L mapped to SCA’s ₹1.40L micro cap",
    SCHEME_GUIDELINES: "ELIGIBILITY LOGIC SYNCED WITH PMMY / PMEGP GUIDELINES · INDICATIVE",
    RADIUS_10KM: "10 km radius",
    LOCATION_LAYER: "location layer",
    VALUE_ADDED_DAIRY: "value-added dairy",
    COMPOSITE_MODEL: "Composite model · weights tuned for rural micro-enterprise · weights: demand 0.30, supply 0.20, pricing 0.15, competition 0.15, finance 0.10, risk 0.10",
    LIVE_DISCOVERY: "DISCOVERY",
    FIELD_DOCUMENTATION: "FIELD DOCUMENTATION · GANDIPET",
    VILLAGE_MARKET_NEED: "A village. A market. A need. An opportunity.",
    LOCAL_SIGNAL_SENTENCE: "GramIntel helps turn that local signal into a business decision you can defend.",
    ENTER_EMAIL: "Enter email",
    ENTER_CODE: "Enter code",
    FAILED: "Failed",
    INVALID_CODE: "Invalid code",
    NOT_ADMIN: "Not an admin account",
    GOOGLE_SIGNIN_FAILED: "Google sign-in failed",
    SESSION_EXPIRED: "Session expired — please re-login",
    SELECT_CASE_FIRST: "Select a case first",
    CASE_NOT_LOADED: "Case detail not loaded — click the case again",
    NOTE_REQUIRED: "Decision note is required — type why approve/reject",
    ALREADY_FINAL: "Already {status} — no further transition",
    DRAFT_CANNOT_DECIDE: "Cannot decide on DRAFT — applicant must click Submit in /assistant first. This case is still DRAFT.",
    DECISION_FAILED: "Decision failed",
    HISTORY_UPDATED: "Case #{id} {decision} — history updated",
    VERIFIED_RECORD: "Verified data:",
    FALLBACK_RECORD: "Simulation fallback:",
    POPULATION: "pop",
    MARGIN: "margin",
    PROJECT: "project",
    LOAN: "loan",
    MONTH: "/mo",
    MONTHS: "months",
    QUARTER: "/qtr",
    YEARS: "years",
    MORATORIUM: "moratorium",
    NOT_SIGNED_IN: "Not signed in",
    OTP_HELP: "OTP is 6 digits and expires in 10 min (max 3 / 10 min). The code is delivered through the configured OTP provider.",
    FEASIBILITY_SIGNALS: "feasibility · 6 signals",
    VERIFIED_GOVERNMENT_DATA: "Verified government dataset:",
    REGIONAL_FALLBACK: "Regional baseline (fallback):",
    GROUNDED_IN: "Grounded in",
    HOUSEHOLDS: "households",
    DAIRY_COOPS: "Dairy Co-ops in cluster",
    ACTIVE_SHGS: "NRLM SHGs",
    POWER_GRID: "Power grid",
    REGIONAL_FALLBACK_NOTE: "Village demographic record not found in primary sample; using calibrated regional fallback (12,480 consumers · ₹8.4L monthly demand baseline).",
    SYNTHESISING: "Synthesising…",
    OPPORTUNITY: "Opportunity:",
    SWOT_LABEL: "SWOT:",
    THREATS: "Threats:",
    PRICING: "Pricing:",
    MODEL_SOURCE: "model",
    NO_NARRATIVE: "No narrative yet — click a language.",
    MONTHLY_SPLIT: "MONTHLY SPLIT · POLAR VIEW",
    CASH_FLOW_CHART: "Polar area chart of cash flow",
    REVENUE: "Revenue",
    COSTS: "Costs",
    SURPLUS: "Surplus",
    BUFFER: "Buffer",
    INFLOW: "inflow",
    OPERATING: "operating",
    BEFORE_EMI: "before EMI",
    STAYS: "stays",
    MONTHLY_REVENUE: "Monthly revenue",
    OPERATING_COSTS: "Operating costs",
    GROSS_SURPLUS: "Gross surplus",
    LOAN_REPAYMENT: "Loan repayment (EMI)",
    NET_BUFFER: "Net buffer",
    INCLUDING_WORKING_CAPITAL: "incl. working capital {amount}",
    QUARTERLY_LOAN: "loan",
    STAYS_WITH_YOU: "stays with you",
    MONTHLY: "monthly",
    RADIUS_MONTHLY: "Radius = monthly ₹ · Angle equal · Buffer highlighted at center",
    TERM_LOAN_NOTE: "Term Loan · 8% · 7yr · 6-month moratorium · quarterly: ₹{amount}/qtr",
    FAMILY_BUFFER: "{amount} stays in the family’s hands — every single month.",
    LOCATING: "Locating…",
    USE_LOCATION: "Use my location",
    LOCATION_UNAVAILABLE: "Location unavailable — search for your village instead. Browsers only share location over HTTPS with permission.",
    GEO_UNSUPPORTED: "Geolocation is not supported in this browser — search for your village instead.",
    EXPLORING: "Exploring",
    FUNDED_BUSINESS: "GramIntel-funded business",
    FUNDED_BUSINESSES: "GramIntel-funded businesses",
    IN_VIEW: "in view",
    NEARBY: "nearby",
    ANALYZE_AREA: "Analyze this area in GramIntel",
    CONTINUES_ASSISTANT: "Continues in the assistant with {location} · {category}",
    VERIFIED_DATA: "VERIFIED DATA",
    AI_ESTIMATE: "AI ESTIMATE",
    DEMO_DATA: "DEMO DATA",
    DATA_SOURCE: "DATA SOURCE",
    MODEL: "MODEL",
    PROTOTYPE: "PROTOTYPE",
    PUBLIC_DATASET: "Public dataset",
    AI_ESTIMATE_MEDIUM: "AI estimate · Confidence: Medium",
    SIMULATED_DATA: "Simulated data · For demonstration",
  },
  hi: {
    LANGUAGE: "भाषा",
    ENGLISH: "अंग्रेज़ी",
    HINDI: "हिंदी",
    TELUGU: "तेलुगु",
    SKIP_TO_CONTENT: "मुख्य सामग्री पर जाएँ",
    RELOAD: "फिर से लोड करें",
    SECTION_UNAVAILABLE: "अनुभाग अभी उपलब्ध नहीं है — कहानी जारी है",
    MAP: "मानचित्र",
    ASSISTANT: "सहायक",
    PORTAL: "पोर्टल",
    LOGOUT: "लॉगआउट",
    OFFICER_PORTAL: "अधिकारी पोर्टल",
    APPLICANT_WORKSPACE: "आवेदक कार्यक्षेत्र",
    HOME: "होम",
    PRIMARY_NAV: "मुख्य नेविगेशन",
    MOBILE_NAV: "मोबाइल नेविगेशन",
    MAP_EXPLORER: "मानचित्र अन्वेषक",
    LOADING_MAP: "मानचित्र लोड हो रहा है · अन्वेषक तैयार हो रहा है",
    OFFLINE_MAP: "आप ऑफ़लाइन हैं — कैश किया गया मानचित्र डेटा दिखाया जा रहा है।",
    LIVE_DATA_UNAVAILABLE: "लाइव व्यवसाय डेटा अस्थायी रूप से अनुपलब्ध है — कैश/डेमो स्थानीय डेटा दिखाया जा रहा है।",
    RETRY_LIVE_DATA: "लाइव डेटा फिर आज़माएँ",
    MAP_RADIUS: "मानचित्र अन्वेषण त्रिज्या",
    MAP_RADIUS_NOTE: "केवल अन्वेषण — व्यवहार्यता रिपोर्ट हमेशा 10 किमी का उपयोग करती है।",
    SEARCH_MODE: "खोज मोड",
    LOCATION: "स्थान",
    F_VILLAGE: "गाँव",
    R_MARKET: "बाज़ार पहुँच · 5–10 कि.मी.",
    CAPITAL: "पूँजी",
    BUSINESS_IDEA: "व्यवसाय विचार",
    COMPETITION: "प्रतिस्पर्धा",
    RISK: "जोखिम",
    DATA_SATELLITE: "उपग्रह + सरकारी खुले आँकड़े",
    DATA_PRICE: "स्थानीय मूल्य आँकड़े",
    DATA_SCHEME: "योजना पात्रता नियम",
    DATA_RISK: "जोखिम अनुमान",
    BUSINESS: "व्यवसाय",
    SEARCH_VILLAGE: "गाँव या शहर खोजें",
    TYPE_VILLAGE: "भारत में गाँव या शहर लिखें",
    SEARCH_BUSINESSES: "दिख रहे व्यवसाय खोजें",
    SEARCH_BY_NAME: "नाम या श्रेणी से खोजें",
    SEARCHING: "खोजा जा रहा है…",
    MATCHING_PLACES: "मिलते-जुलते स्थान",
    MATCHING_BUSINESSES: "मिलते-जुलते व्यवसाय",
    NO_PLACES: "कोई स्थान नहीं मिला — पास का शहर आज़माएँ",
    NEARBY_BUSINESSES: "आस-पास के व्यवसाय",
    ALL: "सभी",
    LOADING: "लोड हो रहा है",
    NO_BUSINESSES: "इस दृश्य में अभी कोई व्यवसाय नहीं है — त्रिज्या बढ़ाएँ या पास का शहर खोजें।",
    BUSINESSES: "व्यवसाय",
    AREA_SIGNALS: "क्षेत्रीय संकेत",
    BUSINESSES_MAPPED: "मानचित्रित व्यवसाय",
    DOMINANT_CATEGORY: "प्रमुख श्रेणी",
    AVG_DISTANCE: "औसत दूरी",
    CATEGORIES_DETECTED: "पहचानी गई श्रेणियाँ",
    DENSITY_BAND: "घनत्व स्तर",
    NO_DATA: "कोई डेटा नहीं",
    LIVE_OSM_RESULTS: "इस खोज क्षेत्र के लाइव OpenStreetMap परिणाम",
    CACHED_DEMO_DATA: "कैश या डेमो स्थानीय डेटा — लाइव खोज अनुपलब्ध",
    MAP_SIGNALS_NOTE: "मानचित्र अन्वेषण संकेत — व्यवहार्यता रिपोर्ट नहीं",
    OPPORTUNITY_CHECK: "अवसर जाँच",
    BUSINESS_CATEGORY: "व्यवसाय श्रेणी",
    NEARBY_COMPETITORS: "आस-पास के प्रतिस्पर्धी",
    CLOSEST: "सबसे निकट",
    DENSITY: "घनत्व",
    SIGNAL: "संकेत",
    DISTANCE: "दूरी",
    CLOSE_DETAILS: "विवरण बंद करें",
    DETAILS_FOR: "{name} का विवरण",
    VIEW_ON_MAP: "मानचित्र पर देखें",
    VIEW_ON_OSM: "OpenStreetMap पर देखें",
    GRAMINTEL_FUNDED: "GramIntel-वित्तपोषित व्यवसाय — अधिकारी ने ऋण स्वीकृत किया",
    DEMO_LISTING: "डेमो सूची — प्रतिनिधि स्थानीय व्यवसाय, लाइव डेटा नहीं",
    OSM_DETAILS: "अधिक विवरण: OpenStreetMap से उपलब्ध नहीं",
    AREA_RESULTS: "क्षेत्रीय परिणाम",
    CLOSE_RESULTS: "परिणाम बंद करें",
    FILTER_CATEGORY: "श्रेणी के अनुसार फ़िल्टर",
    CASES: "केस",
    AI_CASE_ADVISOR: "AI केस सलाहकार",
    LANDING_PAGE: "लैंडिंग पेज",
    OFFICER_LOGIN: "अधिकारी लॉगिन",
    REVIEW_DECIDE: "विश्वास के साथ समीक्षा और निर्णय लें।",
    OR_OTP: "या OTP",
    ADMIN_EMAIL: "प्रशासक ईमेल",
    SIX_DIGIT_CODE: "6 अंकों का कोड",
    SEND_OTP: "OTP भेजें",
    SENDING: "भेजा जा रहा है…",
    VERIFY: "सत्यापित करें",
    VERIFYING: "सत्यापन हो रहा है…",
    BACK: "वापस",
    GOOGLE_CONTINUE: "Google से जारी रखें",
    ADMIN_GOOGLE_HELP: "अधिकारी पोर्टल खोलने के लिए प्रशासक Google खाते से साइन इन करें। कोड उसी पते पर ईमेल किया जाएगा।",
    QUEUE: "कतार",
    SHOWN: "दिखाए गए",
    ALL_STATUSES: "सभी स्थितियाँ",
    REFRESH: "रिफ़्रेश",
    NO_CASES_FILTER: "इस फ़िल्टर के लिए कोई केस नहीं है। आवेदक /assistant से जमा करते हैं — फिर वे यहाँ दिखाई देंगे।",
    SELECT_CASE: "पूरी व्यवहार्यता, वित्तीय जानकारी और विवरण देखने तथा निर्णय लेने के लिए कतार से केस चुनें।",
    CLOSE: "बंद करें",
    MARKET_REACH: "बाज़ार पहुँच",
    VIABILITY: "व्यवहार्यता",
    NARRATIVES: "विवरण",
    STATUS_HISTORY: "स्थिति इतिहास",
    DECISION: "निर्णय",
    DECISION_NOTE: "अनिवार्य टिप्पणी — स्वीकृति/अस्वीकृति का कारण (समयरेखा में दिखेगा)",
    APPROVE: "स्वीकृत करें",
    REJECT: "अस्वीकृत करें",
    TRANSITIONS: "स्थिति क्रम: DRAFT→SUBMITTED→UNDER_REVIEW→APPROVED|REJECTED। पहले निर्णय पर बैकएंड SUBMITTED को UNDER_REVIEW में बदलता है।",
    CASE_TOTAL: "कुल {n}",
    STATUS_DRAFT: "प्रारूप",
    STATUS_SUBMITTED: "जमा किया गया",
    STATUS_UNDER_REVIEW: "समीक्षा में",
    STATUS_APPROVED: "स्वीकृत",
    STATUS_REJECTED: "अस्वीकृत",
    LANDING_ANALYZE: "मेरा व्यवसाय विश्लेषण करें",
    LANDING_METHOD: "विधि",
    LANDING_MARKET: "बाज़ार",
    LANDING_VIABILITY: "व्यवहार्यता",
    LANDING_FINANCE: "वित्त",
    LANDING_SCHEMES: "योजनाएँ",
    LANDING_LANGUAGE: "भाषा",
    LANDING_HOW: "यह कैसे सोचता है देखें",
    LANDING_MAP: "लाइव व्यवसाय मानचित्र देखें",
    HOW_THINKS: "03 — GRAMINTEL कैसे सोचता है",
    TIP_ZOOM: "सुझाव: Ctrl दबाकर स्क्रॉल से ज़ूम करें · खींचकर पैन करें",
    YOUR_MARGIN: "आपकी मार्जिन पूँजी",
    PROJECT_COST: "परियोजना लागत",
    POTENTIAL_LOAN: "संभावित ऋण",
    BENEFICIARY: "लाभार्थी",
    INSTITUTIONAL_FINANCING: "संस्थागत वित्तपोषण",
    REPAYMENT_QUESTION: "क्या व्यवसाय वास्तव में ऋण चुका सकता है?",
    REPAYMENT_EXPLANATION: "बाईं ओर संख्याएँ हैं। दाईं ओर वही महीना ध्रुवीय दृश्य में है, जिससे पैमाना तुरंत समझ आता है।",
    CALCULATION_NOTE: "ईएमआई = P·r·(1+r)ⁿ ⁄ ((1+r)ⁿ−1) · P ₹9 लाख · 8%/12 · n 84 ⇒ {emi}/माह · {quarterly}/तिमाही · बचत {buffer}/माह · 6 माह की अधिस्थगन अवधि",
    REPAYMENT_HEALTH: "पुनर्भुगतान स्थिति",
    SAFE: "सुरक्षित",
    RAW_INFORMATION: "कच्ची जानकारी से शुरुआत।",
    ONE_QUESTION: "एक प्रश्न से शुरुआत।",
    ANALYZE_CTA_UPPER: "मेरा व्यवसाय विश्लेषण करें",
    PROTOTYPE_NOTE: "प्रोटोटाइप · आपका स्थान जुड़ने तक डेमो डेटा",
    LIVE_GEOGRAPHY: "लाइव भूगोल · 12,480 अनुमानित उपभोक्ता · 10 किमी त्रिज्या",
    DISCOVERY: "खोज",
    DEMO_PURPOSES: "YouTube · केवल डेमो के लिए",
    OFFICER_PORTAL_ARROW: "अधिकारी पोर्टल →",
    STARTS_SOMEWHERE: "कहीं से शुरू होता है।",
    GRAMINTEL_LOCAL_SIGNAL: "GramIntel उस स्थानीय संकेत को ऐसे व्यावसायिक निर्णय में बदलता है जिसका आप बचाव कर सकें।",
    LOCAL_PLACES: "स्थानीय स्थान · गांडीपेट 8 किमी",
    MARKET: "बाज़ार",
    FOOD: "खाद्य",
    FAMOUS_PLACES: "प्रसिद्ध स्थान",
    HEALTH: "स्वास्थ्य",
    EDUCATION: "शिक्षा",
    FINANCE: "वित्त",
    RETAIL: "खुदरा",
    TRANSPORT: "परिवहन",
    DEMO_DATA_CLUSTERED: "डेमो डेटा · समूहित",
    TITLE_THE_PROBLEM: "समस्या",
    TITLE_HOW_THINKS: "GRAMINTEL कैसे सोचता है",
    TITLE_MARKET_MAP: "बाज़ार मानचित्र",
    TITLE_MARKET_INTELLIGENCE: "बाज़ार जानकारी · क्लोज़-अप",
    TITLE_BUSINESS_VIABILITY: "व्यवसाय व्यवहार्यता",
    TITLE_INTELLIGENCE_ENGINE: "इंटेलिजेंस इंजन",
    TITLE_FINANCIAL_STRUCTURE: "वित्तीय संरचना",
    TITLE_SCHEME_ROUTING: "योजना चयन",
    TITLE_REPAYMENT_SIMULATION: "पुनर्भुगतान सिमुलेशन",
    TITLE_MULTILINGUAL: "बहुभाषी",
    TITLE_MAKE_IT_DEFENSIBLE: "इसे बचाव योग्य बनाएँ",
    TITLE_SPEAKING_LANGUAGE: "आपकी भाषा में",
    TITLE_REASONING_PIPELINE: "तर्क प्रक्रिया",
    TITLE_MONEY_VISIBLE: "पैसे को स्पष्ट बनाना",
    STAGE_LOCATION: "स्थान",
    STAGE_MARKET: "बाज़ार",
    STAGE_COMPETITION: "प्रतिस्पर्धा",
    STAGE_OPPORTUNITY: "अवसर",
    STAGE_FINANCE: "वित्त",
    STAGE_LOCATION_LINE: "एक पिन। आपका गाँव आर्थिक मानचित्र पर।",
    STAGE_MARKET_LINE: "पहुँच के भीतर उपभोक्ता घनत्व, खर्च क्षमता और आवागमन।",
    STAGE_COMPETITION_LINE: "आपके ग्राहकों की सेवा कर रही हर दुकान — गिनी गई।",
    STAGE_OPPORTUNITY_LINE: "लोगों की ज़रूरत और मौजूदा सेवाओं के बीच का अंतर।",
    STAGE_FINANCE_LINE: "लागत, ऋण, पुनर्भुगतान — प्रतिबद्धता से पहले व्यवहार्यता।",
    FIVE_MOVES: "मानचित्र के एक बिंदु से बैंक-योग्य निर्णय तक पाँच कदम।",
    PILLAR_MARKET_DETAIL: "12,480 उपभोक्ता · 10 किमी क्षेत्र",
    PILLAR_OPPORTUNITY_DETAIL: "मूल्य-वर्धित डेयरी · 78/100 स्कोर",
    PILLAR_FINANCE_DETAIL: "₹1 लाख मार्जिन → ₹9 लाख ऋण · 8% · 7 वर्ष",
    GANDIPET_HYDERABAD: "गांडीपेट · हैदराबाद",
    SMART_INDIA_HACKATHON: "स्मार्ट इंडिया हैकाथॉन",
    PROBLEM_HEAD: "ग्रामीण उद्यमी लगभग बिना स्थानीय डेटा के अरबों रुपये के निर्णय लेते हैं।",
    PROBLEM_HEAD_A: "ग्रामीण उद्यमी",
    PROBLEM_HEAD_B: "अरबों रुपये के निर्णय",
    PROBLEM_HEAD_C: "लगभग बिना स्थानीय डेटा के लेते हैं।",
    PROBLEM_BODY: "ऋण अधिकारी क्रेडिट स्कोर देखता है। परिवार संपार्श्विक देखता है। गाँव का बाज़ार कोई नहीं देखता — अब तक।",
    SCROLL_SIGNAL: "स्क्रॉल करें — संकेत को व्यवस्थित होते देखें →",
    DEMAND: "मांग",
    SUPPLY_GAP: "आपूर्ति अंतर",
    COMPETITION_LABEL: "प्रतिस्पर्धा",
    DEFENSIBLE_HEAD_A: "एक",
    DEFENSIBLE_HEAD_B: "बचाव योग्य निर्णय",
    DEFENSIBLE_HEAD_C: "बाहर आता है।",
    PIPELINE_BODY: "पूछताछ करने वाला चैटबॉट नहीं। एक प्रक्रिया जो आपका संदर्भ पढ़ती है और संरचित जानकारी लौटाती है।",
    INPUT: "इनपुट",
    INTELLIGENCE_ENGINE: "इंटेलिजेंस इंजन",
    OUTPUT: "आउटपुट",
    MARGIN_FAMILY: "एक कामकाजी परिवार वास्तव में जितना बचा और जोखिम में लगा सकता है।",
    DAIRY_UNIT: "डेयरी मूल्य-वर्धन इकाई: उपकरण, शेड, पशु, कार्यशील पूँजी।",
    FINANCING_COVERS: "संस्थागत वित्तपोषण उस हिस्से को पूरा करता है जिसे बचत नहीं कर सकती।",
    ILLUSTRATIVE_CALCULATION: "उदाहरणात्मक गणना · EMI = P·r·(1+r)ⁿ ⁄ ((1+r)ⁿ−1), r = 8%/12, n = 84 · नियत",
    THE_DECISION: "निर्णय",
    THE: "",
    DONT_START_LOAN: "ऋण से शुरुआत न करें।",
    START_DECISION: "निर्णय से शुरुआत करें।",
    UNDERSTAND_MARKET: "अपने बाज़ार को समझें।",
    UNDERSTAND_OPPORTUNITY: "अपने अवसर को समझें।",
    UNDERSTAND_FINANCES: "अपने वित्त को समझें।",
    GOOD_POTENTIAL_LABEL: "अच्छी संभावना",
    SUPPLY_RADIUS: "6 किमी के भीतर आपूर्ति",
    SPEAK_LANGUAGE_HEAD: "इंटेलिजेंस को आपकी भाषा बोलनी चाहिए।",
    YOUR_DECISION: "आपका निर्णय, आपकी भाषा में।",
    PRODUCT: "उत्पाद",
    CONTEXT: "संदर्भ",
    CONNECT: "संपर्क",
    THE_METHOD: "विधि",
    MARKET_INTELLIGENCE: "बाज़ार जानकारी",
    SCHEME_ROUTER: "योजना चयन",
    REPAYMENT_PLANNER: "पुनर्भुगतान योजनाकार",
    THE_PROBLEM_LINK: "समस्या",
    DATA_SOURCES: "डेटा स्रोत",
    IMPACT_MODEL: "प्रभाव मॉडल",
    FOR_LENDERS: "ऋणदाताओं के लिए",
    TEAM_GRAMINTEL: "GramIntel टीम",
    CONTACT: "संपर्क",
    HYPER_LOCAL: "अति-स्थानीय उद्यम जानकारी",
    FOOTER_COPY: "© 2026 GRAMINTEL · मानचित्र के एक स्थान से आत्मविश्वासपूर्ण व्यावसायिक निर्णय तक",
    BUILT_FOR_SIH: "SIH के लिए निर्मित",
    LOCAL_DEMAND: "स्थानीय मांग",
    MILK_RISING: "त्रिज्या के भीतर दूध और डेयरी पर खर्च सबसे तेज़ी से बढ़ रहा है।",
    MARKET_QUANTIFIED: "बाज़ार, मापा हुआ।",
    MARKET_BODY: "अनुभवी व्यापारी जिन संकेतों को सहज रूप से पढ़ता है — उन्हें आपके स्थान के लिए गिना, मूल्यांकित और स्कोर किया गया है।",
    ESTIMATED_CONSUMERS: "अनुमानित उपभोक्ता",
    SIMILAR_BUSINESSES: "समान व्यवसाय",
    PRICE_RANGE: "मूल्य सीमा",
    OPPORTUNITY_SCORE: "अवसर स्कोर",
    LOCAL_DEMAND_GEO: "लाइव भूगोल · 12,480 अनुमानित उपभोक्ता · 10 किमी त्रिज्या",
    RURAL_STARTS: "हर आत्मविश्वासपूर्ण व्यावसायिक निर्णय कहीं से शुरू होता है।",
    THE_GAP: "अंतर",
    SCHEME_QUESTION: "एक प्रश्न से शुरुआत।",
    RIGHT_SCHEME: "सही योजना",
    LIGHTS_UP: "चमक उठती है।",
    MICRO_NEED: "मुझे ₹1.40 लाख तक की परियोजना चाहिए",
    TERM_NEED: "मेरी परियोजना की लागत अधिक है",
    MICRO_FINANCE: "सूक्ष्म वित्त योजना",
    TERM_LOAN: "सावधि ऋण योजना",
    MUDRA_SHISHU: "मुद्रा शिशु",
    MUDRA_TARUN: "मुद्रा तरुण / पीएमईजीपी",
    MICRO_DETAIL: "≤₹1.40 लाख → सूक्ष्म · 6.5% · 3 वर्ष + 3 माह",
    TERM_DETAIL: ">₹1.40 लाख ≤₹50 लाख → सावधि · 8% · 7 वर्ष + 6 माह",
    PROJECT_THRESHOLD: "₹1.40 लाख तक?",
    SCHEME_FOOTNOTE: "मुद्रा शिशु ≤₹50 हजार / किशोर ≤₹5 लाख / तरुण ≤₹10 लाख को एससीए की ₹1.40 लाख सूक्ष्म सीमा में मैप किया गया है",
    SCHEME_GUIDELINES: "पात्रता तर्क पीएमएमवाई / पीएमईजीपी दिशानिर्देशों के अनुसार · संकेतात्मक",
    RADIUS_10KM: "10 किमी त्रिज्या",
    LOCATION_LAYER: "स्थान परत",
    VALUE_ADDED_DAIRY: "मूल्यवर्धित डेयरी",
    COMPOSITE_MODEL: "संयुक्त मॉडल · ग्रामीण सूक्ष्म उद्यम के लिए समायोजित भार · भार: मांग 0.30, आपूर्ति 0.20, मूल्य 0.15, प्रतिस्पर्धा 0.15, वित्त 0.10, जोखिम 0.10",
    LIVE_DISCOVERY: "खोज",
    FIELD_DOCUMENTATION: "मैदानी दस्तावेज़ · गांडीपेट",
    VILLAGE_MARKET_NEED: "एक गाँव। एक बाज़ार। एक ज़रूरत। एक अवसर।",
    LOCAL_SIGNAL_SENTENCE: "GramIntel उस स्थानीय संकेत को ऐसे व्यावसायिक निर्णय में बदलता है जिसका आप बचाव कर सकें।",
    ENTER_EMAIL: "ईमेल दर्ज करें",
    ENTER_CODE: "कोड दर्ज करें",
    FAILED: "विफल",
    INVALID_CODE: "अमान्य कोड",
    NOT_ADMIN: "यह प्रशासक खाता नहीं है",
    GOOGLE_SIGNIN_FAILED: "Google साइन-इन विफल",
    SESSION_EXPIRED: "सत्र समाप्त हो गया — कृपया फिर लॉगिन करें",
    SELECT_CASE_FIRST: "पहले एक केस चुनें",
    CASE_NOT_LOADED: "केस विवरण लोड नहीं हुआ — केस पर फिर क्लिक करें",
    NOTE_REQUIRED: "निर्णय टिप्पणी आवश्यक है — स्वीकृति/अस्वीकृति का कारण लिखें",
    ALREADY_FINAL: "पहले से {status} — आगे कोई बदलाव नहीं",
    DRAFT_CANNOT_DECIDE: "DRAFT पर निर्णय नहीं लिया जा सकता — आवेदक को पहले /assistant में Submit दबाना होगा। यह केस अभी DRAFT है।",
    DECISION_FAILED: "निर्णय विफल",
    HISTORY_UPDATED: "केस #{id} {decision} — इतिहास अपडेट हुआ",
    VERIFIED_RECORD: "सत्यापित डेटा:",
    FALLBACK_RECORD: "सिमुलेशन फ़ॉलबैक:",
    POPULATION: "जनसंख्या",
    MARGIN: "मार्जिन",
    PROJECT: "परियोजना",
    LOAN: "ऋण",
    MONTH: "/माह",
    MONTHS: "माह",
    QUARTER: "/तिमाही",
    YEARS: "वर्ष",
    MORATORIUM: "अधिस्थगन",
    NOT_SIGNED_IN: "साइन इन नहीं किया गया",
    OTP_HELP: "OTP 6 अंकों का है और 10 मिनट में समाप्त हो जाता है (अधिकतम 3 / 10 मिनट)। कोड कॉन्फ़िगर किए गए OTP प्रदाता से भेजा जाता है।",
    FEASIBILITY_SIGNALS: "व्यवहार्यता · 6 संकेत",
    VERIFIED_GOVERNMENT_DATA: "सत्यापित सरकारी डेटासेट:",
    REGIONAL_FALLBACK: "क्षेत्रीय आधार (फ़ॉलबैक):",
    GROUNDED_IN: "आधार",
    HOUSEHOLDS: "परिवार",
    DAIRY_COOPS: "क्लस्टर में डेयरी सहकारी समितियाँ",
    ACTIVE_SHGS: "NRLM स्वयं सहायता समूह",
    POWER_GRID: "पावर ग्रिड",
    REGIONAL_FALLBACK_NOTE: "प्राथमिक नमूने में गाँव का जनसांख्यिकीय रिकॉर्ड नहीं मिला; कैलिब्रेटेड क्षेत्रीय फ़ॉलबैक उपयोग किया जा रहा है (12,480 उपभोक्ता · ₹8.4 लाख मासिक मांग आधार)।",
    SYNTHESISING: "संश्लेषण हो रहा है…",
    OPPORTUNITY: "अवसर:",
    SWOT_LABEL: "SWOT:",
    THREATS: "खतरे:",
    PRICING: "मूल्य निर्धारण:",
    MODEL_SOURCE: "मॉडल",
    NO_NARRATIVE: "अभी कोई विवरण नहीं — भाषा चुनें।",
    MONTHLY_SPLIT: "मासिक विभाजन · ध्रुवीय दृश्य",
    CASH_FLOW_CHART: "नकदी प्रवाह का ध्रुवीय क्षेत्र चार्ट",
    REVENUE: "राजस्व",
    COSTS: "लागत",
    SURPLUS: "अधिशेष",
    BUFFER: "बचत",
    INFLOW: "आवक",
    OPERATING: "संचालन",
    BEFORE_EMI: "EMI से पहले",
    STAYS: "बचता है",
    MONTHLY_REVENUE: "मासिक राजस्व",
    OPERATING_COSTS: "संचालन लागत",
    GROSS_SURPLUS: "सकल अधिशेष",
    LOAN_REPAYMENT: "ऋण पुनर्भुगतान (EMI)",
    NET_BUFFER: "शुद्ध बचत",
    INCLUDING_WORKING_CAPITAL: "कार्यशील पूँजी सहित {amount}",
    QUARTERLY_LOAN: "ऋण",
    STAYS_WITH_YOU: "आपके पास बचता है",
    MONTHLY: "मासिक",
    RADIUS_MONTHLY: "त्रिज्या = मासिक ₹ · कोण समान · केंद्र में बचत",
    TERM_LOAN_NOTE: "सावधि ऋण · 8% · 7 वर्ष · 6 माह अधिस्थगन · त्रैमासिक: ₹{amount}/तिमाही",
    FAMILY_BUFFER: "{amount} हर महीने परिवार के हाथों में बचता है।",
    LOCATING: "स्थान ज्ञात किया जा रहा है…",
    USE_LOCATION: "मेरा स्थान उपयोग करें",
    LOCATION_UNAVAILABLE: "स्थान उपलब्ध नहीं है — इसके बजाय अपना गाँव खोजें। ब्राउज़र अनुमति मिलने पर केवल HTTPS पर स्थान साझा करते हैं।",
    GEO_UNSUPPORTED: "इस ब्राउज़र में जियोलोकेशन समर्थित नहीं है — इसके बजाय अपना गाँव खोजें।",
    EXPLORING: "खोज रहे हैं",
    FUNDED_BUSINESS: "GramIntel-वित्तपोषित व्यवसाय",
    FUNDED_BUSINESSES: "GramIntel-वित्तपोषित व्यवसाय",
    IN_VIEW: "दृश्य में",
    NEARBY: "आस-पास",
    ANALYZE_AREA: "GramIntel में इस क्षेत्र का विश्लेषण करें",
    CONTINUES_ASSISTANT: "सहायक में {location} · {category} के साथ जारी रहेगा",
    VERIFIED_DATA: "सत्यापित डेटा",
    AI_ESTIMATE: "AI अनुमान",
    DEMO_DATA: "डेमो डेटा",
    DATA_SOURCE: "डेटा स्रोत",
    MODEL: "मॉडल",
    PROTOTYPE: "प्रोटोटाइप",
    PUBLIC_DATASET: "सार्वजनिक डेटासेट",
    AI_ESTIMATE_MEDIUM: "AI अनुमान · मध्यम विश्वास",
    SIMULATED_DATA: "सिम्युलेटेड डेटा · प्रदर्शन के लिए",
  },
  te: {
    LANGUAGE: "భాష",
    ENGLISH: "ఆంగ్లం",
    HINDI: "హిందీ",
    TELUGU: "తెలుగు",
    SKIP_TO_CONTENT: "ప్రధాన విషయానికి వెళ్లండి",
    RELOAD: "మళ్లీ లోడ్ చేయండి",
    SECTION_UNAVAILABLE: "విభాగం తాత్కాలికంగా అందుబాటులో లేదు — కథనం కొనసాగుతుంది",
    MAP: "మ్యాప్",
    ASSISTANT: "సహాయకుడు",
    PORTAL: "పోర్టల్",
    LOGOUT: "లాగ్ అవుట్",
    OFFICER_PORTAL: "అధికారి పోర్టల్",
    APPLICANT_WORKSPACE: "దరఖాస్తుదారు కార్యస్థలం",
    HOME: "హోమ్",
    PRIMARY_NAV: "ప్రధాన నావిగేషన్",
    MOBILE_NAV: "మొబైల్ నావిగేషన్",
    MAP_EXPLORER: "మ్యాప్ అన్వేషణ",
    LOADING_MAP: "మ్యాప్ లోడ్ అవుతోంది · అన్వేషణ సిద్ధమవుతోంది",
    OFFLINE_MAP: "మీరు ఆఫ్‌లైన్‌లో ఉన్నారు — క్యాష్ చేసిన మ్యాప్ డేటా చూపిస్తోంది.",
    LIVE_DATA_UNAVAILABLE: "లైవ్ వ్యాపార డేటా తాత్కాలికంగా అందుబాటులో లేదు — క్యాష్/డెమో స్థానిక డేటా చూపిస్తోంది.",
    RETRY_LIVE_DATA: "లైవ్ డేటాను మళ్లీ ప్రయత్నించండి",
    MAP_RADIUS: "మ్యాప్ అన్వేషణ పరిధి",
    MAP_RADIUS_NOTE: "అన్వేషణ మాత్రమే — సాధ్యత నివేదిక ఎల్లప్పుడూ 10 కి.మీ.ను ఉపయోగిస్తుంది.",
    SEARCH_MODE: "శోధన విధానం",
    LOCATION: "స్థానం",
    F_VILLAGE: "గ్రామం",
    R_MARKET: "మార్కెట్ పరిధి · 5–10 కి.మీ.",
    CAPITAL: "మూలధనం",
    BUSINESS_IDEA: "వ్యాపార ఆలోచన",
    COMPETITION: "పోటీ",
    RISK: "ప్రమాదం",
    DATA_SATELLITE: "ఉపగ్రహం + ప్రభుత్వ ఓపెన్ డేటా",
    DATA_PRICE: "స్థానిక ధరల సమాచారం",
    DATA_SCHEME: "పథకం అర్హత నియమాలు",
    DATA_RISK: "ప్రమాద అంచనాలు",
    BUSINESS: "వ్యాపారం",
    SEARCH_VILLAGE: "గ్రామం లేదా పట్టణాన్ని శోధించండి",
    TYPE_VILLAGE: "భారతదేశంలోని గ్రామం లేదా పట్టణాన్ని టైప్ చేయండి",
    SEARCH_BUSINESSES: "కనిపిస్తున్న వ్యాపారాలను శోధించండి",
    SEARCH_BY_NAME: "పేరు లేదా వర్గం ద్వారా శోధించండి",
    SEARCHING: "శోధిస్తోంది…",
    MATCHING_PLACES: "సరిపోలే ప్రదేశాలు",
    MATCHING_BUSINESSES: "సరిపోలే వ్యాపారాలు",
    NO_PLACES: "ప్రదేశాలు కనబడలేదు — దగ్గరలోని పట్టణాన్ని ప్రయత్నించండి",
    NEARBY_BUSINESSES: "దగ్గరలోని వ్యాపారాలు",
    ALL: "అన్నీ",
    LOADING: "లోడ్ అవుతోంది",
    NO_BUSINESSES: "ఈ దృశ్యంలో ఇంకా వ్యాపారాలు లేవు — పరిధిని పెంచండి లేదా దగ్గరలోని పట్టణాన్ని శోధించండి.",
    BUSINESSES: "వ్యాపారాలు",
    AREA_SIGNALS: "ప్రాంత సంకేతాలు",
    BUSINESSES_MAPPED: "మ్యాప్ చేసిన వ్యాపారాలు",
    DOMINANT_CATEGORY: "ప్రధాన వర్గం",
    AVG_DISTANCE: "సగటు దూరం",
    CATEGORIES_DETECTED: "గుర్తించిన వర్గాలు",
    DENSITY_BAND: "సాంద్రత స్థాయి",
    NO_DATA: "డేటా లేదు",
    LIVE_OSM_RESULTS: "ఈ శోధన ప్రాంతానికి లైవ్ OpenStreetMap ఫలితాలు",
    CACHED_DEMO_DATA: "క్యాష్ లేదా డెమో స్థానిక డేటా — లైవ్ శోధన అందుబాటులో లేదు",
    MAP_SIGNALS_NOTE: "మ్యాప్ అన్వేషణ సంకేతాలు — సాధ్యత నివేదిక కాదు",
    OPPORTUNITY_CHECK: "అవకాశ పరిశీలన",
    BUSINESS_CATEGORY: "వ్యాపార వర్గం",
    NEARBY_COMPETITORS: "దగ్గరలోని పోటీదారులు",
    CLOSEST: "అత్యంత దగ్గరగా",
    DENSITY: "సాంద్రత",
    SIGNAL: "సంకేతం",
    DISTANCE: "దూరం",
    CLOSE_DETAILS: "వివరాలను మూసివేయండి",
    DETAILS_FOR: "{name} వివరాలు",
    VIEW_ON_MAP: "మ్యాప్‌లో చూడండి",
    VIEW_ON_OSM: "OpenStreetMapలో చూడండి",
    GRAMINTEL_FUNDED: "GramIntel నిధులు అందించిన వ్యాపారం — అధికారి రుణాన్ని ఆమోదించారు",
    DEMO_LISTING: "డెమో జాబితా — ప్రతినిధి స్థానిక వ్యాపారం, లైవ్ డేటా కాదు",
    OSM_DETAILS: "మరిన్ని వివరాలు: OpenStreetMapలో అందుబాటులో లేవు",
    AREA_RESULTS: "ప్రాంత ఫలితాలు",
    CLOSE_RESULTS: "ఫలితాలను మూసివేయండి",
    FILTER_CATEGORY: "వర్గం ద్వారా ఫిల్టర్ చేయండి",
    CASES: "కేసులు",
    AI_CASE_ADVISOR: "AI కేసు సలహాదారు",
    LANDING_PAGE: "ల్యాండింగ్ పేజీ",
    OFFICER_LOGIN: "అధికారి లాగిన్",
    REVIEW_DECIDE: "నమ్మకంతో సమీక్షించి నిర్ణయం తీసుకోండి.",
    OR_OTP: "లేదా OTP",
    ADMIN_EMAIL: "అడ్మిన్ ఈమెయిల్",
    SIX_DIGIT_CODE: "6 అంకెల కోడ్",
    SEND_OTP: "OTP పంపండి",
    SENDING: "పంపుతోంది…",
    VERIFY: "ధృవీకరించండి",
    VERIFYING: "ధృవీకరిస్తోంది…",
    BACK: "వెనుకకు",
    GOOGLE_CONTINUE: "Googleతో కొనసాగండి",
    ADMIN_GOOGLE_HELP: "అధికారి పోర్టల్‌ను యాక్సెస్ చేయడానికి అడ్మిన్ Google ఖాతాతో సైన్ ఇన్ చేయండి. కోడ్ ఆ చిరునామాకు ఈమెయిల్ చేయబడుతుంది.",
    QUEUE: "క్యూ",
    SHOWN: "చూపిస్తున్నవి",
    ALL_STATUSES: "అన్ని స్థితులు",
    REFRESH: "రిఫ్రెష్",
    NO_CASES_FILTER: "ఈ ఫిల్టర్‌కు కేసులు లేవు. దరఖాస్తుదారులు /assistant నుండి సమర్పిస్తారు — తరువాత అవి ఇక్కడ కనిపిస్తాయి.",
    SELECT_CASE: "పూర్తి సాధ్యత, ఆర్థిక వివరాలు, కథనాన్ని చూడటానికి మరియు నిర్ణయం తీసుకోవడానికి క్యూ నుండి కేసును ఎంచుకోండి.",
    CLOSE: "మూసివేయండి",
    MARKET_REACH: "మార్కెట్ పరిధి",
    VIABILITY: "సాధ్యత",
    NARRATIVES: "కథనాలు",
    STATUS_HISTORY: "స్థితి చరిత్ర",
    DECISION: "నిర్ణయం",
    DECISION_NOTE: "తప్పనిసరి గమనిక — ఆమోదం/తిరస్కరణ కారణం (టైమ్‌లైన్‌లో చూపబడుతుంది)",
    APPROVE: "ఆమోదించండి",
    REJECT: "తిరస్కరించండి",
    TRANSITIONS: "స్థితి క్రమం: DRAFT→SUBMITTED→UNDER_REVIEW→APPROVED|REJECTED. మొదటి నిర్ణయంలో బ్యాకెండ్ SUBMITTEDను UNDER_REVIEWగా మారుస్తుంది.",
    CASE_TOTAL: "మొత్తం {n}",
    STATUS_DRAFT: "డ్రాఫ్ట్",
    STATUS_SUBMITTED: "సమర్పించబడింది",
    STATUS_UNDER_REVIEW: "సమీక్షలో ఉంది",
    STATUS_APPROVED: "ఆమోదించబడింది",
    STATUS_REJECTED: "తిరస్కరించబడింది",
    LANDING_ANALYZE: "నా వ్యాపారాన్ని విశ్లేషించండి",
    LANDING_METHOD: "పద్ధతి",
    LANDING_MARKET: "మార్కెట్",
    LANDING_VIABILITY: "సాధ్యత",
    LANDING_FINANCE: "ఆర్థికం",
    LANDING_SCHEMES: "పథకాలు",
    LANDING_LANGUAGE: "భాష",
    LANDING_HOW: "ఇది ఎలా ఆలోచిస్తుందో చూడండి",
    LANDING_MAP: "లైవ్ వ్యాపార మ్యాప్‌ను చూడండి",
    HOW_THINKS: "03 — GRAMINTEL ఎలా ఆలోచిస్తుంది",
    TIP_ZOOM: "సూచన: Ctrl నొక్కి స్క్రోల్‌తో జూమ్ చేయండి · లాగి పాన్ చేయండి",
    YOUR_MARGIN: "మీ మార్జిన్ మూలధనం",
    PROJECT_COST: "ప్రాజెక్ట్ వ్యయం",
    POTENTIAL_LOAN: "సంభావ్య రుణం",
    BENEFICIARY: "లబ్ధిదారు",
    INSTITUTIONAL_FINANCING: "సంస్థాగత ఫైనాన్సింగ్",
    REPAYMENT_QUESTION: "వ్యాపారం నిజంగా రుణాన్ని తిరిగి చెల్లించగలదా?",
    REPAYMENT_EXPLANATION: "ఎడమవైపు సంఖ్యలు ఉన్నాయి. కుడివైపు అదే నెలను పోలార్ దృశ్యంలో చూపించాం, కాబట్టి పరిమాణం వెంటనే అర్థమవుతుంది.",
    CALCULATION_NOTE: "ఈఎంఐ = P·r·(1+r)ⁿ ⁄ ((1+r)ⁿ−1) · P ₹9 లక్షలు · 8%/12 · n 84 ⇒ {emi}/నెల · {quarterly}/త్రైమాసికం · నిల్వ {buffer}/నెల · 6 నెలల మారటోరియం",
    REPAYMENT_HEALTH: "తిరిగి చెల్లింపు స్థితి",
    SAFE: "సురక్షితం",
    RAW_INFORMATION: "ముడి సమాచారం లోపలికి.",
    ONE_QUESTION: "ఒక ప్రశ్న లోపలికి.",
    ANALYZE_CTA_UPPER: "నా వ్యాపారాన్ని విశ్లేషించండి",
    PROTOTYPE_NOTE: "ప్రోటోటైప్ · మీ స్థానం కనెక్ట్ అయ్యే వరకు డెమో డేటా",
    LIVE_GEOGRAPHY: "లైవ్ భౌగోళికం · 12,480 అంచనా వినియోగదారులు · 10 కి.మీ. పరిధి",
    DISCOVERY: "అన్వేషణ",
    DEMO_PURPOSES: "YouTube · డెమో ప్రయోజనాల కోసం మాత్రమే",
    OFFICER_PORTAL_ARROW: "అధికారి పోర్టల్ →",
    STARTS_SOMEWHERE: "ఎక్కడో ఒకచోట ప్రారంభమవుతుంది.",
    GRAMINTEL_LOCAL_SIGNAL: "GramIntel ఆ స్థానిక సంకేతాన్ని మీరు సమర్థించగల వ్యాపార నిర్ణయంగా మార్చడంలో సహాయపడుతుంది.",
    LOCAL_PLACES: "స్థానిక ప్రదేశాలు · గండిపేట్ 8 కి.మీ.",
    MARKET: "మార్కెట్",
    FOOD: "ఆహారం",
    FAMOUS_PLACES: "ప్రసిద్ధ ప్రదేశాలు",
    HEALTH: "ఆరోగ్యం",
    EDUCATION: "విద్య",
    FINANCE: "ఫైనాన్స్",
    RETAIL: "రిటైల్",
    TRANSPORT: "రవాణా",
    DEMO_DATA_CLUSTERED: "డెమో డేటా · సమూహీకరించబడింది",
    TITLE_THE_PROBLEM: "సమస్య",
    TITLE_HOW_THINKS: "GRAMINTEL ఎలా ఆలోచిస్తుంది",
    TITLE_MARKET_MAP: "మార్కెట్ మ్యాప్",
    TITLE_MARKET_INTELLIGENCE: "మార్కెట్ సమాచారం · క్లోజ్-అప్",
    TITLE_BUSINESS_VIABILITY: "వ్యాపార సాధ్యత",
    TITLE_INTELLIGENCE_ENGINE: "ఇంటెలిజెన్స్ ఇంజిన్",
    TITLE_FINANCIAL_STRUCTURE: "ఆర్థిక నిర్మాణం",
    TITLE_SCHEME_ROUTING: "పథకం ఎంపిక",
    TITLE_REPAYMENT_SIMULATION: "తిరిగి చెల్లింపు సిమ్యులేషన్",
    TITLE_MULTILINGUAL: "బహుభాషా",
    TITLE_MAKE_IT_DEFENSIBLE: "దీనిని సమర్థించగలిగేలా చేయండి",
    TITLE_SPEAKING_LANGUAGE: "మీ భాషలో మాట్లాడుతుంది",
    TITLE_REASONING_PIPELINE: "తర్క ప్రక్రియ",
    TITLE_MONEY_VISIBLE: "డబ్బును స్పష్టంగా చూపించడం",
    STAGE_LOCATION: "స్థానం",
    STAGE_MARKET: "మార్కెట్",
    STAGE_COMPETITION: "పోటీ",
    STAGE_OPPORTUNITY: "అవకాశం",
    STAGE_FINANCE: "ఆర్థికం",
    STAGE_LOCATION_LINE: "ఒక పిన్. మీ గ్రామం ఆర్థిక మ్యాప్‌పై ఉంచబడింది.",
    STAGE_MARKET_LINE: "చేరుకోగల పరిధిలో వినియోగదారుల సాంద్రత, ఖర్చు శక్తి, రాకపోకలు.",
    STAGE_COMPETITION_LINE: "మీ కస్టమర్లకు ఇప్పటికే సేవ చేస్తున్న ప్రతి దుకాణం — లెక్కించబడింది.",
    STAGE_OPPORTUNITY_LINE: "ప్రజలకు అవసరమైన వాటికి, ఉన్న వాటికి మధ్య ఖాళీ.",
    STAGE_FINANCE_LINE: "ఖర్చులు, రుణాలు, తిరిగి చెల్లింపు — కట్టుబాటుకు ముందు సాధ్యత.",
    FIVE_MOVES: "మ్యాప్‌లోని ఒక బిందువు నుండి బ్యాంకుకు అనుకూల నిర్ణయం వరకు ఐదు అడుగులు.",
    PILLAR_MARKET_DETAIL: "12,480 వినియోగదారులు · 10 కి.మీ. పరిధి",
    PILLAR_OPPORTUNITY_DETAIL: "విలువ జోడించిన పాడి పరిశ్రమ · 78/100 స్కోర్",
    PILLAR_FINANCE_DETAIL: "₹1 లక్ష మార్జిన్ → ₹9 లక్షల రుణం · 8% · 7 సంవత్సరాలు",
    GANDIPET_HYDERABAD: "గండిపేట్ · హైదరాబాద్",
    SMART_INDIA_HACKATHON: "స్మార్ట్ ఇండియా హ్యాకథాన్",
    PROBLEM_HEAD: "గ్రామీణ వ్యవస్థాపకులు స్థానిక డేటా లేకుండానే బిలియన్ల రూపాయల నిర్ణయాలు తీసుకుంటారు.",
    PROBLEM_HEAD_A: "గ్రామీణ వ్యవస్థాపకులు",
    PROBLEM_HEAD_B: "బిలియన్ల రూపాయల నిర్ణయాలు",
    PROBLEM_HEAD_C: "దాదాపు స్థానిక డేటా లేకుండా తీసుకుంటారు.",
    PROBLEM_BODY: "రుణ అధికారి క్రెడిట్ స్కోర్ చూస్తారు. కుటుంబం పూచీకత్తు చూస్తుంది. గ్రామ మార్కెట్‌ను ఎవరూ చూడరు — ఇప్పటి వరకు.",
    SCROLL_SIGNAL: "స్క్రోల్ చేయండి — సంకేతం ఎలా క్రమబద్ధమవుతుందో చూడండి →",
    DEMAND: "డిమాండ్",
    SUPPLY_GAP: "సరఫరా లోటు",
    COMPETITION_LABEL: "పోటీ",
    DEFENSIBLE_HEAD_A: "ఒక",
    DEFENSIBLE_HEAD_B: "సమర్థించగల నిర్ణయం",
    DEFENSIBLE_HEAD_C: "బయటకు వస్తుంది.",
    PIPELINE_BODY: "ప్రశ్నలు అడిగే చాట్‌బాట్ కాదు. మీ సందర్భాన్ని చదివి నిర్మితమైన ఇంటెలిజెన్స్‌ను అందించే ఒక ప్రక్రియ.",
    INPUT: "ఇన్‌పుట్",
    INTELLIGENCE_ENGINE: "ఇంటెలిజెన్స్ ఇంజిన్",
    OUTPUT: "అవుట్‌పుట్",
    MARGIN_FAMILY: "పని చేసే కుటుంబం నిజంగా ఆదా చేసి రిస్క్ చేయగల మొత్తం.",
    DAIRY_UNIT: "పాడి విలువ-వృద్ధి యూనిట్: పరికరాలు, షెడ్, పశువులు, నిర్వహణ మూలధనం.",
    FINANCING_COVERS: "సంస్థాగత ఫైనాన్సింగ్ పొదుపులు భర్తీ చేయలేని భాగాన్ని కవర్ చేస్తుంది.",
    ILLUSTRATIVE_CALCULATION: "ఉదాహరణ గణన · EMI = P·r·(1+r)ⁿ ⁄ ((1+r)ⁿ−1), r = 8%/12, n = 84 · నిర్ణీత",
    THE_DECISION: "నిర్ణయం",
    THE: "",
    DONT_START_LOAN: "రుణంతో ప్రారంభించవద్దు.",
    START_DECISION: "నిర్ణయంతో ప్రారంభించండి.",
    UNDERSTAND_MARKET: "మీ మార్కెట్‌ను అర్థం చేసుకోండి.",
    UNDERSTAND_OPPORTUNITY: "మీ అవకాశాన్ని అర్థం చేసుకోండి.",
    UNDERSTAND_FINANCES: "మీ ఆర్థిక పరిస్థితిని అర్థం చేసుకోండి.",
    GOOD_POTENTIAL_LABEL: "మంచి అవకాశం",
    SUPPLY_RADIUS: "6 కి.మీ. పరిధిలో సరఫరా",
    SPEAK_LANGUAGE_HEAD: "ఇంటెలిజెన్స్ మీ భాషలో మాట్లాడాలి.",
    YOUR_DECISION: "మీ నిర్ణయం, మీ భాషలో.",
    PRODUCT: "ఉత్పత్తి",
    CONTEXT: "సందర్భం",
    CONNECT: "కనెక్ట్",
    THE_METHOD: "పద్ధతి",
    MARKET_INTELLIGENCE: "మార్కెట్ సమాచారం",
    SCHEME_ROUTER: "పథకం ఎంపిక",
    REPAYMENT_PLANNER: "తిరిగి చెల్లింపు ప్లానర్",
    THE_PROBLEM_LINK: "సమస్య",
    DATA_SOURCES: "డేటా మూలాలు",
    IMPACT_MODEL: "ప్రభావ మోడల్",
    FOR_LENDERS: "రుణదాతల కోసం",
    TEAM_GRAMINTEL: "GramIntel బృందం",
    CONTACT: "సంప్రదించండి",
    HYPER_LOCAL: "అతి-స్థానిక ఎంటర్‌ప్రైజ్ ఇంటెలిజెన్స్",
    FOOTER_COPY: "© 2026 GRAMINTEL · మ్యాప్‌లోని ఒక స్థానం నుండి నమ్మకమైన వ్యాపార నిర్ణయం వరకు",
    BUILT_FOR_SIH: "SIH కోసం నిర్మించబడింది",
    LOCAL_DEMAND: "స్థానిక డిమాండ్",
    MILK_RISING: "పరిధిలో పాలు మరియు డెయిరీపై ఖర్చు అత్యంత వేగంగా పెరుగుతోంది.",
    MARKET_QUANTIFIED: "మార్కెట్, కొలవబడింది.",
    MARKET_BODY: "అనుభవజ్ఞుడైన వ్యాపారి సహజంగా చదివే సంకేతాలు — మీ నిర్దిష్ట స్థానానికి లెక్కించబడి, ధర నిర్ణయించబడి, స్కోర్ చేయబడ్డాయి.",
    ESTIMATED_CONSUMERS: "అంచనా వినియోగదారులు",
    SIMILAR_BUSINESSES: "సమాన వ్యాపారాలు",
    PRICE_RANGE: "ధర పరిధి",
    OPPORTUNITY_SCORE: "అవకాశ స్కోర్",
    LOCAL_DEMAND_GEO: "లైవ్ భౌగోళికం · 12,480 అంచనా వినియోగదారులు · 10 కి.మీ. పరిధి",
    RURAL_STARTS: "ప్రతి నమ్మకమైన వ్యాపార నిర్ణయం ఎక్కడో ఒకచోట ప్రారంభమవుతుంది.",
    THE_GAP: "ఖాళీ",
    SCHEME_QUESTION: "ఒక ప్రశ్న లోపలికి.",
    RIGHT_SCHEME: "సరైన పథకం",
    LIGHTS_UP: "వెలుగుతుంది.",
    MICRO_NEED: "నాకు ₹1.40 లక్షల వరకు ప్రాజెక్ట్ కావాలి",
    TERM_NEED: "నా ప్రాజెక్ట్ ఖర్చు ఎక్కువ",
    MICRO_FINANCE: "సూక్ష్మ ఆర్థిక పథకం",
    TERM_LOAN: "కాల పరిమితి రుణ పథకం",
    MUDRA_SHISHU: "ముద్ర శిశు",
    MUDRA_TARUN: "ముద్ర తరుణ్ / పీఎంఈజీపీ",
    MICRO_DETAIL: "≤₹1.40 లక్షలు → సూక్ష్మ · 6.5% · 3 సంవత్సరాలు + 3 నెలలు",
    TERM_DETAIL: ">₹1.40 లక్షలు ≤₹50 లక్షలు → కాల రుణం · 8% · 7 సంవత్సరాలు + 6 నెలలు",
    PROJECT_THRESHOLD: "₹1.40 లక్షల వరకు?",
    SCHEME_FOOTNOTE: "ముద్ర శిశు ≤₹50 వేలు / కిశోర్ ≤₹5 లక్షలు / తరుణ్ ≤₹10 లక్షలను SCA ₹1.40 లక్షల సూక్ష్మ పరిమితికి మ్యాప్ చేశాం",
    SCHEME_GUIDELINES: "అర్హత తర్కం PMMY / PMEGP మార్గదర్శకాలతో సమకాలీకరించబడింది · సూచనాత్మకం",
    RADIUS_10KM: "10 కి.మీ. పరిధి",
    LOCATION_LAYER: "స్థాన పొర",
    VALUE_ADDED_DAIRY: "విలువ ఆధారిత డెయిరీ",
    COMPOSITE_MODEL: "కాంపోజిట్ మోడల్ · గ్రామీణ సూక్ష్మ సంస్థ కోసం సర్దుబాటు చేసిన బరువులు · బరువులు: డిమాండ్ 0.30, సరఫరా 0.20, ధర 0.15, పోటీ 0.15, ఫైనాన్స్ 0.10, రిస్క్ 0.10",
    LIVE_DISCOVERY: "అన్వేషణ",
    FIELD_DOCUMENTATION: "ఫీల్డ్ డాక్యుమెంటేషన్ · గండిపేట్",
    VILLAGE_MARKET_NEED: "ఒక గ్రామం. ఒక మార్కెట్. ఒక అవసరం. ఒక అవకాశం.",
    LOCAL_SIGNAL_SENTENCE: "GramIntel ఆ స్థానిక సంకేతాన్ని మీరు సమర్థించగల వ్యాపార నిర్ణయంగా మార్చడంలో సహాయపడుతుంది.",
    ENTER_EMAIL: "ఈమెయిల్ నమోదు చేయండి",
    ENTER_CODE: "కోడ్ నమోదు చేయండి",
    FAILED: "విఫలమైంది",
    INVALID_CODE: "చెల్లని కోడ్",
    NOT_ADMIN: "ఇది అడ్మిన్ ఖాతా కాదు",
    GOOGLE_SIGNIN_FAILED: "Google సైన్-ఇన్ విఫలమైంది",
    SESSION_EXPIRED: "సెషన్ ముగిసింది — దయచేసి మళ్లీ లాగిన్ చేయండి",
    SELECT_CASE_FIRST: "ముందుగా కేసును ఎంచుకోండి",
    CASE_NOT_LOADED: "కేసు వివరాలు లోడ్ కాలేదు — కేసుపై మళ్లీ క్లిక్ చేయండి",
    NOTE_REQUIRED: "నిర్ణయ గమనిక అవసరం — ఆమోదం/తిరస్కరణ కారణాన్ని టైప్ చేయండి",
    ALREADY_FINAL: "ఇప్పటికే {status} — మరిన్ని మార్పులు లేవు",
    DRAFT_CANNOT_DECIDE: "DRAFTపై నిర్ణయం తీసుకోలేరు — దరఖాస్తుదారు ముందుగా /assistantలో Submit క్లిక్ చేయాలి. ఈ కేసు ఇంకా DRAFTలో ఉంది.",
    DECISION_FAILED: "నిర్ణయం విఫలమైంది",
    HISTORY_UPDATED: "కేసు #{id} {decision} — చరిత్ర నవీకరించబడింది",
    VERIFIED_RECORD: "ధృవీకరించిన డేటా:",
    FALLBACK_RECORD: "సిమ్యులేషన్ ఫాల్‌బ్యాక్:",
    POPULATION: "జనాభా",
    MARGIN: "మార్జిన్",
    PROJECT: "ప్రాజెక్ట్",
    LOAN: "రుణం",
    MONTH: "/నెల",
    MONTHS: "నెలలు",
    QUARTER: "/త్రైమాసికం",
    YEARS: "సంవత్సరాలు",
    MORATORIUM: "మారటోరియం",
    NOT_SIGNED_IN: "సైన్ ఇన్ చేయలేదు",
    OTP_HELP: "OTP 6 అంకెలది మరియు 10 నిమిషాల్లో ముగుస్తుంది (గరిష్టంగా 3 / 10 నిమిషాలు). కోడ్ కాన్ఫిగర్ చేసిన OTP ప్రొవైడర్ ద్వారా పంపబడుతుంది.",
    FEASIBILITY_SIGNALS: "సాధ్యత · 6 సంకేతాలు",
    VERIFIED_GOVERNMENT_DATA: "ధృవీకరించిన ప్రభుత్వ డేటాసెట్:",
    REGIONAL_FALLBACK: "ప్రాంతీయ ప్రాథమిక డేటా (ఫాల్‌బ్యాక్):",
    GROUNDED_IN: "ఆధారం",
    HOUSEHOLDS: "కుటుంబాలు",
    DAIRY_COOPS: "క్లస్టర్‌లో పాడి సహకార సంఘాలు",
    ACTIVE_SHGS: "NRLM స్వయం సహాయక సంఘాలు",
    POWER_GRID: "పవర్ గ్రిడ్",
    REGIONAL_FALLBACK_NOTE: "ప్రాథమిక నమూనాలో గ్రామ జనాభా రికార్డు కనబడలేదు; సర్దుబాటు చేసిన ప్రాంతీయ ఫాల్‌బ్యాక్ ఉపయోగిస్తోంది (12,480 వినియోగదారులు · ₹8.4 లక్షల నెలవారీ డిమాండ్ ఆధారం).",
    SYNTHESISING: "సంశ్లేషిస్తోంది…",
    OPPORTUNITY: "అవకాశం:",
    SWOT_LABEL: "SWOT:",
    THREATS: "ముప్పులు:",
    PRICING: "ధర నిర్ణయం:",
    MODEL_SOURCE: "మోడల్",
    NO_NARRATIVE: "ఇంకా కథనం లేదు — ఒక భాషను ఎంచుకోండి.",
    MONTHLY_SPLIT: "నెలవారీ విభజన · పోలార్ దృశ్యం",
    CASH_FLOW_CHART: "నగదు ప్రవాహం పోలార్ ఏరియా చార్ట్",
    REVENUE: "ఆదాయం",
    COSTS: "ఖర్చులు",
    SURPLUS: "మిగులు",
    BUFFER: "మిగులు నిల్వ",
    INFLOW: "లోపలికి వచ్చే మొత్తం",
    OPERATING: "నిర్వహణ",
    BEFORE_EMI: "EMIకి ముందు",
    STAYS: "మిగులుతుంది",
    MONTHLY_REVENUE: "నెలవారీ ఆదాయం",
    OPERATING_COSTS: "నిర్వహణ ఖర్చులు",
    GROSS_SURPLUS: "స్థూల మిగులు",
    LOAN_REPAYMENT: "రుణ తిరిగి చెల్లింపు (EMI)",
    NET_BUFFER: "నికర నిల్వ",
    INCLUDING_WORKING_CAPITAL: "నిర్వహణ మూలధనం {amount}తో సహా",
    QUARTERLY_LOAN: "రుణం",
    STAYS_WITH_YOU: "మీ వద్ద మిగులుతుంది",
    MONTHLY: "నెలవారీ",
    RADIUS_MONTHLY: "వ్యాసార్థం = నెలవారీ ₹ · కోణం సమానం · మధ్యలో నిల్వ హైలైట్",
    TERM_LOAN_NOTE: "టర్మ్ లోన్ · 8% · 7 సంవత్సరాలు · 6 నెలల మారటోరియం · త్రైమాసికం: ₹{amount}/త్రైమాసికం",
    FAMILY_BUFFER: "{amount} ప్రతి నెలా కుటుంబం చేతుల్లో మిగులుతుంది.",
    LOCATING: "స్థానాన్ని గుర్తిస్తోంది…",
    USE_LOCATION: "నా స్థానాన్ని ఉపయోగించండి",
    LOCATION_UNAVAILABLE: "స్థానం అందుబాటులో లేదు — బదులుగా మీ గ్రామాన్ని శోధించండి. అనుమతితో HTTPSలో మాత్రమే బ్రౌజర్లు స్థానాన్ని పంచుకుంటాయి.",
    GEO_UNSUPPORTED: "ఈ బ్రౌజర్‌లో జియోలొకేషన్‌కు మద్దతు లేదు — బదులుగా మీ గ్రామాన్ని శోధించండి.",
    EXPLORING: "అన్వేషిస్తోంది",
    FUNDED_BUSINESS: "GramIntel నిధులు అందించిన వ్యాపారం",
    FUNDED_BUSINESSES: "GramIntel నిధులు అందించిన వ్యాపారాలు",
    IN_VIEW: "దృశ్యంలో",
    NEARBY: "దగ్గరలో",
    ANALYZE_AREA: "GramIntelలో ఈ ప్రాంతాన్ని విశ్లేషించండి",
    CONTINUES_ASSISTANT: "సహాయకుడిలో {location} · {category}తో కొనసాగుతుంది",
    VERIFIED_DATA: "ధృవీకరించిన డేటా",
    AI_ESTIMATE: "AI అంచనా",
    DEMO_DATA: "డెమో డేటా",
    DATA_SOURCE: "డేటా మూలం",
    MODEL: "మోడల్",
    PROTOTYPE: "ప్రోటోటైప్",
    PUBLIC_DATASET: "పబ్లిక్ డేటాసెట్",
    AI_ESTIMATE_MEDIUM: "AI అంచనా · మధ్యస్థ నమ్మకం",
    SIMULATED_DATA: "సిమ్యులేటెడ్ డేటా · ప్రదర్శన కోసం",
  },
};

export function uiText(lang: UiLang, key: string, vars: Record<string, string | number> = {}): string {
  let value = UI_STRINGS[lang][key] ?? key;
  for (const [name, replacement] of Object.entries(vars)) {
    value = value.replaceAll(`{${name}}`, String(replacement));
  }
  return value;
}

export const UI_KEYS = Object.keys(UI_STRINGS.en);

export const CATEGORY_LABELS: Record<UiLang, Record<string, string>> = {
  en: { Dairy: "Dairy", Retail: "Retail", Food: "Food", Services: "Services", Textile: "Textile", Grocery: "Grocery", Healthcare: "Healthcare", Education: "Education", Agriculture: "Agriculture", Transport: "Transport", Finance: "Finance", Manufacturing: "Manufacturing", Hospitality: "Hospitality", Repair: "Repair", Beauty: "Beauty", Livestock: "Livestock", Other: "Other", Kirana: "Kirana", Poultry: "Poultry", "Food Processing": "Food Processing" },
  hi: { Dairy: "डेयरी", Retail: "खुदरा", Food: "खाद्य", Services: "सेवाएँ", Textile: "वस्त्र", Grocery: "किराना", Healthcare: "स्वास्थ्य सेवा", Education: "शिक्षा", Agriculture: "कृषि", Transport: "परिवहन", Finance: "वित्त", Manufacturing: "विनिर्माण", Hospitality: "आतिथ्य", Repair: "मरम्मत", Beauty: "सौंदर्य", Livestock: "पशुधन", Other: "अन्य", Kirana: "किराना", Poultry: "कुक्कुट पालन", "Food Processing": "खाद्य प्रसंस्करण" },
  te: { Dairy: "పాడి పరిశ్రమ", Retail: "రిటైల్", Food: "ఆహారం", Services: "సేవలు", Textile: "వస్త్రాలు", Grocery: "కిరాణా", Healthcare: "ఆరోగ్య సేవలు", Education: "విద్య", Agriculture: "వ్యవసాయం", Transport: "రవాణా", Finance: "ఫైనాన్స్", Manufacturing: "తయారీ", Hospitality: "ఆతిథ్యం", Repair: "మరమ్మత్తు", Beauty: "అందం", Livestock: "పశుసంపద", Other: "ఇతరాలు", Kirana: "కిరాణా", Poultry: "కోళ్ల పెంపకం", "Food Processing": "ఆహార ప్రాసెసింగ్" },
};

export function categoryText(lang: UiLang, category: string): string {
  return CATEGORY_LABELS[lang][category] ?? category;
}

export const STATUS_LABELS: Record<UiLang, Record<string, string>> = {
  en: { DRAFT: "Draft", SUBMITTED: "Submitted", UNDER_REVIEW: "Under review", APPROVED: "Approved", REJECTED: "Rejected" },
  hi: { DRAFT: "प्रारूप", SUBMITTED: "जमा किया गया", UNDER_REVIEW: "समीक्षा में", APPROVED: "स्वीकृत", REJECTED: "अस्वीकृत" },
  te: { DRAFT: "డ్రాఫ్ట్", SUBMITTED: "సమర్పించబడింది", UNDER_REVIEW: "సమీక్షలో ఉంది", APPROVED: "ఆమోదించబడింది", REJECTED: "తిరస్కరించబడింది" },
};

export function statusText(lang: UiLang, status: string): string {
  return STATUS_LABELS[lang][status] ?? status;
}
